; ----------------------------------------------------------------------------------------------------------------
; script to covert tpp to csv
; ----------------------------------------------------------------------------------------------------------------


RUN PGM=MATRIX
FILEI MATI[1] = "E:\projects\clients\solanoNapa\SNABM\2015_TM151_PPA_V1\skims\nonmotskm.tpp"
FILEO MATO[1] = "E:\projects\clients\solanoNapa\SNABM\2015_TM151_PPA_V1\skims\nonmotskm.csv" MO=1 PATTERN=IJ:V DELIMITER = "," MAXFIELDS=1


ZONE=2400
MW[1] = MI.1.3 ;DIST
;MW[2] = MI.1.11 ;DIST_2Veh
;MW[3] = MI.1.12 ;COST_2Veh

ENDRUN