/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TppMatio */

#ifndef _Included_TppMatio
#define _Included_TppMatio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TppMatio
 * Method:    tppioNative
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_TppMatio_tppioNative
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
