name: tm1_calibration_doc
channels: 
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas>=1.5.0
  - jupyter
  - matplotlib
  - seaborn
  - geopandas
  - numpy
  - tabulate
  - scipy
  - python-dotenv
  - pip
  - pip:
      - "-e ./calib_report"