---
title: "Trip Length Frequency, Morning Commute, Travel Time, Automobile Trips"
author: "David Ory"
output: 
  html_document:
    theme: cosmo
    toc: yes
---


## Administration

#### Purpose
Prepares a bespoke summary of travel model output.  Specifically, for all automobile trips in the morning commute period, writes out the travel mode, trip distance, and trip time. 

#### Outputs
1.  A CSV database with logical names. 


## Procedure

#### Overhead
```{r overhead, results = 'hide'}
library(knitr)
suppressMessages(library(dplyr))
```

```{r config, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

#### Mode look-up table
```{r mode-lookup}
LOOKUP_MODE <- data.frame(trip_mode = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18),
                          mode_name = c("Drive alone - free", "Drive alone - pay", 
                                        "Shared ride two - free", "Shared ride two - pay",
                                        "Shared ride three - free", "Shared ride three - pay",
                                        "Walk", "Bike",
                                        "Walk  to local bus", "Walk to light rail or ferry", "Walk to express bus", 
                                        "Walk to heavy rail", "Walk to commuter rail",
                                        "Drive  to local bus", "Drive to light rail or ferry", "Drive to express bus", 
                                        "Drive to heavy rail", "Drive to commuter rail"))


```


#### Remote file locations and Run name
```{r remote-dir}
TARGET_DIR  <- "M:/Application/Model One/RTP2013/Scenarios/2010_03_YYY/OUTPUT/updated_output/"
OUTPUT_DIR  <- "M:/Application/Model One/RTP2013/Scenarios/2010_03_YYY/OUTPUT/bespoke/"

SCENARIO_ID = "2010_03_YYY"
SAMPLING_RATE = 1.00

# TARGET_DIR  <- "M:/Application/Model One/RTP2013/Scenarios/Round 05 -- Final/2040_03_116/OUTPUT/updated_output/"
# OUTPUT_DIR  <- "M:/Application/Model One/RTP2013/Scenarios/Round 05 -- Final/2040_03_116/OUTPUT/bespoke/"
# 
# SCENARIO_ID = "2040_03_116"
# SAMPLING_RATE = 0.500
```


#### Load, join, compute
```{r data-manips}
# Load
load(paste(TARGET_DIR, "trips.rdata", sep = ""))

# Select variables of interest
trips_working <- trips %>%
  select(trip_mode, timeCode, time, time_fail) %>%
  filter(trip_mode < 7) %>%
  filter(timeCode == "AM") %>%
  mutate(scenario = SCENARIO_ID) %>%
  mutate(trip_weight = 1/SAMPLING_RATE)

table(trips_working$time_fail)

trips_working <- left_join(trips_working, LOOKUP_MODE, by = c("trip_mode"))

trips_summed <- trips_working %>%
  select(scenario, person_trips = trip_weight, time, mode_name) %>%
  mutate(time_int = trunc(time)) %>%
  group_by(scenario, time_int, mode_name) %>%
  summarise(sum_person_trips = sum(person_trips))
```

#### Write to disk
```{r write-disk}
F_OUTPUT = paste(OUTPUT_DIR, "trip-time-automobile-morning-commute.csv", sep = "")
write.csv(trips_summed, file = F_OUTPUT, row.names = FALSE, quote = F)
```
