VARIABLE_TEMPLATES:
    IN_EXPR: "@in_skims['{sk}']"
    TERMINAL_TIME_EXPR: "2 * terminal_time"
    OPERATING_COST_EXPR: "@COST_PER_MILE * (2 * in_skims['{sk}'])"
    DAILY_PARKING_COST: "8 * hourly_parking_cost_for_workers"
    SHORT_WAIT_EXPR: "@(in_skims['{sk}']/100).clip(upper={th})+(in_skims['{sk}']/100).clip(upper={th})"
    LONG_WAIT_EXPR: "@(in_skims['{sk}']/100-{th}).clip(0)+(in_skims['{sk}']/100-{th}).clip(0)"
    VALUE_OF_TIME: "value_of_time"

CONSTANTS:
    COST_PER_MILE: 18.48
    WALK_THRESH: 1.50
    WALK_SPEED: 3.00
    WAIT_THRESH: 10.00
    BIKE_SPEED: 12.00
    BIKE_THRESH: 6.00


