"""Hand-curated crosswalk between CTRAMP UEC row numbers and ActivitySim spec labels.

Each submodel maps asim_label → ctramp_row_number (int) or list of row numbers
when multiple CTRAMP rows collapse to a single ActivitySim row (many-to-one).
Rows that appear on only one side (unmapped) show up automatically via outer join.
"""

# fmt: off

# {submodel_name: {asim_label: ctramp_row_no | [ctramp_row_nos]}}
MAPPINGS: dict[str, dict[str, int | list[int]]] = {

    "Workplace Location": {
        "util_dist_0_1":                       18,
        "util_dist_1_2":                       19,
        "util_dist_2_5":                       20,
        "util_dist_5_15":                      21,
        "util_dist_15_up":                     22,
        "util_dist_0_5_high":                  32,
        "util_dist_15_up_high":                33,
        "util_mode_logsum":                    23,
        "util_size_variable":                  [24, 25, 26, 27],
        "util_no_attractions":                 [28, 29, 30, 31],
        "util_sample_of_corrections_factor":   17,
        "util_sf_to_sf":                       34,
        "util_sf_to_san_mateo":                35,
        "util_sf_to_santa_clara":              36,
        "util_san_mateo_to_santa_clara":       37,
        "util_san_mateo_to_alameda":           38,
        "util_santa_clara_to_sf":              39,
        "util_santa_clara_to_santa_clara":     40,
        "util_alameda_to_santa_clara":         41,
        "util_contra_costa_to_san_mateo":      42,
        "util_contra_costa_to_santa_clara":    43,
    },

    "School Location": {
        "util_sample_of_corrections_factor":   7,
        "util_dist_0_1":                       8,
        "util_dist_1_2":                       9,
        "util_dist_2_5":                       10,
        "util_dist_5_15":                      11,
        "util_dist_15_up":                     12,
        "util_mode_choice_logsum":             13,
        "util_size_variable":                  14,
        "util_no_attractions":                 15,
    },

    "Tour Mode Choice": {
        "util_DRIVEALONEFREE_Unavailable": 157,
        "util_DRIVEALONEFREE_Unavailable_for_zero_auto_households": 158,
        "util_DRIVEALONEFREE_Unavailable_for_persons_less_than_16": 159,
        "util_DRIVEALONEFREE_Unavailable_for_joint_tours": 160,
        "util_DRIVEALONEFREE_Unavailable_if_didn't_drive_to_work": 161,
        "util_DRIVEALONEFREE_In_vehicle_time": 162,
        "util_DRIVEALONEFREE_Terminal_time": 163,
        "util_DRIVEALONEFREE_Operating_cost": 164,
        "util_DRIVEALONEFREE_Parking_cost": 165,
        "util_DRIVEALONEFREE_Bridge_toll": 166,
        "util_DRIVEALONEFREE_Person_is_between_16_and_19_years_old": 167,
        "util_DRIVEALONEPAY_Unavailable": 168,
        "util_DRIVEALONEPAY_Unavailable_for_zero_auto_households": 169,
        "util_DRIVEALONEPAY_Unavailable_for_persons_less_than_16": 170,
        "util_DRIVEALONEPAY_Unavailable_for_joint_tours": 171,
        "util_DRIVEALONEPAY_Unavailable_if_didn't_drive_to_work": 172,
        "util_DRIVEALONEPAY_In_vehicle_time": 173,
        "util_DRIVEALONEPAY_Terminal_time": 174,
        "util_DRIVEALONEPAY_Operating_cost": 175,
        "util_DRIVEALONEPAY_Parking_cost": 176,
        "util_DRIVEALONEPAY_Bridge_toll": 177,
        "util_DRIVEALONEPAY_Value_toll": 178,
        "util_DRIVEALONEPAY_Person_is_between_16_and_19_years_old": 179,
        "util_SHARED2FREE_Unavailable": 180,
        "util_SHARED2FREE_Unavailable_based_on_party_size": 181,
        "util_SHARED2FREE_In_vehicle_time": 182,
        "util_SHARED2FREE_Terminal_time": 183,
        "util_SHARED2FREE_Operating_cost": 184,
        "util_SHARED2FREE_Parking_cost": 185,
        "util_SHARED2FREE_Bridge_toll": 186,
        "util_SHARED2FREE_One_person_household": 187,
        "util_SHARED2FREE_Two_person_household": 188,
        "util_SHARED2FREE_Person_is_16_years_old_or_older": 189,
        "util_SHARED2PAY_Unavailable": 190,
        "util_SHARED2PAY_Unavailable_based_on_party_size": 191,
        "util_SHARED2PAY_In_vehicle_time": 192,
        "util_SHARED2PAY_Terminal_time": 193,
        "util_SHARED2PAY_Operating_cost": 194,
        "util_SHARED2PAY_Parking_cost": 195,
        "util_SHARED2PAY_Bridge_toll": 196,
        "util_SHARED2PAY_Value_toll": 197,
        "util_SHARED2PAY_One_person_household": 198,
        "util_SHARED2PAY_Two_person_household": 199,
        "util_SHARED2PAY_Person_is_16_years_old_or_older": 200,
        "util_SHARED3FREE_Unavailable": 201,
        "util_SHARED3FREE_In_vehicle_time": 202,
        "util_SHARED3FREE_Terminal_time": 203,
        "util_SHARED3FREE_Operating_cost": 204,
        "util_SHARED3FREE_Parking_cost": 205,
        "util_SHARED3FREE_Bridge_toll": 206,
        "util_SHARED3FREE_One_person_household": 207,
        "util_SHARED3FREE_Two_person_household": 208,
        "util_SHARED3FREE_Person_is_16_years_old_or_older": 209,
        "util_SHARED3PAY_Unavailable": 210,
        "util_SHARED3PAY_In_vehicle_time": 211,
        "util_SHARED3PAY_Terminal_time": 212,
        "util_SHARED3PAY_Operating_cost": 213,
        "util_SHARED3PAY_Parking_cost": 214,
        "util_SHARED3PAY_Bridge_toll": 215,
        "util_SHARED3PAY_Value_toll": 216,
        "util_SHARED3PAY_One_person_household": 217,
        "util_SHARED3PAY_Two_person_household": 218,
        "util_SHARED3PAY_Person_is_16_years_old_or_older": 219,
        "util_WALK_Time_up_to_2_miles": 220,
        "util_WALK_Time_beyond_2_of_a_miles": 221,
        "util_WALK_Destination_zone_densityIndex": 222,
        "util_WALK_Topology": 223,
        "util_BIKE_Unavailable_if_didn't_bike_to_work": 224,
        "util_BIKE_Time_up_to_6_miles": 225,
        "util_BIKE_Time_beyond_6_of_a_miles": 226,
        "util_BIKE_Destination_zone_densityIndex": 227,
        "util_BIKE_Topology": 228,
        "util_WALK_LOC_Unavailable": 229,
        "util_WALK_LOC_In_vehicle_time": 230,
        "util_WALK_LOC_Short_iwait_time": 231,
        "util_WALK_LOC_Long_iwait_time": 232,
        "util_WALK_LOC_transfer_wait_time": 233,
        "util_WALK_LOC_number_of_transfers": 234,
        "util_WALK_LOC_Walk_access_time": 235,
        "util_WALK_LOC_Walk_egress_time": 236,
        "util_WALK_LOC_Walk_other_time": 237,
        "util_WALK_LOC_Fare": 238,
        "util_WALK_LOC_Destination_zone_densityIndex": 239,
        "util_WALK_LOC_Topology": 240,
        "util_WALK_LOC_Person_is_less_than_10_years_old": 241,
        "util_WALK_LRF_Unavailable": 242,
        "util_WALK_LRF_In_vehicle_time": 243,
        "util_WALK_LRF_In_vehicle_time_on_Light_Rail": 244,
        "util_WALK_LRF_In_vehicle_time_on_Ferry": 245,
        "util_WALK_LRF_Short_iwait_time": 246,
        "util_WALK_LRF_Long_iwait_time": 247,
        "util_WALK_LRF_transfer_wait_time": 248,
        "util_WALK_LRF_number_of_transfers": 249,
        "util_WALK_LRF_Walk_access_time": 250,
        "util_WALK_LRF_Walk_egress_time": 251,
        "util_WALK_LRF_Walk_other_time": 252,
        "util_WALK_LRF_Fare": 253,
        "util_WALK_LRF_Destination_zone_densityIndex": 254,
        "util_WALK_LRF_Topology": 255,
        "util_WALK_LRF_Person_is_less_than_10_years_old": 256,
        "util_WALK_EXP_Unavailable": 257,
        "util_WALK_EXP_In_vehicle_time": 258,
        "util_WALK_EXP_In_vehicle_time_on_Express_bus": 259,
        "util_WALK_EXP_Short_iwait_time": 260,
        "util_WALK_EXP_Long_iwait_time": 261,
        "util_WALK_EXP_transfer_wait_time": 262,
        "util_WALK_EXP_number_of_transfers": 263,
        "util_WALK_EXP_Walk_access_time": 264,
        "util_WALK_EXP_Walk_egress_time": 265,
        "util_WALK_EXP_Walk_other_time": 266,
        "util_WALK_EXP_Fare": 267,
        "util_WALK_EXP_Destination_zone_densityIndex": 268,
        "util_WALK_EXP_Topology": 269,
        "util_WALK_EXP_Person_is_less_than_10_years_old": 270,
        "util_WALK_HVY_Unavailable": 271,
        "util_WALK_HVY_In_vehicle_time": 272,
        "util_WALK_HVY_In_vehicle_time_on_heavy_rail": 273,
        "util_WALK_HVY_Short_iwait_time": 274,
        "util_WALK_HVY_Long_iwait_time": 275,
        "util_WALK_HVY_transfer_wait_time": 276,
        "util_WALK_HVY_number_of_transfers": 277,
        "util_WALK_HVY_Walk_access_time": 278,
        "util_WALK_HVY_Walk_egress_time": 279,
        "util_WALK_HVY_Walk_other_time": 280,
        "util_WALK_HVY_Fare": 281,
        "util_WALK_HVY_Destination_zone_densityIndex": 282,
        "util_WALK_HVY_Topology": 283,
        "util_WALK_HVY_Person_is_less_than_10_years_old": 284,
        "util_WALK_COM_Unavailable": 285,
        "util_WALK_COM_In_vehicle_time": 286,
        "util_WALK_COM_In_vehicle_time_on_commuter_rail": 287,
        "util_WALK_COM_Short_iwait_time": 288,
        "util_WALK_COM_Long_iwait_time": 289,
        "util_WALK_COM_transfer_wait_time": 290,
        "util_WALK_COM_number_of_transfers": 291,
        "util_WALK_COM_Walk_access_time": 292,
        "util_WALK_COM_Walk_egress_time": 293,
        "util_WALK_COM_Walk_other_time": 294,
        "util_WALK_COM_Fare": 295,
        "util_WALK_COM_Destination_zone_densityIndex": 296,
        "util_WALK_COM_Topology": 297,
        "util_WALK_COM_Person_is_less_than_10_years_old": 298,
        "util_DRIVE_LOC_Unavailable": 299,
        "util_DRIVE_LOC_Unavailable_for_zero_auto_households": 300,
        "util_DRIVE_LOC_Unavailable_for_persons_less_than_16": 301,
        "util_DRIVE_LOC_In_vehicle_time": 302,
        "util_DRIVE_LOC_Short_iwait_time": 303,
        "util_DRIVE_LOC_Long_iwait_time": 304,
        "util_DRIVE_LOC_transfer_wait_time": 305,
        "util_DRIVE_LOC_number_of_transfers": 306,
        "util_DRIVE_LOC_Drive_time": 307,
        "util_DRIVE_LOC_Walk_access_time": 308,
        "util_DRIVE_LOC_Walk_egress_time": 309,
        "util_DRIVE_LOC_Walk_other_time": 310,
        "util_DRIVE_LOC_Fare_and_operating_cost": 311,
        "util_DRIVE_LOC_Ratio_of_drive_access_distance_to_OD_distance": 312,
        "util_DRIVE_LOC_Destination_zone_densityIndex": 313,
        "util_DRIVE_LOC_Topology": 314,
        "util_DRIVE_LOC_Person_is_less_than_10_years_old": 315,
        "util_DRIVE_LRF_Unavailable": 316,
        "util_DRIVE_LRF_Unavailable_for_zero_auto_households": 317,
        "util_DRIVE_LRF_Unavailable_for_persons_less_than_16": 318,
        "util_DRIVE_LRF_In_vehicle_time": 319,
        "util_DRIVE_LRF_In_vehicle_time_on_Light_Rail": 320,
        "util_DRIVE_LRF_In_vehicle_time_on_Ferry": 321,
        "util_DRIVE_LRF_Short_iwait_time": 322,
        "util_DRIVE_LRF_Long_iwait_time": 323,
        "util_DRIVE_LRF_transfer_wait_time": 324,
        "util_DRIVE_LRF_number_of_transfers": 325,
        "util_DRIVE_LRF_Drive_time": 326,
        "util_DRIVE_LRF_Walk_access_time": 327,
        "util_DRIVE_LRF_Walk_egress_time": 328,
        "util_DRIVE_LRF_Walk_other_time": 329,
        "util_DRIVE_LRF_Fare_and_operating_cost": 330,
        "util_DRIVE_LRF_Ratio_of_drive_access_distance_to_OD_distance": 331,
        "util_DRIVE_LRF_Destination_zone_densityIndex": 332,
        "util_DRIVE_LRF_Topology": 333,
        "util_DRIVE_LRF_Person_is_less_than_10_years_old": 334,
        "util_DRIVE_EXP_Unavailable": 335,
        "util_DRIVE_EXP_Unavailable_for_zero_auto_households": 336,
        "util_DRIVE_EXP_Unavailable_for_persons_less_than_16": 337,
        "util_DRIVE_EXP_In_vehicle_time": 338,
        "util_DRIVE_EXP_In_vehicle_time_on_Express_bus": 339,
        "util_DRIVE_EXP_Short_iwait_time": 340,
        "util_DRIVE_EXP_Long_iwait_time": 341,
        "util_DRIVE_EXP_transfer_wait_time": 342,
        "util_DRIVE_EXP_number_of_transfers": 343,
        "util_DRIVE_EXP_Drive_time": 344,
        "util_DRIVE_EXP_Walk_access_time": 345,
        "util_DRIVE_EXP_Walk_egress_ime": 346,
        "util_DRIVE_EXP_Walk_other_time": 347,
        "util_DRIVE_EXP_Fare_and_operating_cost": 348,
        "util_DRIVE_EXP_Ratio_of_drive_access_distance_to_OD_distance": 349,
        "util_DRIVE_EXP_Destination_zone_densityIndex": 350,
        "util_DRIVE_EXP_Topology": 351,
        "util_DRIVE_EXP_Person_is_less_than_10_years_old": 352,
        "util_DRIVE_HVY_Unavailable": 353,
        "util_DRIVE_HVY_Unavailable_for_zero_auto_households": 354,
        "util_DRIVE_HVY_Unavailable_for_persons_less_than_16": 355,
        "util_DRIVE_HVY_In_vehicle_time": 356,
        "util_DRIVE_HVY_In_vehicle_time_on_heavy_rail": 357,
        "util_DRIVE_HVY_Short_iwait_time": 358,
        "util_DRIVE_HVY_Long_iwait_time": 359,
        "util_DRIVE_HVY_transfer_wait_time": 360,
        "util_DRIVE_HVY_number_of_transfers": 361,
        "util_DRIVE_HVY_Drive_time": 362,
        "util_DRIVE_HVY_Walk_access_time": 363,
        "util_DRIVE_HVY_Walk_egress_time": 364,
        "util_DRIVE_HVY_Walk_other_time": 365,
        "util_DRIVE_HVY_Fare_and_operating_cost": 366,
        "util_DRIVE_HVY_Ratio_of_drive_access_distance_to_OD_distance": 367,
        "util_DRIVE_HVY_Destination_zone_densityIndex": 368,
        "util_DRIVE_HVY_Topology": 369,
        "util_DRIVE_HVY_Person_is_less_than_10_years_old": 370,
        "util_DRIVE_COM_Unavailable": 371,
        "util_DRIVE_COM_Unavailable_for_zero_auto_households": 372,
        "util_DRIVE_COM_Unavailable_for_persons_less_than_16": 373,
        "util_DRIVE_COM_In_vehicle_time": 374,
        "util_DRIVE_COM_In_vehicle_time_on_commuter_rail": 375,
        "util_DRIVE_COM_Short_iwait_time": 376,
        "util_DRIVE_COM_Long_iwait_time": 377,
        "util_DRIVE_COM_transfer_wait_time": 378,
        "util_DRIVE_COM_number_of_transfers": 379,
        "util_DRIVE_COM_Drive_time": 380,
        "util_DRIVE_COM_Walk_access_time": 381,
        "util_DRIVE_COM_Walk_egress_time": 382,
        "util_DRIVE_COM_Walk_other_time": 383,
        "util_DRIVE_COM_Fare_and_operating_cost": 384,
        "util_DRIVE_COM_Ratio_of_drive_access_distance_to_OD_distance": 385,
        "util_DRIVE_COM_Destination_zone_densityIndex": 386,
        "util_DRIVE_COM_Topology": 387,
        "util_DRIVE_COM_Person_is_less_than_10_years_old": 388,
        "util_Taxi_In_vehicle_time": 389,
        "util_Taxi_Wait_time": 390,
        "util_Taxi_Tolls": 391,
        "util_Taxi_Bridge_toll": 392,
        "util_Taxi_Fare": 393,
        "util_TNC_Single_In_vehicle_time": 394,
        "util_TNC_Single_Wait_time": 395,
        "util_TNC_Single_Tolls": 396,
        "util_TNC_Single_Bridge_toll": 397,
        "util_TNC_Single_Cost": 398,
        "util_TNC_Shared_In_vehicle_time": 399,
        "util_TNC_Shared_Wait_time": 400,
        "util_TNC_Shared_Tolls": 401,
        "util_TNC_Shared_Bridge_toll": 402,
        "util_TNC_Shared_Cost": 403,
        "util_Walk_ASC_Zero_auto": 404,
        "util_Walk_ASC_Auto_deficient": 405,
        "util_Walk_ASC_Auto_sufficient": 406,
        "util_Bike_ASC_Zero_auto": 407,
        "util_Bike_ASC_Auto_deficient": 408,
        "util_Bike_ASC_Auto_sufficient": 409,
        "util_Shared_ride_2_ASC_Zero_auto": 410,
        "util_Shared_ride_2_ASC_Auto_deficient": 411,
        "util_Shared_ride_2_ASC_Auto_sufficient": 412,
        "util_Shared_ride_3p_Zero_auto": 413,
        "util_Shared_ride_3p_Auto_deficient": 414,
        "util_Shared_ride_3p_Auto_sufficient": 415,
        "util_Walk_to_Transit_Zero_auto": 416,
        "util_Walk_to_Transit_Auto_deficient": 417,
        "util_Walk_to_Transit_Auto_sufficient": 418,
        "util_Drive_to_Transit_Zero_auto": 419,
        "util_Drive_to_Transit_Auto_deficient": 420,
        "util_Drive_to_Transit_Auto_sufficient": 421,
        "util_Taxi_Zero_auto": 422,
        "util_Taxi_Auto_deficient": 423,
        "util_Taxi_Auto_sufficient": 424,
        "util_TNC_Single_Zero_auto": 425,
        "util_TNC_Single_Auto_deficient": 426,
        "util_TNC_Single_Auto_sufficient": 427,
        "util_TNC_Shared_Zero_auto": 428,
        "util_TNC_Shared_Auto_deficient": 429,
        "util_TNC_Shared_Auto_sufficient": 430,
        "util_Joint_Walk_ASC_Zero_auto": 431,
        "util_Joint_Walk_ASC_Auto_deficient": 432,
        "util_Joint_Walk_ASC_Auto_sufficient": 433,
        "util_Joint_Bike_ASC_Zero_auto": 434,
        "util_Joint_Bike_ASC_Auto_deficient": 435,
        "util_Joint_Bike_ASC_Auto_sufficient": 436,
        "util_Joint_Shared_ride_2_ASC_Zero_auto": 437,
        "util_Joint_Shared_ride_2_ASC_Auto_deficient": 438,
        "util_Joint_Shared_ride_2_ASC_Auto_sufficient": 439,
        "util_Joint_Shared_ride_3p_Zero_auto": 440,
        "util_Joint_Shared_ride_3p_Auto_deficient": 441,
        "util_Joint_Shared_ride_3p_Auto_sufficient": 442,
        "util_Joint_Walk_to_Transit_Zero_auto": 443,
        "util_Joint_Walk_to_Transit_Auto_deficient": 444,
        "util_Joint_Walk_to_Transit_Auto_sufficient": 445,
        "util_Joint_Drive_to_Transit_Zero_auto": 446,
        "util_Joint_Drive_to_Transit_Auto_deficient": 447,
        "util_Joint_Drive_to_Transit_Auto_sufficient": 448,
        "util_Joint_Taxi_Zero_auto": 449,
        "util_Joint_Taxi_Auto_deficient": 450,
        "util_Joint_Taxi_Auto_sufficient": 451,
        "util_Joint_TNC_Single_Zero_auto": 452,
        "util_Joint_TNC_Single_Auto_deficient": 453,
        "util_Joint_TNC_Single_Auto_sufficient": 454,
        "util_Joint_TNC_Shared_Zero_auto": 455,
        "util_Joint_TNC_Shared_Auto_deficient": 456,
        "util_Joint_TNC_Shared_Auto_sufficient": 457,
        "util_Local_bus_ASC": 458,
        "util_Walk_to_Light_Rail_ASC": 459,
        "util_Drive_to_Light_Rail_ASC": 460,
        "util_Walk_to_Ferry_ASC": 461,
        "util_Drive_to_Ferry_ASC": 462,
        "util_Express_Bus_ASC": 463,
        "util_Heavy_Rail_ASC": 464,
        "util_Commuter_Rail": 37,
        "util_Walk_to_Transit_dest_CBD": 466,
        "util_Drive_to_Transit_dest_CBD": 467,
        "util_Drive_to_Transit_distance_penalty": 474,
        "util_Walk_not_available_for_long_distances": 475,
        "util_Bike_not_available_for_long_distances": 476,
    },


    "Trip Mode Choice": {
        "util_DRIVEALONEFREE_Unavailable": 170,
        "util_DRIVEALONEFREE_Unavailable_for_zero_auto_households": 171,
        "util_DRIVEALONEFREE_Unavailable_for_persons_less_than_16": 172,
        "util_DRIVEALONEFREE_Unavailable_for_joint_tours": 173,
        "util_DRIVEALONEFREE_Unavailable_if_didn't_drive_to_work": 174,
        "util_DRIVEALONEFREE_In_vehicle_time": 175,
        "util_DRIVEALONEFREE_Terminal_time": 176,
        "util_DRIVEALONEFREE_Operating_cost": 177,
        "util_DRIVEALONEFREE_Parking_cost": 178,
        "util_DRIVEALONEFREE_Bridge_toll": 179,
        "util_DRIVEALONEFREE_Person_is_between_16_and_19_years_old": 180,
        "util_DRIVEALONEPAY_Unavailable": 181,
        "util_DRIVEALONEPAY_Unavailable_for_zero_auto_households": 182,
        "util_DRIVEALONEPAY_Unavailable_for_persons_less_than_16": 183,
        "util_DRIVEALONEPAY_Unavailable_for_joint_tours": 184,
        "util_DRIVEALONEPAY_Unavailable_if_didn't_drive_to_work": 185,
        "util_DRIVEALONEPAY_In_vehicle_time": 186,
        "util_DRIVEALONEPAY_Terminal_time": 187,
        "util_DRIVEALONEPAY_Operating_cost": 188,
        "util_DRIVEALONEPAY_Parking_cost": 189,
        "util_DRIVEALONEPAY_Bridge_toll": 190,
        "util_DRIVEALONEPAY_Value_toll": 191,
        "util_DRIVEALONEPAY_Person_is_between_16_and_19_years_old": 192,
        "util_SHARED2FREE_Unavailable": 193,
        "util_SHARED2FREE_Unavailable_based_on_party_size": 194,
        "util_SHARED2FREE_In_vehicle_time": 195,
        "util_SHARED2FREE_Terminal_time": 196,
        "util_SHARED2FREE_Operating_cost": 197,
        "util_SHARED2FREE_Parking_cost": 198,
        "util_SHARED2FREE_Bridge_toll": 199,
        "util_SHARED2FREE_One_person_household": 200,
        "util_SHARED2FREE_Two_person_household": 201,
        "util_SHARED2FREE_Person_is_16_years_old_or_older": 202,
        "util_SHARED2PAY_Unavailable": 203,
        "util_SHARED2PAY_Unavailable_based_on_party_size": 204,
        "util_SHARED2PAY_In_vehicle_time": 205,
        "util_SHARED2PAY_Terminal_time": 206,
        "util_SHARED2PAY_Operating_cost": 207,
        "util_SHARED2PAY_Parking_cost": 208,
        "util_SHARED2PAY_Bridge_toll": 209,
        "util_SHARED2PAY_Value_toll": 210,
        "util_SHARED2PAY_One_person_household": 211,
        "util_SHARED2PAY_Two_person_household": 212,
        "util_SHARED2PAY_Person_is_16_years_old_or_older": 213,
        "util_SHARED3FREE_Unavailable": 214,
        "util_SHARED3FREE_In_vehicle_time": 215,
        "util_SHARED3FREE_Terminal_time": 216,
        "util_SHARED3FREE_Operating_cost": 217,
        "util_SHARED3FREE_Parking_cost": 218,
        "util_SHARED3FREE_Bridge_toll": 219,
        "util_SHARED3FREE_One_person_household": 220,
        "util_SHARED3FREE_Two_person_household": 221,
        "util_SHARED3FREE_Person_is_16_years_old_or_older": 222,
        "util_SHARED3PAY_Unavailable": 223,
        "util_SHARED3PAY_In_vehicle_time": 224,
        "util_SHARED3PAY_Terminal_time": 225,
        "util_SHARED3PAY_Operating_cost": 226,
        "util_SHARED3PAY_Parking_cost": 227,
        "util_SHARED3PAY_Bridge_toll": 228,
        "util_SHARED3PAY_Value_toll": 229,
        "util_SHARED3PAY_One_person_household": 230,
        "util_SHARED3PAY_Two_person_household": 231,
        "util_SHARED3PAY_Person_is_16_years_old_or_older": 232,
        "util_WALK_Time_up_to_2_miles": 233,
        "util_WALK_Time_beyond_2_of_a_miles": 234,
        "util_WALK_Destination_zone_densityIndex": 235,
        "util_WALK_Topology": 236,
        "util_BIKE_Unavailable_if_didn't_bike_to_work": 237,
        "util_BIKE_Time_up_to_6_miles": 238,
        "util_BIKE_Time_beyond_6_of_a_miles": 239,
        "util_BIKE_Destination_zone_densityIndex": 240,
        "util_BIKE_Topology": 241,
        "util_WALK_LOC_Unavailable": 242,
        "util_WALK_LOC_In_vehicle_time": 243,
        "util_WALK_LOC_Short_iwait_time": 244,
        "util_WALK_LOC_Long_iwait_time": 245,
        "util_WALK_LOC_transfer_wait_time": 246,
        "util_WALK_LOC_number_of_transfers": 247,
        "util_WALK_LOC_Walk_access_time": 248,
        "util_WALK_LOC_Walk_egress_time": 249,
        "util_WALK_LOC_Walk_other_time": 250,
        "util_WALK_LOC_Fare": 251,
        "util_WALK_LOC_Destination_zone_densityIndex": 252,
        "util_WALK_LOC_Topology": 253,
        "util_WALK_LOC_Person_is_less_than_10_years_old": 254,
        "util_WALK_LRF_Unavailable": 255,
        "util_WALK_LRF_In_vehicle_time": 256,
        "util_WALK_LRF_In_vehicle_time_on_Light_Rail": 257,
        "util_WALK_LRF_In_vehicle_time_on_Ferry": 258,
        "util_WALK_LRF_Short_iwait_time": 259,
        "util_WALK_LRF_Long_iwait_time": 260,
        "util_WALK_LRF_transfer_wait_time": 261,
        "util_WALK_LRF_number_of_transfers": 262,
        "util_WALK_LRF_Walk_access_time": 263,
        "util_WALK_LRF_Walk_egress_time": 264,
        "util_WALK_LRF_Walk_other_time": 265,
        "util_WALK_LRF_Fare": 266,
        "util_WALK_LRF_Destination_zone_densityIndex": 267,
        "util_WALK_LRF_Topology": 268,
        "util_WALK_LRF_Person_is_less_than_10_years_old": 269,
        "util_WALK_EXP_Unavailable": 270,
        "util_WALK_EXP_In_vehicle_time": 271,
        "util_WALK_EXP_In_vehicle_time_on_Express_bus": 272,
        "util_WALK_EXP_Short_iwait_time": 273,
        "util_WALK_EXP_Long_iwait_time": 274,
        "util_WALK_EXP_transfer_wait_time": 275,
        "util_WALK_EXP_number_of_transfers": 276,
        "util_WALK_EXP_Walk_access_time": 277,
        "util_WALK_EXP_Walk_egress_time": 278,
        "util_WALK_EXP_Walk_other_time": 279,
        "util_WALK_EXP_Fare": 280,
        "util_WALK_EXP_Destination_zone_densityIndex": 281,
        "util_WALK_EXP_Topology": 282,
        "util_WALK_EXP_Person_is_less_than_10_years_old": 283,
        "util_WALK_HVY_Unavailable": 284,
        "util_WALK_HVY_In_vehicle_time": 285,
        "util_WALK_HVY_In_vehicle_time_on_heavy_rail": 286,
        "util_WALK_HVY_Short_iwait_time": 287,
        "util_WALK_HVY_Long_iwait_time": 288,
        "util_WALK_HVY_transfer_wait_time": 289,
        "util_WALK_HVY_number_of_transfers": 290,
        "util_WALK_HVY_Walk_access_time": 291,
        "util_WALK_HVY_Walk_egress_time": 292,
        "util_WALK_HVY_Walk_other_time": 293,
        "util_WALK_HVY_Fare": 294,
        "util_WALK_HVY_Destination_zone_densityIndex": 295,
        "util_WALK_HVY_Topology": 296,
        "util_WALK_HVY_Person_is_less_than_10_years_old": 297,
        "util_WALK_COM_Unavailable": 298,
        "util_WALK_COM_In_vehicle_time": 299,
        "util_WALK_COM_In_vehicle_time_on_commuter_rail": 300,
        "util_WALK_COM_Short_iwait_time": 301,
        "util_WALK_COM_Long_iwait_time": 302,
        "util_WALK_COM_transfer_wait_time": 303,
        "util_WALK_COM_number_of_transfers": 304,
        "util_WALK_COM_Walk_access_time": 305,
        "util_WALK_COM_Walk_egress_time": 306,
        "util_WALK_COM_Walk_other_time": 307,
        "util_WALK_COM_Fare": 308,
        "util_WALK_COM_Destination_zone_densityIndex": 309,
        "util_WALK_COM_Topology": 310,
        "util_WALK_COM_Person_is_less_than_10_years_old": 311,
        "util_DRIVE_LOC_Unavailable_for_zero_auto_households": 313,
        "util_DRIVE_LOC_Unavailable_for_persons_less_than_16": 314,
        "util_DRIVE_LOC_Destination_zone_densityIndex": 325,
        "util_DRIVE_LOC_Topology": 326,
        "util_DRIVE_LOC_Person_is_less_than_10_years_old": 327,
        "util_DRIVE_LOC_outbound_Unavailable": 312,
        "util_DRIVE_LOC_outbound_In_vehicle_time": 315,
        "util_DRIVE_LOC_outbound_Short_iwait_time": 316,
        "util_DRIVE_LOC_outbound_Long_iwait_time": 317,
        "util_DRIVE_LOC_outbound_transfer_wait_time": 318,
        "util_DRIVE_LOC_outbound_number_of_transfers": 319,
        "util_DRIVE_LOC_outbound_Drive_time": 320,
        "util_DRIVE_LOC_outbound_Walk_egress_time": 321,
        "util_DRIVE_LOC_outbound_Walk_other_time": 322,
        "util_DRIVE_LOC_outbound_Fare_and_operating_cost": 323,
        "util_DRIVE_LOC_outbound_Ratio_of_drive_access_distance_to_OD_distance": 324,
        "util_DRIVE_LOC_inbound_Unavailable": 328,
        "util_DRIVE_LOC_inbound_In_vehicle_time": 331,
        "util_DRIVE_LOC_inbound_Short_iwait_time": 332,
        "util_DRIVE_LOC_inbound_Long_iwait_time": 333,
        "util_DRIVE_LOC_inbound_transfer_wait_time": 334,
        "util_DRIVE_LOC_inbound_number_of_transfers": 335,
        "util_DRIVE_LOC_inbound_Drive_time": 336,
        "util_DRIVE_LOC_inbound_Walk_access_time": 337,
        "util_DRIVE_LOC_inbound_Walk_other_time": 338,
        "util_DRIVE_LOC_inbound_Fare_and_operating_cost": 339,
        "util_DRIVE_LOC_inbound_Ratio_of_drive_access_distance_to_OD_distance": 340,
        "util_DRIVE_LRF_Unavailable_for_zero_auto_households": 345,
        "util_DRIVE_LRF_Unavailable_for_persons_less_than_16": 346,
        "util_DRIVE_LRF_Destination_zone_densityIndex": 359,
        "util_DRIVE_LRF_Topology": 360,
        "util_DRIVE_LRF_Person_is_less_than_10_years_old": 361,
        "util_DRIVE_LRF_outbound_Unavailable": 344,
        "util_DRIVE_LRF_outbound_In_vehicle_time": 347,
        "util_DRIVE_LRF_outbound_In_vehicle_time_on_LR": 348,
        "util_DRIVE_LRF_outbound_In_vehicle_time_on_Ferry": 349,
        "util_DRIVE_LRF_outbound_Short_iwait_time": 350,
        "util_DRIVE_LRF_outbound_Long_iwait_time": 351,
        "util_DRIVE_LRF_outbound_transfer_wait_time": 352,
        "util_DRIVE_LRF_outbound_number_of_transfers": 353,
        "util_DRIVE_LRF_outbound_Drive_time": 354,
        "util_DRIVE_LRF_outbound_Walk_egress_time": 355,
        "util_DRIVE_LRF_outbound_Walk_other_time": 356,
        "util_DRIVE_LRF_outbound_Fare_and_operating_cost": 357,
        "util_DRIVE_LRF_outbound_Ratio_of_drive_access_distance_to_OD_distance": 358,
        "util_DRIVE_LRF_inbound_Unavailable": 362,
        "util_DRIVE_LRF_inbound_In_vehicle_time": 365,
        "util_DRIVE_LRF_inbound_In_vehicle_time_on_LR": 366,
        "util_DRIVE_LRF_inbound_In_vehicle_time_on_Ferry": 367,
        "util_DRIVE_LRF_inbound_Short_iwait_time": 368,
        "util_DRIVE_LRF_inbound_Long_iwait_time": 369,
        "util_DRIVE_LRF_inbound_transfer_wait_time": 370,
        "util_DRIVE_LRF_inbound_number_of_transfers": 371,
        "util_DRIVE_LRF_inbound_Drive_time": 372,
        "util_DRIVE_LRF_inbound_Walk_access_time": 373,
        "util_DRIVE_LRF_inbound_Walk_other_time": 374,
        "util_DRIVE_LRF_inbound_Fare_and_operating_cost": 375,
        "util_DRIVE_LRF_inbound_Ratio_of_drive_access_distance_to_OD_distance": 376,
        "util_DRIVE_EXP_Unavailable_for_zero_auto_households": 381,
        "util_DRIVE_EXP_Unavailable_for_persons_less_than_16": 382,
        "util_DRIVE_EXP_Destination_zone_densityIndex": 394,
        "util_DRIVE_EXP_Topology": 395,
        "util_DRIVE_EXP_Person_is_less_than_10_years_old": 396,
        "util_DRIVE_EXP_outbound_Unavailable": 380,
        "util_DRIVE_EXP_outbound_In_vehicle_time": 383,
        "util_DRIVE_EXP_outbound_In_vehicle_time_on_EXP": 384,
        "util_DRIVE_EXP_outbound_Short_iwait_time": 385,
        "util_DRIVE_EXP_outbound_Long_iwait_time": 386,
        "util_DRIVE_EXP_outbound_transfer_wait_time": 387,
        "util_DRIVE_EXP_outbound_number_of_transfers": 388,
        "util_DRIVE_EXP_outbound_Drive_time": 389,
        "util_DRIVE_EXP_outbound_Walk_egress_time": 390,
        "util_DRIVE_EXP_outbound_Walk_other_time": 391,
        "util_DRIVE_EXP_outbound_Fare_and_operating_cost": 392,
        "util_DRIVE_EXP_outbound_Ratio_of_drive_access_distance_to_OD_distance": 393,
        "util_DRIVE_EXP_inbound_Unavailable": 397,
        "util_DRIVE_EXP_inbound_In_vehicle_time": 400,
        "util_DRIVE_EXP_inbound_In_vehicle_time_on_EXP": 401,
        "util_DRIVE_EXP_inbound_Short_iwait_time": 402,
        "util_DRIVE_EXP_inbound_Long_iwait_time": 403,
        "util_DRIVE_EXP_inbound_transfer_wait_time": 404,
        "util_DRIVE_EXP_inbound_number_of_transfers": 405,
        "util_DRIVE_EXP_inbound_Drive_time": 406,
        "util_DRIVE_EXP_inbound_Walk_access_time": 407,
        "util_DRIVE_EXP_inbound_Walk_other_time": 408,
        "util_DRIVE_EXP_inbound_Fare_and_operating_cost": 409,
        "util_DRIVE_EXP_inbound_Ratio_of_drive_access_distance_to_OD_distance": 410,
        "util_DRIVE_HVY_Unavailable_for_zero_auto_households": 415,
        "util_DRIVE_HVY_Unavailable_for_persons_less_than_16": 416,
        "util_DRIVE_HVY_Destination_zone_densityIndex": 428,
        "util_DRIVE_HVY_Topology": 429,
        "util_DRIVE_HVY_Person_is_less_than_10_years_old": 430,
        "util_DRIVE_HVY_outbound_Unavailable": 414,
        "util_DRIVE_HVY_outbound_In_vehicle_time": 417,
        "util_DRIVE_HVY_outbound_In_vehicle_time_on_HVY": 418,
        "util_DRIVE_HVY_outbound_Short_iwait_time": 419,
        "util_DRIVE_HVY_outbound_Long_iwait_time": 420,
        "util_DRIVE_HVY_outbound_transfer_wait_time": 421,
        "util_DRIVE_HVY_outbound_number_of_transfers": 422,
        "util_DRIVE_HVY_outbound_Drive_time": 423,
        "util_DRIVE_HVY_outbound_Walk_egress_time": 424,
        "util_DRIVE_HVY_outbound_Walk_other_time": 425,
        "util_DRIVE_HVY_outbound_Fare_and_operating_cost": 426,
        "util_DRIVE_HVY_outbound_Ratio_of_drive_access_distance_to_OD_distance": 427,
        "util_DRIVE_HVY_inbound_Unavailable": 431,
        "util_DRIVE_HVY_inbound_In_vehicle_time": 434,
        "util_DRIVE_HVY_inbound_In_vehicle_time_on_HVY": 435,
        "util_DRIVE_HVY_inbound_Short_iwait_time": 436,
        "util_DRIVE_HVY_inbound_Long_iwait_time": 437,
        "util_DRIVE_HVY_inbound_transfer_wait_time": 438,
        "util_DRIVE_HVY_inbound_number_of_transfers": 439,
        "util_DRIVE_HVY_inbound_Drive_time": 440,
        "util_DRIVE_HVY_inbound_Walk_access_time": 441,
        "util_DRIVE_HVY_inbound_Walk_other_time": 442,
        "util_DRIVE_HVY_inbound_Fare_and_operating_cost": 443,
        "util_DRIVE_HVY_inbound_Ratio_of_drive_access_distance_to_OD_distance": 444,
        "util_DRIVE_COM_Unavailable_for_zero_auto_households": 449,
        "util_DRIVE_COM_Unavailable_for_persons_less_than_16": 450,
        "util_DRIVE_COM_Destination_zone_densityIndex": 462,
        "util_DRIVE_COM_Topology": 463,
        "util_DRIVE_COM_Person_is_less_than_10_years_old": 464,
        "util_DRIVE_COM_outbound_Unavailable": 448,
        "util_DRIVE_COM_outbound_In_vehicle_time": 451,
        "util_DRIVE_COM_outbound_In_vehicle_time_on_COM": 452,
        "util_DRIVE_COM_outbound_Short_iwait_time": 453,
        "util_DRIVE_COM_outbound_Long_iwait_time": 454,
        "util_DRIVE_COM_outbound_transfer_wait_time": 455,
        "util_DRIVE_COM_outbound_number_of_transfers": 456,
        "util_DRIVE_COM_outbound_Drive_time": 457,
        "util_DRIVE_COM_outbound_Walk_egress_time": 458,
        "util_DRIVE_COM_outbound_Walk_other_time": 459,
        "util_DRIVE_COM_outbound_Fare_and_operating_cost": 460,
        "util_DRIVE_COM_outbound_Ratio_of_drive_access_distance_to_OD_distance": 461,
        "util_DRIVE_COM_inbound_Unavailable": 465,
        "util_DRIVE_COM_inbound_In_vehicle_time": 468,
        "util_DRIVE_COM_inbound_In_vehicle_time_on_COM": 469,
        "util_DRIVE_COM_inbound_Short_iwait_time": 470,
        "util_DRIVE_COM_inbound_Long_iwait_time": 471,
        "util_DRIVE_COM_inbound_transfer_wait_time": 472,
        "util_DRIVE_COM_inbound_number_of_transfers": 473,
        "util_DRIVE_COM_inbound_Drive_time": 474,
        "util_DRIVE_COM_inbound_Walk_access_time": 475,
        "util_DRIVE_COM_inbound_Walk_other_time": 476,
        "util_DRIVE_COM_inbound_Fare_and_operating_cost": 477,
        "util_DRIVE_COM_inbound_Ratio_of_drive_access_distance_to_OD_distance": 478,
        "util_Taxi_In_vehicle_time": 482,
        "util_Taxi_Wait_time": 483,
        "util_Taxi_Tolls": 484,
        "util_Taxi_Bridge_toll": 485,
        "util_Taxi_Fare": 486,
        "util_TNC_Single_In_vehicle_time": 487,
        "util_TNC_Single_Wait_time": 488,
        "util_TNC_Single_Tolls": 489,
        "util_TNC_Single_Bridge_toll": 490,
        "util_TNC_Single_Cost": 491,
        "util_TNC_Shared_In_vehicle_time": 492,
        "util_TNC_Shared_Wait_time": 493,
        "util_TNC_Shared_Tolls": 494,
        "util_TNC_Shared_Bridge_toll": 495,
        "util_TNC_Shared_Cost": 496,
        "util_tour_mode_is_auto": 69,
        "util_tour_mode_is_walk": 71,
        "util_tour_mode_is_bike": 72,
        "util_tour_mode_is_walk_transit": 73,
        "util_tour_mode_is_drive_transit": 74,
        "util_tour_mode_is_ride_hail": 75,
        "util_Drive_Alone_tour_mode_ASC_shared_ride_2_df_is_indiv": 503,
        "util_Drive_Alone_tour_mode_ASC_shared_ride_3_plus": 504,
        "util_Drive_Alone_tour_mode_ASC_walk": 505,
        "util_Drive_Alone_tour_mode_ASC_ride_hail": 506,
        "util_Shared_Ride_2_tour_mode_ASC_shared_ride_2": 507,
        "util_Shared_Ride_2_tour_mode_ASC_shared_ride_3_plus": 508,
        "util_Shared_Ride_2_tour_mode_ASC_walk": 509,
        "util_Shared_Ride_2_tour_mode_ASC_ride_hail": 510,
        "util_Shared_Ride_3_tour_mode_ASC_shared_ride_2": 511,
        "util_Shared_Ride_3_tour_mode_ASC_shared_ride_3_plus": 512,
        "util_Shared_Ride_3_tour_mode_ASC_walk": 513,
        "util_Shared_Ride_3_tour_mode_ASC_ride_hail": 514,
        "util_Walk_tour_mode_ASC_ride_hail": 515,
        "util_Bike_tour_mode_ASC_walk": 516,
        "util_Bike_tour_mode_ASC_ride_hail": 517,
        "util_Walk_to_Transit_tour_mode_ASC_light_rail": 518,
        "util_Walk_to_Transit_tour_mode_ASC_ferry": 519,
        "util_Walk_to_Transit_tour_mode_ASC_express_bus": 520,
        "util_Walk_to_Transit_tour_mode_ASC_heavy_rail": 521,
        "util_Walk_to_Transit_tour_mode_ASC_commuter_rail": 522,
        "util_Walk_to_Transit_tour_mode_ASC_shared_ride_2": 523,
        "util_Walk_to_Transit_tour_mode_ASC_shared_ride_3_plus": 524,
        "util_Walk_to_Transit_tour_mode_ASC_walk": 525,
        "util_Walk_to_Transit_tour_mode_ASC_ride_hail": 526,
        "util_Drive_to_Transit_tour_mode_ASC_light_rail_skims_differ": 527,
        "util_Drive_to_Transit_tour_mode_ASC_ferry": 528,
        "util_Drive_to_Transit_tour_mode_ASC_express_bus": 529,
        "util_Drive_to_Transit_tour_mode_ASC_heavy_rail": 530,
        "util_Drive_to_Transit_tour_mode_ASC_commuter_rail": 531,
        "util_Drive_to_Transit_tour_mode_ASC_ride_hail": 532,
        "util_Ride_Hail_tour_mode_ASC_shared_ride_2": 533,
        "util_Ride_Hail_tour_mode_ASC_shared_ride_3_plus": 534,
        "util_Ride_Hail_tour_mode_ASC_walk": 535,
        "util_Ride_Hail_tour_mode_ASC_walk_to_transit": 536,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_taxi": 537,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_single": 538,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_shared": 539,
        "util_Walk_not_available_for_long_distances": 540,
        "util_Bike_not_available_for_long_distances": 541,
        "util_origin_density_index": 27,
        "util_walk_express_penalty": 543,
        "util_adjust_tnc_shared": 555,
    },

}

# Explanatory notes for rows that appear on only one side or as many-to-one.
# {submodel: {label_or_"row_N": note_text}}
NOTES: dict[str, dict[str, str]] = {

    "Workplace Location": {
        # Many-to-one: CTRAMP has per-income-segment rows, ASim uses size_terms table
        "util_size_variable": (
            "CTRAMP rows 24-27 are per-income-segment size variables (low/med/high/veryhigh) "
            "with identical coeff=1. ActivitySim handles segmentation via "
            "destination_choice_size_terms.csv, so one spec row suffices."
        ),
        "util_no_attractions": (
            "CTRAMP rows 28-31 are per-income-segment no-attractions penalties "
            "(coeff=-999). ActivitySim applies the same penalty across segments "
            "via a single spec row; segmentation is in the size terms table."
        ),
        # ASim-only: no CTRAMP equivalent
        "local_dist": (
            "Intermediate variable that caches skims['DIST'] for reuse by "
            "downstream distance-band expressions. Not a utility term."
        ),
        "local_home_county": (
            "Intermediate variable that looks up the origin county_id for "
            "county-to-county constant expressions. Not a utility term."
        ),
        "util_utility_adjustment": (
            "ActivitySim shadow pricing mechanism — iteratively adjusts zone "
            "attractiveness to match aggregate targets. CTRAMP uses a different "
            "shadow pricing implementation outside the UEC."
        ),
    },

    "School Location": {
        "local_dist": (
            "Intermediate variable that caches skims['DIST'] for reuse by "
            "downstream distance-band expressions. Not a utility term."
        ),
        "util_utility_adjustment": (
            "ActivitySim shadow pricing mechanism — iteratively adjusts zone "
            "attractiveness to match aggregate targets. CTRAMP uses a different "
            "shadow pricing implementation outside the UEC."
        ),
    },
}

# Crosswalk for size-terms: CTRAMP (purpose, segment) → ASim (model_selector, segment)
SIZE_TERMS_CROSSWALK: dict[tuple[str, str], tuple[str, str]] = {
    ("work", "low"):            ("workplace", "work_low"),
    ("work", "med"):            ("workplace", "work_med"),
    ("work", "high"):           ("workplace", "work_high"),
    ("work", "very high"):      ("workplace", "work_veryhigh"),
    ("university", "university"): ("school", "university"),
    ("school", "grade"):        ("school", "gradeschool"),
    ("school", "high"):         ("school", "highschool"),
    ("escort", "kids"):         ("non_mandatory", "escort_kids"),
    ("escort", "no kids"):      ("non_mandatory", "escort_nokids"),
    ("shopping", "shopping"):   ("non_mandatory", "shopping"),
    ("eatout", "eatout"):       ("non_mandatory", "eatout"),
    ("othmaint", "othmaint"):   ("non_mandatory", "othmaint"),
    ("social", "social"):       ("non_mandatory", "social"),
    ("othdiscr", "othdiscr"):   ("non_mandatory", "othdiscr"),
    ("atwork", "atwork"):       ("atwork", "atwork"),
}

# fmt: on
