"""Hand-curated crosswalk between CTRAMP UEC row numbers and ActivitySim spec labels.

Each submodel maps asim_label → ctramp_row_number (int) or list of row numbers
when multiple CTRAMP rows collapse to a single ActivitySim row (many-to-one).
When row numbers differ across purpose sheets, use a dict with "*" as default
and sheet names as overrides: {"*": 463, "OthMaint": 461, "WorkBased": 466}.
Rows that appear on only one side (unmapped) show up automatically via outer join.
"""

# fmt: off

# {submodel_name: {asim_label: ctramp_row_no | [ctramp_row_nos] | {"*": default, "SheetName": override}}}
MAPPINGS: dict[str, dict[str, int | list[int] | dict[str, int]]] = {

    "Workplace Location": {
        "util_dist_0_1":                       18,
        "util_dist_1_2":                       19,
        "util_dist_2_5":                       20,
        "util_dist_5_15":                      21,
        "util_dist_15_up":                     22,
        "util_dist_0_5_high":                  32,
        "util_dist_15_up_high":                33,
        "util_mode_logsum":                    23,
        "util_size_variable":                  [24, 25, 26, 27],
        "util_no_attractions":                 [28, 29, 30, 31],
        "util_sample_of_corrections_factor":   17,
        "util_sf_to_sf":                       34,
        "util_sf_to_san_mateo":                35,
        "util_sf_to_santa_clara":              36,
        "util_san_mateo_to_santa_clara":       37,
        "util_san_mateo_to_alameda":           38,
        "util_santa_clara_to_sf":              39,
        "util_santa_clara_to_santa_clara":     40,
        "util_alameda_to_santa_clara":         41,
        "util_contra_costa_to_san_mateo":      42,
        "util_contra_costa_to_santa_clara":    43,
    },

    "School Location": {
        "util_sample_of_corrections_factor":   7,
        "util_dist_0_1":                       8,
        "util_dist_1_2":                       9,
        "util_dist_2_5":                       10,
        "util_dist_5_15":                      11,
        "util_dist_15_up":                     12,
        "util_mode_choice_logsum":             13,
        "util_size_variable":                  14,
        "util_no_attractions":                 15,
    },

    "Auto Ownership": {
        "util_drivers_2":                      21,
        "util_drivers_3":                      22,
        "util_drivers_4_up":                   23,
        "util_persons_16_17":                  24,
        "util_persons_18_24":                  25,
        "util_persons_25_34":                  26,
        "util_presence_children_0_4":          27,
        "util_presence_children_5_17":         28,
        "util_num_workers_clip_3":             29,
        "util_hh_income_0_30k":               30,
        "util_hh_income_30_75k":              31,
        "util_hh_income_75k_up":              32,
        "util_density_0_10_no_workers":        33,
        "util_density_10_up_no_workers":       34,
        "util_density_0_10_workers":           35,
        "util_density_10_up_workers":          36,
        "util_retail_auto_no_workers":         37,
        "util_retail_auto_workers":            38,
        "util_retail_transit_no_workers":      39,
        "util_retail_transit_workers":         40,
        "util_retail_non_motor_no_workers":    41,
        "util_retail_non_motor_workers":       42,
        "util_auto_time_saving_per_worker":    43,
        "util_asc":                            44,
        "util_asc_san_francisco":              45,
        "util_asc_solano":                     46,
        "util_asc_napa":                       47,
        "util_asc_sonoma":                     48,
        "util_asc_marin":                      49,
        "util_asc_santa_clara":                50,
        # AV rows (rows 51-65) — only affect AV alts
        "util_av_asc_income_under_50k":        51,
        "util_av_asc_income_100k_up":          52,
        "util_av_auto_time_per_worker":        53,
        "util_av_asc_100pct":                  54,
        "util_av_asc_95pct":                   55,
        "util_av_asc_75pct":                   56,
        "util_av_asc_50pct":                   57,
        "util_av_asc_30pct":                   58,
        "util_av_asc_25pct":                   59,
        "util_av_asc_20pct":                   60,
        "util_av_asc_15pct":                   61,
        "util_av_asc_10pct":                   62,
        "util_av_asc_5pct":                    63,
        "util_av_asc_3pct":                    64,
        "util_av_asc_0pct":                    65,
    },

    "CDAP": {
        "Full-time worker alternative-specific constants":           29,
        "Part-time worker alternative-specific constants":           30,
        "University student alternative-specific constants":         31,
        "Non-working adult alternative-specific constants":          32,
        "Retired alternative-specific constants":                    33,
        "Driving-age child who is in school alternative-specific constants": 34,
        "Pre-driving-age child who is in school alternative-specific constants": 35,
        "Pre-driving-age child who is too young for school alternative-specific constants": 36,
        "Pre-driving-age child who is too young for school interaction with age 0 to 1": 37,
        "Pre-driving-age child who is too young for school interaction with age 4 to 5": 38,
        "Pre-driving-age child who is in school interaction with age 6 to 9": 39,
        "Pre-driving-age child who is in school interaction with age 13 to 15": 40,
        "Full-time worker interaction with age less than 40":       41,
        "Retired interaction with age more than 80":                42,
        "Full-time worker interaction with female gender":          43,
        "Non-working adult interaction with female gender":         44,
        "Retired interaction with female":                          45,
        "Non-working adult interaction with more cars than workers": 46,
        "Retired interaction with more cars than workers":          47,
        "Pre-driving-age child who is too young for school interaction with more cars than workers": 48,
        "Full-time worker interaction with fewer cars than workers": 49,
        "Non-working adult interaction with fewer cars than workers": 50,
        "Retired interaction with fewer cars than workers":         51,
        "Driving-age child who is in school interaction with fewer cars than workers": 52,
        "Pre-driving-age child who is in school interaction with fewer cars than workers": 53,
        "Pre-driving-age child who is too young for school interaction with fewer cars than workers": 54,
        "Full-time worker interaction with income less than $20k":  55,
        "Retired interaction with income less than $20k":           56,
        "Part-time worker interaction with income less than $20k":  57,
        "Part-time worker interaction with income between $50k and $100k": 58,
        "Part-time worker interaction with income more than $100k": 59,
        "Non-working adult interaction with income between $50k and $100k": 60,
        "Non-working adult interaction with income more than $100k": 61,
        "Driving-age child who is in school interaction with less than $20k": 62,
        "Driving-age child who is in school interaction income between $50k and $100k": 63,
        "Driving-age child who is in school interaction with income more than $100k": 64,
        "Pre-driving-age child who is too young for school interaction with income between $50k and $100k": 65,
        "Pre-driving-age child who is too young for school interaction with income more than $100k": 66,
        "Full-time worker intraction with peak accessibility to all employment": 67,
        "Part-time worker interaction with peak accessibility to all employment": 68,
        "Non-working adult interaction with peak accessibility to all employment": 69,
        "Retired interaction with peak accessibility to all employment": 70,
        "Non-working adult interaction with off-peak accessibility to retail": 71,
        "Retired interaction with off-peak accessibility to retail": 72,
        "University student interaction with off-peak accessibility to retail": 73,
        "Driving-age child who is in school interaction with off-peak accessibility to retail": 74,
        "Pre-driving-age child who is in school interaction with off-peak accessibility to retail": 75,
        "Pre-driving-age child who is too young for school interaction with off-peak accessibility to retail": 76,
        # WFH interaction rows (CTRAMP rows 77-87)
        "WFH worker interaction (FT)":                             77,
        "WFH worker interaction (PT)":                             78,
        # Rows 79-82: no-usual-location penalties — dead code in MTC (tokens always 0)
        # Rows 83-84: retired/non-working M unavailable — covered by ptype ASC rows 32-33
        "Mandatory unavailable for WFH workers":                   85,
        "FT worker M-pattern boost (post-WFH extraction)":         86,
        "PT worker M-pattern boost (post-WFH extraction)":         87,
    },

    "Work From Home": {
        "Estimated constant":                    12,
        "HH income 75-100k (2023$)":             13,
        "HH income 100-200k (2023$)":            14,
        "HH income 200k+ (2023$)":               15,
        "Industry: Agriculture/natural resources": 16,
        "Industry: Health/education/recreation":  17,
        "Industry: Manufacturing/wholesale/transport": 18,
        "Industry: Retail trade":                19,
        "Home county is North Bay":              20,
        "Work county is San Francisco":          21,
        "East Bay to/from SF commute":           22,
        "Distance home to work":                 23,
        "Calibration constant":                  24,
        # EN7 superdistrict-level calibration boosts (rows 25-58)
        "EN7 Boost for Superdistrict 01":        25,
        "EN7 Boost for Superdistrict 02":        26,
        "EN7 Boost for Superdistrict 03":        27,
        "EN7 Boost for Superdistrict 04":        28,
        "EN7 Boost for Superdistrict 05":        29,
        "EN7 Boost for Superdistrict 06":        30,
        "EN7 Boost for Superdistrict 07":        31,
        "EN7 Boost for Superdistrict 08":        32,
        "EN7 Boost for Superdistrict 09":        33,
        "EN7 Boost for Superdistrict 10":        34,
        "EN7 Boost for Superdistrict 11":        35,
        "EN7 Boost for Superdistrict 12":        36,
        "EN7 Boost for Superdistrict 13":        37,
        "EN7 Boost for Superdistrict 14":        38,
        "EN7 Boost for Superdistrict 15":        39,
        "EN7 Boost for Superdistrict 16":        40,
        "EN7 Boost for Superdistrict 17":        41,
        "EN7 Boost for Superdistrict 18":        42,
        "EN7 Boost for Superdistrict 19":        43,
        "EN7 Boost for Superdistrict 20":        44,
        "EN7 Boost for Superdistrict 21":        45,
        "EN7 Boost for Superdistrict 22":        46,
        "EN7 Boost for Superdistrict 23":        47,
        "EN7 Boost for Superdistrict 24":        48,
        "EN7 Boost for Superdistrict 25":        49,
        "EN7 Boost for Superdistrict 26":        50,
        "EN7 Boost for Superdistrict 27":        51,
        "EN7 Boost for Superdistrict 28":        52,
        "EN7 Boost for Superdistrict 29":        53,
        "EN7 Boost for Superdistrict 30":        54,
        "EN7 Boost for Superdistrict 31":        55,
        "EN7 Boost for Superdistrict 32":        56,
        "EN7 Boost for Superdistrict 33":        57,
        "EN7 Boost for Superdistrict 34":        58,
    },

    "Tour Mode Choice": {
        "util_DRIVEALONEFREE_Unavailable": 157,
        "util_DRIVEALONEFREE_Unavailable_for_zero_auto_households": 158,
        "util_DRIVEALONEFREE_Unavailable_for_persons_less_than_16": 159,
        "util_DRIVEALONEFREE_Unavailable_for_joint_tours": 160,
        # tourCategorySubtour==1 filter: only fires on WorkBased; other sheets effectively 0
        "util_DRIVEALONEFREE_Unavailable_if_didn't_drive_to_work": {"WorkBased": 164, "*": None},
        "util_DRIVEALONEFREE_In_vehicle_time": 162,
        "util_DRIVEALONEFREE_Terminal_time": 163,
        "util_DRIVEALONEFREE_Operating_cost": 164,
        "util_DRIVEALONEFREE_Parking_cost": 165,
        "util_DRIVEALONEFREE_Bridge_toll": 166,
        "util_DRIVEALONEFREE_Person_is_between_16_and_19_years_old": 167,
        "util_DRIVEALONEPAY_Unavailable": 168,
        "util_DRIVEALONEPAY_Unavailable_for_zero_auto_households": 169,
        "util_DRIVEALONEPAY_Unavailable_for_persons_less_than_16": 170,
        "util_DRIVEALONEPAY_Unavailable_for_joint_tours": 171,
        "util_DRIVEALONEPAY_Unavailable_if_didn't_drive_to_work": {"WorkBased": 175, "*": None},
        "util_DRIVEALONEPAY_In_vehicle_time": 173,
        "util_DRIVEALONEPAY_Terminal_time": 174,
        "util_DRIVEALONEPAY_Operating_cost": 175,
        "util_DRIVEALONEPAY_Parking_cost": 176,
        "util_DRIVEALONEPAY_Bridge_toll": 177,
        "util_DRIVEALONEPAY_Value_toll": 178,
        "util_DRIVEALONEPAY_Person_is_between_16_and_19_years_old": 179,
        "util_SHARED2FREE_Unavailable": 180,
        "util_SHARED2FREE_Unavailable_based_on_party_size": 181,
        "util_SHARED2FREE_In_vehicle_time": 182,
        "util_SHARED2FREE_Terminal_time": 183,
        "util_SHARED2FREE_Operating_cost": 184,
        "util_SHARED2FREE_Parking_cost": 185,
        "util_SHARED2FREE_Bridge_toll": 186,
        "util_SHARED2FREE_One_person_household": 187,
        "util_SHARED2FREE_Two_person_household": 188,
        "util_SHARED2FREE_Person_is_16_years_old_or_older": 189,
        "util_SHARED2PAY_Unavailable": 190,
        "util_SHARED2PAY_Unavailable_based_on_party_size": 191,
        "util_SHARED2PAY_In_vehicle_time": 192,
        "util_SHARED2PAY_Terminal_time": 193,
        "util_SHARED2PAY_Operating_cost": 194,
        "util_SHARED2PAY_Parking_cost": 195,
        "util_SHARED2PAY_Bridge_toll": 196,
        "util_SHARED2PAY_Value_toll": 197,
        "util_SHARED2PAY_One_person_household": 198,
        "util_SHARED2PAY_Two_person_household": 199,
        "util_SHARED2PAY_Person_is_16_years_old_or_older": 200,
        "util_SHARED3FREE_Unavailable": 201,
        "util_SHARED3FREE_In_vehicle_time": 202,
        "util_SHARED3FREE_Terminal_time": 203,
        "util_SHARED3FREE_Operating_cost": 204,
        "util_SHARED3FREE_Parking_cost": 205,
        "util_SHARED3FREE_Bridge_toll": 206,
        "util_SHARED3FREE_One_person_household": 207,
        "util_SHARED3FREE_Two_person_household": 208,
        "util_SHARED3FREE_Person_is_16_years_old_or_older": 209,
        "util_SHARED3PAY_Unavailable": 210,
        "util_SHARED3PAY_In_vehicle_time": 211,
        "util_SHARED3PAY_Terminal_time": 212,
        "util_SHARED3PAY_Operating_cost": 213,
        "util_SHARED3PAY_Parking_cost": 214,
        "util_SHARED3PAY_Bridge_toll": 215,
        "util_SHARED3PAY_Value_toll": 216,
        "util_SHARED3PAY_One_person_household": 217,
        "util_SHARED3PAY_Two_person_household": 218,
        "util_SHARED3PAY_Person_is_16_years_old_or_older": 219,
        "util_WALK_Time_up_to_2_miles": 220,
        "util_WALK_Time_beyond_2_of_a_miles": 221,
        "util_WALK_Destination_zone_densityIndex": 222,
        "util_WALK_Topology": 223,
        "util_BIKE_Unavailable_if_didn't_bike_to_work": {"WorkBased": 227, "*": None},
        "util_BIKE_Time_up_to_6_miles": 225,
        "util_BIKE_Time_beyond_6_of_a_miles": 226,
        "util_BIKE_Destination_zone_densityIndex": 227,
        "util_BIKE_Topology": 228,
        "util_WALK_LOC_Unavailable": 229,
        "util_WALK_LOC_In_vehicle_time": 230,
        "util_WALK_LOC_Short_iwait_time": 231,
        "util_WALK_LOC_Long_iwait_time": 232,
        "util_WALK_LOC_transfer_wait_time": 233,
        "util_WALK_LOC_number_of_transfers": 234,
        "util_WALK_LOC_Walk_access_time": 235,
        "util_WALK_LOC_Walk_egress_time": 236,
        "util_WALK_LOC_Walk_other_time": 237,
        "util_WALK_LOC_Fare": 238,
        "util_WALK_LOC_Destination_zone_densityIndex": 239,
        "util_WALK_LOC_Topology": 240,
        "util_WALK_LOC_Person_is_less_than_10_years_old": 241,
        "util_WALK_LRF_Unavailable": 242,
        "util_WALK_LRF_In_vehicle_time": 243,
        "util_WALK_LRF_In_vehicle_time_on_Light_Rail": 244,
        "util_WALK_LRF_In_vehicle_time_on_Ferry": 245,
        "util_WALK_LRF_Short_iwait_time": 246,
        "util_WALK_LRF_Long_iwait_time": 247,
        "util_WALK_LRF_transfer_wait_time": 248,
        "util_WALK_LRF_number_of_transfers": 249,
        "util_WALK_LRF_Walk_access_time": 250,
        "util_WALK_LRF_Walk_egress_time": 251,
        "util_WALK_LRF_Walk_other_time": 252,
        "util_WALK_LRF_Fare": 253,
        "util_WALK_LRF_Destination_zone_densityIndex": 254,
        "util_WALK_LRF_Topology": 255,
        "util_WALK_LRF_Person_is_less_than_10_years_old": 256,
        "util_WALK_EXP_Unavailable": 257,
        "util_WALK_EXP_In_vehicle_time": 258,
        "util_WALK_EXP_In_vehicle_time_on_Express_bus": 259,
        "util_WALK_EXP_Short_iwait_time": 260,
        "util_WALK_EXP_Long_iwait_time": 261,
        "util_WALK_EXP_transfer_wait_time": 262,
        "util_WALK_EXP_number_of_transfers": 263,
        "util_WALK_EXP_Walk_access_time": 264,
        "util_WALK_EXP_Walk_egress_time": 265,
        "util_WALK_EXP_Walk_other_time": 266,
        "util_WALK_EXP_Fare": 267,
        "util_WALK_EXP_Destination_zone_densityIndex": 268,
        "util_WALK_EXP_Topology": 269,
        "util_WALK_EXP_Person_is_less_than_10_years_old": 270,
        "util_WALK_HVY_Unavailable": 271,
        "util_WALK_HVY_In_vehicle_time": 272,
        "util_WALK_HVY_In_vehicle_time_on_heavy_rail": 273,
        "util_WALK_HVY_Short_iwait_time": 274,
        "util_WALK_HVY_Long_iwait_time": 275,
        "util_WALK_HVY_transfer_wait_time": 276,
        "util_WALK_HVY_number_of_transfers": 277,
        "util_WALK_HVY_Walk_access_time": 278,
        "util_WALK_HVY_Walk_egress_time": 279,
        "util_WALK_HVY_Walk_other_time": 280,
        "util_WALK_HVY_Fare": 281,
        "util_WALK_HVY_Destination_zone_densityIndex": 282,
        "util_WALK_HVY_Topology": 283,
        "util_WALK_HVY_Person_is_less_than_10_years_old": 284,
        "util_WALK_COM_Unavailable": 285,
        "util_WALK_COM_In_vehicle_time": 286,
        "util_WALK_COM_In_vehicle_time_on_commuter_rail": 287,
        "util_WALK_COM_Short_iwait_time": 288,
        "util_WALK_COM_Long_iwait_time": 289,
        "util_WALK_COM_transfer_wait_time": 290,
        "util_WALK_COM_number_of_transfers": 291,
        "util_WALK_COM_Walk_access_time": 292,
        "util_WALK_COM_Walk_egress_time": 293,
        "util_WALK_COM_Walk_other_time": 294,
        "util_WALK_COM_Fare": 295,
        "util_WALK_COM_Destination_zone_densityIndex": 296,
        "util_WALK_COM_Topology": 297,
        "util_WALK_COM_Person_is_less_than_10_years_old": 298,
        "util_DRIVE_LOC_Unavailable": 299,
        "util_DRIVE_LOC_Unavailable_for_zero_auto_households": 300,
        "util_DRIVE_LOC_Unavailable_for_persons_less_than_16": 301,
        "util_DRIVE_LOC_In_vehicle_time": 302,
        "util_DRIVE_LOC_Short_iwait_time": 303,
        "util_DRIVE_LOC_Long_iwait_time": 304,
        "util_DRIVE_LOC_transfer_wait_time": 305,
        "util_DRIVE_LOC_number_of_transfers": 306,
        "util_DRIVE_LOC_Drive_time": 307,
        "util_DRIVE_LOC_Walk_access_time": 308,
        "util_DRIVE_LOC_Walk_egress_time": 309,
        "util_DRIVE_LOC_Walk_other_time": 310,
        "util_DRIVE_LOC_Fare_and_operating_cost": 311,
        "util_DRIVE_LOC_Ratio_of_drive_access_distance_to_OD_distance": 312,
        "util_DRIVE_LOC_Destination_zone_densityIndex": 313,
        "util_DRIVE_LOC_Topology": 314,
        "util_DRIVE_LOC_Person_is_less_than_10_years_old": 315,
        "util_DRIVE_LRF_Unavailable": 316,
        "util_DRIVE_LRF_Unavailable_for_zero_auto_households": 317,
        "util_DRIVE_LRF_Unavailable_for_persons_less_than_16": 318,
        "util_DRIVE_LRF_In_vehicle_time": 319,
        "util_DRIVE_LRF_In_vehicle_time_on_Light_Rail": 320,
        "util_DRIVE_LRF_In_vehicle_time_on_Ferry": 321,
        "util_DRIVE_LRF_Short_iwait_time": 322,
        "util_DRIVE_LRF_Long_iwait_time": 323,
        "util_DRIVE_LRF_transfer_wait_time": 324,
        "util_DRIVE_LRF_number_of_transfers": 325,
        "util_DRIVE_LRF_Drive_time": 326,
        "util_DRIVE_LRF_Walk_access_time": 327,
        "util_DRIVE_LRF_Walk_egress_time": 328,
        "util_DRIVE_LRF_Walk_other_time": 329,
        "util_DRIVE_LRF_Fare_and_operating_cost": 330,
        "util_DRIVE_LRF_Ratio_of_drive_access_distance_to_OD_distance": 331,
        "util_DRIVE_LRF_Destination_zone_densityIndex": 332,
        "util_DRIVE_LRF_Topology": 333,
        "util_DRIVE_LRF_Person_is_less_than_10_years_old": 334,
        "util_DRIVE_EXP_Unavailable": 335,
        "util_DRIVE_EXP_Unavailable_for_zero_auto_households": 336,
        "util_DRIVE_EXP_Unavailable_for_persons_less_than_16": 337,
        "util_DRIVE_EXP_In_vehicle_time": 338,
        "util_DRIVE_EXP_In_vehicle_time_on_Express_bus": 339,
        "util_DRIVE_EXP_Short_iwait_time": 340,
        "util_DRIVE_EXP_Long_iwait_time": 341,
        "util_DRIVE_EXP_transfer_wait_time": 342,
        "util_DRIVE_EXP_number_of_transfers": 343,
        "util_DRIVE_EXP_Drive_time": 344,
        "util_DRIVE_EXP_Walk_access_time": 345,
        "util_DRIVE_EXP_Walk_egress_ime": 346,
        "util_DRIVE_EXP_Walk_other_time": 347,
        "util_DRIVE_EXP_Fare_and_operating_cost": 348,
        "util_DRIVE_EXP_Ratio_of_drive_access_distance_to_OD_distance": 349,
        "util_DRIVE_EXP_Destination_zone_densityIndex": 350,
        "util_DRIVE_EXP_Topology": 351,
        "util_DRIVE_EXP_Person_is_less_than_10_years_old": 352,
        "util_DRIVE_HVY_Unavailable": 353,
        "util_DRIVE_HVY_Unavailable_for_zero_auto_households": 354,
        "util_DRIVE_HVY_Unavailable_for_persons_less_than_16": 355,
        "util_DRIVE_HVY_In_vehicle_time": 356,
        "util_DRIVE_HVY_In_vehicle_time_on_heavy_rail": 357,
        "util_DRIVE_HVY_Short_iwait_time": 358,
        "util_DRIVE_HVY_Long_iwait_time": 359,
        "util_DRIVE_HVY_transfer_wait_time": 360,
        "util_DRIVE_HVY_number_of_transfers": 361,
        "util_DRIVE_HVY_Drive_time": 362,
        "util_DRIVE_HVY_Walk_access_time": 363,
        "util_DRIVE_HVY_Walk_egress_time": 364,
        "util_DRIVE_HVY_Walk_other_time": 365,
        "util_DRIVE_HVY_Fare_and_operating_cost": 366,
        "util_DRIVE_HVY_Ratio_of_drive_access_distance_to_OD_distance": 367,
        "util_DRIVE_HVY_Destination_zone_densityIndex": 368,
        "util_DRIVE_HVY_Topology": 369,
        "util_DRIVE_HVY_Person_is_less_than_10_years_old": 370,
        "util_DRIVE_COM_Unavailable": 371,
        "util_DRIVE_COM_Unavailable_for_zero_auto_households": 372,
        "util_DRIVE_COM_Unavailable_for_persons_less_than_16": 373,
        "util_DRIVE_COM_In_vehicle_time": 374,
        "util_DRIVE_COM_In_vehicle_time_on_commuter_rail": 375,
        "util_DRIVE_COM_Short_iwait_time": 376,
        "util_DRIVE_COM_Long_iwait_time": 377,
        "util_DRIVE_COM_transfer_wait_time": 378,
        "util_DRIVE_COM_number_of_transfers": 379,
        "util_DRIVE_COM_Drive_time": 380,
        "util_DRIVE_COM_Walk_access_time": 381,
        "util_DRIVE_COM_Walk_egress_time": 382,
        "util_DRIVE_COM_Walk_other_time": 383,
        "util_DRIVE_COM_Fare_and_operating_cost": 384,
        "util_DRIVE_COM_Ratio_of_drive_access_distance_to_OD_distance": 385,
        "util_DRIVE_COM_Destination_zone_densityIndex": 386,
        "util_DRIVE_COM_Topology": 387,
        "util_DRIVE_COM_Person_is_less_than_10_years_old": 388,
        "util_Taxi_In_vehicle_time": 389,
        "util_Taxi_Wait_time": 390,
        "util_Taxi_Tolls": 391,
        "util_Taxi_Bridge_toll": 392,
        "util_Taxi_Fare": 393,
        "util_TNC_Single_In_vehicle_time": 394,
        "util_TNC_Single_Wait_time": {"*": 395, "OthMaint": 393, "WorkBased": 398},
        "util_TNC_Single_Tolls": {"*": 396, "OthMaint": 394, "WorkBased": 399},
        "util_TNC_Single_Bridge_toll": {"*": 397, "OthMaint": 395, "WorkBased": 400},
        "util_TNC_Single_Cost": {"*": 398, "OthMaint": 396, "WorkBased": 401},
        "util_TNC_Shared_In_vehicle_time": {"*": 399, "OthMaint": 397, "WorkBased": 402},
        "util_TNC_Shared_Wait_time": {"*": 400, "OthMaint": 398, "WorkBased": 403},
        "util_TNC_Shared_Tolls": {"*": 401, "OthMaint": 399, "WorkBased": 404},
        "util_TNC_Shared_Bridge_toll": {"*": 402, "OthMaint": 400, "WorkBased": 405},
        "util_TNC_Shared_Cost": {"*": 403, "OthMaint": 401, "WorkBased": 406},
        "util_Walk_ASC_Zero_auto": {"*": 404, "OthMaint": 402, "WorkBased": 407},
        "util_Walk_ASC_Auto_deficient": {"*": 405, "OthMaint": 403, "WorkBased": 408},
        "util_Walk_ASC_Auto_sufficient": {"*": 406, "OthMaint": 404, "WorkBased": 411},
        "util_Bike_ASC_Zero_auto": {"*": 407, "OthMaint": 405, "WorkBased": 410},
        "util_Bike_ASC_Auto_deficient": {"*": 408, "OthMaint": 406, "WorkBased": None},
        "util_Bike_ASC_Auto_sufficient": {"*": 409, "OthMaint": 407, "WorkBased": 412},
        "util_Shared_ride_2_ASC_Zero_auto": {"*": 410, "OthMaint": 408, "WorkBased": 413},
        "util_Shared_ride_2_ASC_Auto_deficient": {"*": 411, "OthMaint": 409, "WorkBased": 414},
        "util_Shared_ride_2_ASC_Auto_sufficient": {"*": 412, "OthMaint": 410, "WorkBased": 415},
        "util_Shared_ride_3p_Zero_auto": {"*": 413, "OthMaint": 411, "WorkBased": 416},
        "util_Shared_ride_3p_Auto_deficient": {"*": 414, "OthMaint": 412, "WorkBased": 417},
        "util_Shared_ride_3p_Auto_sufficient": {"*": 415, "OthMaint": 413, "WorkBased": 418},
        "util_Walk_to_Transit_Zero_auto": {"*": 416, "OthMaint": 414, "WorkBased": 419},
        "util_Walk_to_Transit_Auto_deficient": {"*": 417, "OthMaint": 415, "WorkBased": 420},
        "util_Walk_to_Transit_Auto_sufficient": {"*": 418, "OthMaint": 416, "WorkBased": 421},
        "util_Drive_to_Transit_Zero_auto": {"*": 419, "OthMaint": 417, "WorkBased": 422},
        "util_Drive_to_Transit_Auto_deficient": {"*": 420, "OthMaint": 418, "WorkBased": 423},
        "util_Drive_to_Transit_Auto_sufficient": {"*": 421, "OthMaint": 419, "WorkBased": 424},
        "util_Taxi_Zero_auto": {"*": 422, "OthMaint": 420, "WorkBased": 425},
        "util_Taxi_Auto_deficient": {"*": 423, "OthMaint": 421, "WorkBased": 426},
        "util_Taxi_Auto_sufficient": {"*": 424, "OthMaint": 422, "WorkBased": 427},
        "util_TNC_Single_Zero_auto": {"*": 425, "OthMaint": 423, "WorkBased": 428},
        "util_TNC_Single_Auto_deficient": {"*": 426, "OthMaint": 424, "WorkBased": 429},
        "util_TNC_Single_Auto_sufficient": {"*": 427, "OthMaint": 425, "WorkBased": 430},
        "util_TNC_Shared_Zero_auto": {"*": 428, "OthMaint": 426, "WorkBased": 431},
        "util_TNC_Shared_Auto_deficient": {"*": 429, "OthMaint": 427, "WorkBased": 432},
        "util_TNC_Shared_Auto_sufficient": {"*": 430, "OthMaint": 428, "WorkBased": 433},
        "util_Joint_Walk_ASC_Zero_auto": {"*": 431, "OthMaint": 429, "WorkBased": 434},
        "util_Joint_Walk_ASC_Auto_deficient": {"*": 432, "OthMaint": 430, "WorkBased": 435},
        "util_Joint_Walk_ASC_Auto_sufficient": {"*": 433, "OthMaint": 431, "WorkBased": 436},
        "util_Joint_Bike_ASC_Zero_auto": {"*": 434, "OthMaint": 432, "WorkBased": 437},
        "util_Joint_Bike_ASC_Auto_deficient": {"*": 435, "OthMaint": 433, "WorkBased": 438},
        "util_Joint_Bike_ASC_Auto_sufficient": {"*": 436, "OthMaint": 434, "WorkBased": 439},
        "util_Joint_Shared_ride_2_ASC_Zero_auto": {"*": 437, "OthMaint": 435, "WorkBased": 440},
        "util_Joint_Shared_ride_2_ASC_Auto_deficient": {"*": 438, "OthMaint": 436, "WorkBased": 441},
        "util_Joint_Shared_ride_2_ASC_Auto_sufficient": {"*": 439, "OthMaint": 437, "WorkBased": 442},
        "util_Joint_Shared_ride_3p_Zero_auto": {"*": 440, "OthMaint": 438, "WorkBased": 443},
        "util_Joint_Shared_ride_3p_Auto_deficient": {"*": 441, "OthMaint": 439, "WorkBased": 444},
        "util_Joint_Shared_ride_3p_Auto_sufficient": {"*": 442, "OthMaint": 440, "WorkBased": 445},
        "util_Joint_Walk_to_Transit_Zero_auto": {"*": 443, "OthMaint": 441, "WorkBased": 446},
        "util_Joint_Walk_to_Transit_Auto_deficient": {"*": 444, "OthMaint": 442, "WorkBased": 447},
        "util_Joint_Walk_to_Transit_Auto_sufficient": {"*": 445, "OthMaint": 443, "WorkBased": 448},
        "util_Joint_Drive_to_Transit_Zero_auto": {"*": 446, "OthMaint": 444, "WorkBased": 449},
        "util_Joint_Drive_to_Transit_Auto_deficient": {"*": 447, "OthMaint": 445, "WorkBased": 450},
        "util_Joint_Drive_to_Transit_Auto_sufficient": {"*": 448, "OthMaint": 446, "WorkBased": 451},
        "util_Joint_Taxi_Zero_auto": {"*": 449, "OthMaint": 447, "WorkBased": 452},
        "util_Joint_Taxi_Auto_deficient": {"*": 450, "OthMaint": 448, "WorkBased": 453},
        "util_Joint_Taxi_Auto_sufficient": {"*": 451, "OthMaint": 449, "WorkBased": 454},
        "util_Joint_TNC_Single_Zero_auto": {"*": 452, "OthMaint": 450, "WorkBased": 455},
        "util_Joint_TNC_Single_Auto_deficient": {"*": 453, "OthMaint": 451, "WorkBased": 456},
        "util_Joint_TNC_Single_Auto_sufficient": {"*": 454, "OthMaint": 452, "WorkBased": 457},
        "util_Joint_TNC_Shared_Zero_auto": {"*": 455, "OthMaint": 453, "WorkBased": 458},
        "util_Joint_TNC_Shared_Auto_deficient": {"*": 456, "OthMaint": 454, "WorkBased": 459},
        "util_Joint_TNC_Shared_Auto_sufficient": {"*": 457, "OthMaint": 455, "WorkBased": 460},
        # Transit ASCs: row numbers differ on OthMaint (-2) and WorkBased (+3)
        "util_Local_bus_ASC": {"*": 458, "OthMaint": 456, "WorkBased": 461},
        "util_Walk_to_Light_Rail_ASC": {"*": 459, "OthMaint": 457, "WorkBased": 462},
        "util_Drive_to_Light_Rail_ASC": {"*": 460, "OthMaint": 458, "WorkBased": 463},
        "util_Walk_to_Ferry_ASC": {"*": 461, "OthMaint": 459, "WorkBased": 464},
        "util_Drive_to_Ferry_ASC": {"*": 462, "OthMaint": 460, "WorkBased": 465},
        "util_Express_Bus_ASC": {"*": 463, "OthMaint": 461, "WorkBased": 466},
        "util_Heavy_Rail_ASC": {"*": 464, "OthMaint": 462, "WorkBased": 467},
        "util_Commuter_Rail": {"*": 465, "OthMaint": 463, "WorkBased": 468},
        "util_Walk_to_Transit_dest_CBD": {"*": 466, "OthMaint": 464, "WorkBased": 469},
        "util_Drive_to_Transit_dest_CBD": {"*": 467, "OthMaint": 465, "WorkBased": 470},
        "util_Walk_to_Transit_dest_SF": {"Work": 468, "University": 468, "School": 468, "Escort": 468, "Shopping": 468, "EatOut": 468, "OthMaint": 466, "Social": 468, "OthDiscr": 468, "WorkBased": 471},
        "util_Drive_to_Transit_dest_SF": {"Work": 469, "University": 469, "School": 469, "Escort": 469, "Shopping": 469, "EatOut": 469, "OthMaint": 467, "Social": 469, "OthDiscr": 469, "WorkBased": 472},
        "util_Walk_to_Transit_within_SF": {"Work": 470, "University": 470, "School": 470, "Escort": 470, "Shopping": 470, "EatOut": 470, "OthMaint": 468, "Social": 470, "OthDiscr": 470, "WorkBased": 473},
        "util_Drive_to_Transit_within_SF": {"Work": 471, "University": 471, "School": 471, "Escort": 471, "Shopping": 471, "EatOut": 471, "OthMaint": 469, "Social": 471, "OthDiscr": 471, "WorkBased": 474},
        "util_Walk_to_Transit_orig_SF": {"Work": 472, "University": 472, "School": 472, "Escort": 472, "Shopping": 472, "EatOut": 472, "OthMaint": 470, "Social": 472, "OthDiscr": 472, "WorkBased": 475},
        "util_Drive_to_Transit_orig_SF": {"Work": 473, "University": 473, "School": 473, "Escort": 473, "Shopping": 473, "EatOut": 473, "OthMaint": 471, "Social": 473, "OthDiscr": 473, "WorkBased": 476},
        "util_transit_hesitance_local_bus": {"Work": 477, "University": 477, "School": 477, "Escort": 478, "Shopping": 477, "EatOut": 477, "OthMaint": 475, "Social": 477, "OthDiscr": 477, "WorkBased": 481},
        "util_transit_hesitance_walk_lrt": {"Work": 478, "University": 478, "School": 478, "Escort": 479, "Shopping": 478, "EatOut": 478, "OthMaint": 476, "Social": 478, "OthDiscr": 478, "WorkBased": 482},
        "util_transit_hesitance_drive_lrt": {"Work": 479, "University": 479, "School": 479, "Escort": 480, "Shopping": 479, "EatOut": 479, "OthMaint": 477, "Social": 479, "OthDiscr": 479, "WorkBased": 483},
        "util_transit_hesitance_walk_ferry": {"Work": 480, "University": 480, "School": 480, "Escort": 481, "Shopping": 480, "EatOut": 480, "OthMaint": 478, "Social": 480, "OthDiscr": 480, "WorkBased": 484},
        "util_transit_hesitance_drive_ferry": {"Work": 481, "University": 481, "School": 481, "Escort": 482, "Shopping": 481, "EatOut": 481, "OthMaint": 479, "Social": 481, "OthDiscr": 481, "WorkBased": 485},
        "util_transit_hesitance_express_bus": {"Work": 482, "University": 482, "School": 482, "Escort": 483, "Shopping": 482, "EatOut": 482, "OthMaint": 480, "Social": 482, "OthDiscr": 482, "WorkBased": 486},
        "util_transit_hesitance_heavy_rail": {"Work": 483, "University": 483, "School": 483, "Escort": 484, "Shopping": 483, "EatOut": 483, "OthMaint": 481, "Social": 483, "OthDiscr": 483, "WorkBased": 487},
        "util_transit_hesitance_commuter_rail": {"Work": 484, "University": 484, "School": 484, "Escort": 485, "Shopping": 484, "EatOut": 484, "OthMaint": 482, "Social": 484, "OthDiscr": 484, "WorkBased": 488},
        "util_rail_hesitance_heavy_rail": {"Work": 485, "University": 485, "School": 485, "Escort": 486, "Shopping": 485, "EatOut": 485, "OthMaint": 483, "Social": 485, "OthDiscr": 485, "WorkBased": 489},
        "util_rail_hesitance_commuter_rail": {"Work": 486, "University": 486, "School": 486, "Escort": 487, "Shopping": 486, "EatOut": 486, "OthMaint": 484, "Social": 486, "OthDiscr": 486, "WorkBased": 490},
        "util_Drive_to_Transit_distance_penalty": {"Work": 474, "University": 474, "School": 474, "Escort": None, "Shopping": 474, "EatOut": 474, "OthMaint": 472, "Social": 474, "OthDiscr": 474, "WorkBased": 477},
        "util_Walk_not_available_for_long_distances": {"Work": 475, "University": 475, "School": 475, "Escort": 476, "Shopping": 475, "EatOut": 475, "OthMaint": 473, "Social": 475, "OthDiscr": 475, "WorkBased": 478},
        "util_Bike_not_available_for_long_distances": {"Work": 476, "University": 476, "School": 476, "Escort": 477, "Shopping": 476, "EatOut": 476, "OthMaint": 474, "Social": 476, "OthDiscr": 476, "WorkBased": 479},
        "util_TNC_Single_adjustment": {"Work": 487, "University": 487, "School": 487, "Escort": 488, "Shopping": 487, "EatOut": 487, "OthMaint": 485, "Social": 487, "OthDiscr": 487, "WorkBased": 491},
        "util_TNC_Shared_adjustment": {"Work": 488, "University": 488, "School": 488, "Escort": 489, "Shopping": 488, "EatOut": 488, "OthMaint": 486, "Social": 488, "OthDiscr": 488, "WorkBased": 492},
        "util_PBA50_bike_infra_constant": {"Work": 489, "University": 489, "School": 489, "Escort": 490, "Shopping": 489, "EatOut": 489, "OthMaint": 487, "Social": 489, "OthDiscr": 489, "WorkBased": 493},
    },


    "Trip Mode Choice": {
        # WorkBased has no generic DA unavailability row — relies on specific rows instead
        "util_DRIVEALONEFREE_Unavailable": {"Work": 170, "WorkBased": None, "*": 173},
        "util_DRIVEALONEFREE_Unavailable_for_zero_auto_households": 171,
        "util_DRIVEALONEFREE_Unavailable_for_persons_less_than_16": 172,
        "util_DRIVEALONEFREE_Unavailable_for_joint_tours": 173,
        # subtour==1 filter: only fires on WorkBased; other sheets effectively 0
        "util_DRIVEALONEFREE_Unavailable_if_didn't_drive_to_work": {"WorkBased": 176, "*": None},
        "util_DRIVEALONEFREE_In_vehicle_time": 175,
        "util_DRIVEALONEFREE_Terminal_time": 176,
        "util_DRIVEALONEFREE_Operating_cost": 177,
        "util_DRIVEALONEFREE_Parking_cost": 178,
        "util_DRIVEALONEFREE_Bridge_toll": 179,
        "util_DRIVEALONEFREE_Person_is_between_16_and_19_years_old": 180,
        "util_DRIVEALONEPAY_Unavailable": 181,
        "util_DRIVEALONEPAY_Unavailable_for_zero_auto_households": 182,
        "util_DRIVEALONEPAY_Unavailable_for_persons_less_than_16": 183,
        "util_DRIVEALONEPAY_Unavailable_for_joint_tours": 184,
        "util_DRIVEALONEPAY_Unavailable_if_didn't_drive_to_work": {"WorkBased": 187, "*": None},
        "util_DRIVEALONEPAY_In_vehicle_time": 186,
        "util_DRIVEALONEPAY_Terminal_time": 187,
        "util_DRIVEALONEPAY_Operating_cost": 188,
        "util_DRIVEALONEPAY_Parking_cost": 189,
        "util_DRIVEALONEPAY_Bridge_toll": 190,
        "util_DRIVEALONEPAY_Value_toll": 191,
        "util_DRIVEALONEPAY_Person_is_between_16_and_19_years_old": 192,
        "util_SHARED2FREE_Unavailable": 193,
        "util_SHARED2FREE_Unavailable_based_on_party_size": 194,
        "util_SHARED2FREE_In_vehicle_time": 195,
        "util_SHARED2FREE_Terminal_time": 196,
        "util_SHARED2FREE_Operating_cost": 197,
        "util_SHARED2FREE_Parking_cost": 198,
        "util_SHARED2FREE_Bridge_toll": 199,
        "util_SHARED2FREE_One_person_household": 200,
        "util_SHARED2FREE_Two_person_household": 201,
        "util_SHARED2FREE_Person_is_16_years_old_or_older": 202,
        "util_SHARED2PAY_Unavailable": 203,
        "util_SHARED2PAY_Unavailable_based_on_party_size": 204,
        "util_SHARED2PAY_In_vehicle_time": 205,
        "util_SHARED2PAY_Terminal_time": 206,
        "util_SHARED2PAY_Operating_cost": 207,
        "util_SHARED2PAY_Parking_cost": 208,
        "util_SHARED2PAY_Bridge_toll": 209,
        "util_SHARED2PAY_Value_toll": 210,
        "util_SHARED2PAY_One_person_household": 211,
        "util_SHARED2PAY_Two_person_household": 212,
        "util_SHARED2PAY_Person_is_16_years_old_or_older": 213,
        "util_SHARED3FREE_Unavailable": 214,
        "util_SHARED3FREE_In_vehicle_time": 215,
        "util_SHARED3FREE_Terminal_time": 216,
        "util_SHARED3FREE_Operating_cost": 217,
        "util_SHARED3FREE_Parking_cost": 218,
        "util_SHARED3FREE_Bridge_toll": 219,
        "util_SHARED3FREE_One_person_household": 220,
        "util_SHARED3FREE_Two_person_household": 221,
        "util_SHARED3FREE_Person_is_16_years_old_or_older": 222,
        "util_SHARED3PAY_Unavailable": 223,
        "util_SHARED3PAY_In_vehicle_time": 224,
        "util_SHARED3PAY_Terminal_time": 225,
        "util_SHARED3PAY_Operating_cost": 226,
        "util_SHARED3PAY_Parking_cost": 227,
        "util_SHARED3PAY_Bridge_toll": 228,
        "util_SHARED3PAY_Value_toll": 229,
        "util_SHARED3PAY_One_person_household": 230,
        "util_SHARED3PAY_Two_person_household": 231,
        "util_SHARED3PAY_Person_is_16_years_old_or_older": 232,
        # Row numbers differ across sheets; OthDiscr/WorkBased say "2 miles", others "1 mile"
        "util_WALK_Time_up_to_2_miles": {"Work": 233, "WorkBased": 235, "*": 236},
        "util_WALK_Time_beyond_2_of_a_miles": {"Work": 234, "WorkBased": 236, "*": 237},
        "util_WALK_Destination_zone_densityIndex": 235,
        "util_WALK_Topology": 236,
        "util_BIKE_Unavailable_if_didn't_bike_to_work": {"WorkBased": 239, "*": None},
        "util_BIKE_Time_up_to_6_miles": 238,
        "util_BIKE_Time_beyond_6_of_a_miles": 239,
        "util_BIKE_Destination_zone_densityIndex": 240,
        "util_BIKE_Topology": 241,
        "util_WALK_LOC_Unavailable": 242,
        "util_WALK_LOC_In_vehicle_time": 243,
        "util_WALK_LOC_Short_iwait_time": 244,
        "util_WALK_LOC_Long_iwait_time": 245,
        "util_WALK_LOC_transfer_wait_time": 246,
        "util_WALK_LOC_number_of_transfers": 247,
        "util_WALK_LOC_Walk_access_time": 248,
        "util_WALK_LOC_Walk_egress_time": 249,
        "util_WALK_LOC_Walk_other_time": 250,
        "util_WALK_LOC_Fare": 251,
        "util_WALK_LOC_Destination_zone_densityIndex": 252,
        "util_WALK_LOC_Topology": 253,
        "util_WALK_LOC_Person_is_less_than_10_years_old": 254,
        "util_WALK_LRF_Unavailable": 255,
        "util_WALK_LRF_In_vehicle_time": 256,
        "util_WALK_LRF_In_vehicle_time_on_Light_Rail": 257,
        "util_WALK_LRF_In_vehicle_time_on_Ferry": 258,
        "util_WALK_LRF_Short_iwait_time": 259,
        "util_WALK_LRF_Long_iwait_time": 260,
        "util_WALK_LRF_transfer_wait_time": 261,
        "util_WALK_LRF_number_of_transfers": 262,
        "util_WALK_LRF_Walk_access_time": 263,
        "util_WALK_LRF_Walk_egress_time": 264,
        "util_WALK_LRF_Walk_other_time": 265,
        "util_WALK_LRF_Fare": 266,
        "util_WALK_LRF_Destination_zone_densityIndex": 267,
        "util_WALK_LRF_Topology": 268,
        "util_WALK_LRF_Person_is_less_than_10_years_old": 269,
        "util_WALK_EXP_Unavailable": 270,
        "util_WALK_EXP_In_vehicle_time": 271,
        "util_WALK_EXP_In_vehicle_time_on_Express_bus": 272,
        "util_WALK_EXP_Short_iwait_time": 273,
        "util_WALK_EXP_Long_iwait_time": 274,
        "util_WALK_EXP_transfer_wait_time": 275,
        "util_WALK_EXP_number_of_transfers": 276,
        "util_WALK_EXP_Walk_access_time": 277,
        "util_WALK_EXP_Walk_egress_time": 278,
        "util_WALK_EXP_Walk_other_time": 279,
        "util_WALK_EXP_Fare": 280,
        "util_WALK_EXP_Destination_zone_densityIndex": 281,
        "util_WALK_EXP_Topology": 282,
        "util_WALK_EXP_Person_is_less_than_10_years_old": 283,
        "util_WALK_HVY_Unavailable": 284,
        "util_WALK_HVY_In_vehicle_time": 285,
        "util_WALK_HVY_In_vehicle_time_on_heavy_rail": 286,
        "util_WALK_HVY_Short_iwait_time": 287,
        "util_WALK_HVY_Long_iwait_time": 288,
        "util_WALK_HVY_transfer_wait_time": 289,
        "util_WALK_HVY_number_of_transfers": 290,
        "util_WALK_HVY_Walk_access_time": 291,
        "util_WALK_HVY_Walk_egress_time": 292,
        "util_WALK_HVY_Walk_other_time": 293,
        "util_WALK_HVY_Fare": 294,
        "util_WALK_HVY_Destination_zone_densityIndex": 295,
        "util_WALK_HVY_Topology": 296,
        "util_WALK_HVY_Person_is_less_than_10_years_old": 297,
        "util_WALK_COM_Unavailable": 298,
        "util_WALK_COM_In_vehicle_time": 299,
        "util_WALK_COM_In_vehicle_time_on_commuter_rail": 300,
        "util_WALK_COM_Short_iwait_time": 301,
        "util_WALK_COM_Long_iwait_time": 302,
        "util_WALK_COM_transfer_wait_time": 303,
        "util_WALK_COM_number_of_transfers": 304,
        "util_WALK_COM_Walk_access_time": 305,
        "util_WALK_COM_Walk_egress_time": 306,
        "util_WALK_COM_Walk_other_time": 307,
        "util_WALK_COM_Fare": 308,
        "util_WALK_COM_Destination_zone_densityIndex": 309,
        "util_WALK_COM_Topology": 310,
        "util_WALK_COM_Person_is_less_than_10_years_old": 311,
        "util_DRIVE_LOC_Unavailable_for_zero_auto_households": 313,
        "util_DRIVE_LOC_Unavailable_for_persons_less_than_16": 314,
        "util_DRIVE_LOC_Destination_zone_densityIndex": 325,
        "util_DRIVE_LOC_Topology": 326,
        "util_DRIVE_LOC_Person_is_less_than_10_years_old": 327,
        "util_DRIVE_LOC_outbound_Unavailable": 312,
        "util_DRIVE_LOC_outbound_In_vehicle_time": 315,
        "util_DRIVE_LOC_outbound_Short_iwait_time": 316,
        "util_DRIVE_LOC_outbound_Long_iwait_time": 317,
        "util_DRIVE_LOC_outbound_transfer_wait_time": 318,
        "util_DRIVE_LOC_outbound_number_of_transfers": 319,
        "util_DRIVE_LOC_outbound_Drive_time": 320,
        "util_DRIVE_LOC_outbound_Walk_egress_time": 321,
        "util_DRIVE_LOC_outbound_Walk_other_time": 322,
        "util_DRIVE_LOC_outbound_Fare_and_operating_cost": 323,
        "util_DRIVE_LOC_outbound_Ratio_of_drive_access_distance_to_OD_distance": 324,
        "util_DRIVE_LOC_inbound_Unavailable": 328,
        "util_DRIVE_LOC_inbound_In_vehicle_time": 331,
        "util_DRIVE_LOC_inbound_Short_iwait_time": 332,
        "util_DRIVE_LOC_inbound_Long_iwait_time": 333,
        "util_DRIVE_LOC_inbound_transfer_wait_time": 334,
        "util_DRIVE_LOC_inbound_number_of_transfers": 335,
        "util_DRIVE_LOC_inbound_Drive_time": 336,
        "util_DRIVE_LOC_inbound_Walk_access_time": 337,
        "util_DRIVE_LOC_inbound_Walk_other_time": 338,
        "util_DRIVE_LOC_inbound_Fare_and_operating_cost": 339,
        "util_DRIVE_LOC_inbound_Ratio_of_drive_access_distance_to_OD_distance": 340,
        "util_DRIVE_LRF_Unavailable_for_zero_auto_households": 345,
        "util_DRIVE_LRF_Unavailable_for_persons_less_than_16": 346,
        "util_DRIVE_LRF_Destination_zone_densityIndex": 359,
        "util_DRIVE_LRF_Topology": 360,
        "util_DRIVE_LRF_Person_is_less_than_10_years_old": 361,
        "util_DRIVE_LRF_outbound_Unavailable": 344,
        "util_DRIVE_LRF_outbound_In_vehicle_time": 347,
        "util_DRIVE_LRF_outbound_In_vehicle_time_on_LR": 348,
        "util_DRIVE_LRF_outbound_In_vehicle_time_on_Ferry": 349,
        "util_DRIVE_LRF_outbound_Short_iwait_time": 350,
        "util_DRIVE_LRF_outbound_Long_iwait_time": 351,
        "util_DRIVE_LRF_outbound_transfer_wait_time": 352,
        "util_DRIVE_LRF_outbound_number_of_transfers": 353,
        "util_DRIVE_LRF_outbound_Drive_time": 354,
        "util_DRIVE_LRF_outbound_Walk_egress_time": 355,
        "util_DRIVE_LRF_outbound_Walk_other_time": 356,
        "util_DRIVE_LRF_outbound_Fare_and_operating_cost": 357,
        "util_DRIVE_LRF_outbound_Ratio_of_drive_access_distance_to_OD_distance": 358,
        "util_DRIVE_LRF_inbound_Unavailable": 362,
        "util_DRIVE_LRF_inbound_In_vehicle_time": 365,
        "util_DRIVE_LRF_inbound_In_vehicle_time_on_LR": 366,
        "util_DRIVE_LRF_inbound_In_vehicle_time_on_Ferry": 367,
        "util_DRIVE_LRF_inbound_Short_iwait_time": 368,
        "util_DRIVE_LRF_inbound_Long_iwait_time": 369,
        "util_DRIVE_LRF_inbound_transfer_wait_time": 370,
        "util_DRIVE_LRF_inbound_number_of_transfers": 371,
        "util_DRIVE_LRF_inbound_Drive_time": 372,
        "util_DRIVE_LRF_inbound_Walk_access_time": 373,
        "util_DRIVE_LRF_inbound_Walk_other_time": 374,
        "util_DRIVE_LRF_inbound_Fare_and_operating_cost": 375,
        "util_DRIVE_LRF_inbound_Ratio_of_drive_access_distance_to_OD_distance": 376,
        "util_DRIVE_EXP_Unavailable_for_zero_auto_households": 381,
        "util_DRIVE_EXP_Unavailable_for_persons_less_than_16": 382,
        "util_DRIVE_EXP_Destination_zone_densityIndex": 394,
        "util_DRIVE_EXP_Topology": 395,
        "util_DRIVE_EXP_Person_is_less_than_10_years_old": 396,
        "util_DRIVE_EXP_outbound_Unavailable": 380,
        "util_DRIVE_EXP_outbound_In_vehicle_time": 383,
        "util_DRIVE_EXP_outbound_In_vehicle_time_on_EXP": 384,
        "util_DRIVE_EXP_outbound_Short_iwait_time": 385,
        "util_DRIVE_EXP_outbound_Long_iwait_time": 386,
        "util_DRIVE_EXP_outbound_transfer_wait_time": 387,
        "util_DRIVE_EXP_outbound_number_of_transfers": 388,
        "util_DRIVE_EXP_outbound_Drive_time": 389,
        "util_DRIVE_EXP_outbound_Walk_egress_time": 390,
        "util_DRIVE_EXP_outbound_Walk_other_time": 391,
        "util_DRIVE_EXP_outbound_Fare_and_operating_cost": 392,
        "util_DRIVE_EXP_outbound_Ratio_of_drive_access_distance_to_OD_distance": 393,
        "util_DRIVE_EXP_inbound_Unavailable": 397,
        "util_DRIVE_EXP_inbound_In_vehicle_time": 400,
        "util_DRIVE_EXP_inbound_In_vehicle_time_on_EXP": 401,
        "util_DRIVE_EXP_inbound_Short_iwait_time": 402,
        "util_DRIVE_EXP_inbound_Long_iwait_time": 403,
        "util_DRIVE_EXP_inbound_transfer_wait_time": 404,
        "util_DRIVE_EXP_inbound_number_of_transfers": 405,
        "util_DRIVE_EXP_inbound_Drive_time": 406,
        "util_DRIVE_EXP_inbound_Walk_access_time": 407,
        "util_DRIVE_EXP_inbound_Walk_other_time": 408,
        "util_DRIVE_EXP_inbound_Fare_and_operating_cost": 409,
        "util_DRIVE_EXP_inbound_Ratio_of_drive_access_distance_to_OD_distance": 410,
        "util_DRIVE_HVY_Unavailable_for_zero_auto_households": 415,
        "util_DRIVE_HVY_Unavailable_for_persons_less_than_16": 416,
        "util_DRIVE_HVY_Destination_zone_densityIndex": 428,
        "util_DRIVE_HVY_Topology": 429,
        "util_DRIVE_HVY_Person_is_less_than_10_years_old": 430,
        "util_DRIVE_HVY_outbound_Unavailable": 414,
        "util_DRIVE_HVY_outbound_In_vehicle_time": 417,
        "util_DRIVE_HVY_outbound_In_vehicle_time_on_HVY": 418,
        "util_DRIVE_HVY_outbound_Short_iwait_time": 419,
        "util_DRIVE_HVY_outbound_Long_iwait_time": 420,
        "util_DRIVE_HVY_outbound_transfer_wait_time": 421,
        "util_DRIVE_HVY_outbound_number_of_transfers": 422,
        "util_DRIVE_HVY_outbound_Drive_time": 423,
        "util_DRIVE_HVY_outbound_Walk_egress_time": 424,
        "util_DRIVE_HVY_outbound_Walk_other_time": 425,
        "util_DRIVE_HVY_outbound_Fare_and_operating_cost": 426,
        "util_DRIVE_HVY_outbound_Ratio_of_drive_access_distance_to_OD_distance": 427,
        "util_DRIVE_HVY_inbound_Unavailable": 431,
        "util_DRIVE_HVY_inbound_In_vehicle_time": 434,
        "util_DRIVE_HVY_inbound_In_vehicle_time_on_HVY": 435,
        "util_DRIVE_HVY_inbound_Short_iwait_time": 436,
        "util_DRIVE_HVY_inbound_Long_iwait_time": 437,
        "util_DRIVE_HVY_inbound_transfer_wait_time": 438,
        "util_DRIVE_HVY_inbound_number_of_transfers": 439,
        "util_DRIVE_HVY_inbound_Drive_time": 440,
        "util_DRIVE_HVY_inbound_Walk_access_time": 441,
        "util_DRIVE_HVY_inbound_Walk_other_time": 442,
        "util_DRIVE_HVY_inbound_Fare_and_operating_cost": 443,
        "util_DRIVE_HVY_inbound_Ratio_of_drive_access_distance_to_OD_distance": 444,
        "util_DRIVE_COM_Unavailable_for_zero_auto_households": 449,
        "util_DRIVE_COM_Unavailable_for_persons_less_than_16": 450,
        "util_DRIVE_COM_Destination_zone_densityIndex": 462,
        "util_DRIVE_COM_Topology": 463,
        "util_DRIVE_COM_Person_is_less_than_10_years_old": 464,
        "util_DRIVE_COM_outbound_Unavailable": 448,
        "util_DRIVE_COM_outbound_In_vehicle_time": 451,
        "util_DRIVE_COM_outbound_In_vehicle_time_on_COM": 452,
        "util_DRIVE_COM_outbound_Short_iwait_time": 453,
        "util_DRIVE_COM_outbound_Long_iwait_time": 454,
        "util_DRIVE_COM_outbound_transfer_wait_time": 455,
        "util_DRIVE_COM_outbound_number_of_transfers": 456,
        "util_DRIVE_COM_outbound_Drive_time": 457,
        "util_DRIVE_COM_outbound_Walk_egress_time": 458,
        "util_DRIVE_COM_outbound_Walk_other_time": 459,
        "util_DRIVE_COM_outbound_Fare_and_operating_cost": 460,
        "util_DRIVE_COM_outbound_Ratio_of_drive_access_distance_to_OD_distance": 461,
        "util_DRIVE_COM_inbound_Unavailable": 465,
        "util_DRIVE_COM_inbound_In_vehicle_time": 468,
        "util_DRIVE_COM_inbound_In_vehicle_time_on_COM": 469,
        "util_DRIVE_COM_inbound_Short_iwait_time": 470,
        "util_DRIVE_COM_inbound_Long_iwait_time": 471,
        "util_DRIVE_COM_inbound_transfer_wait_time": 472,
        "util_DRIVE_COM_inbound_number_of_transfers": 473,
        "util_DRIVE_COM_inbound_Drive_time": 474,
        "util_DRIVE_COM_inbound_Walk_access_time": 475,
        "util_DRIVE_COM_inbound_Walk_other_time": 476,
        "util_DRIVE_COM_inbound_Fare_and_operating_cost": 477,
        "util_DRIVE_COM_inbound_Ratio_of_drive_access_distance_to_OD_distance": 478,
        "util_Taxi_In_vehicle_time": 482,
        "util_Taxi_Wait_time": 483,
        "util_Taxi_Tolls": 484,
        "util_Taxi_Bridge_toll": 485,
        "util_Taxi_Fare": 486,
        "util_TNC_Single_In_vehicle_time": 487,
        "util_TNC_Single_Wait_time": 488,
        "util_TNC_Single_Tolls": 489,
        "util_TNC_Single_Bridge_toll": 490,
        "util_TNC_Single_Cost": 491,
        "util_TNC_Shared_In_vehicle_time": 492,
        "util_TNC_Shared_Wait_time": 493,
        "util_TNC_Shared_Tolls": 494,
        "util_TNC_Shared_Bridge_toll": 495,
        "util_TNC_Shared_Cost": 496,
        "util_tour_mode_is_auto": 497,
        "util_tour_mode_is_walk": 498,
        "util_tour_mode_is_bike": 499,
        "util_tour_mode_is_walk_transit": 500,
        "util_tour_mode_is_drive_transit": 501,
        "util_tour_mode_is_ride_hail": 502,
        "util_Drive_Alone_tour_mode_ASC_shared_ride_2_df_is_indiv": 503,
        "util_Drive_Alone_tour_mode_ASC_shared_ride_3_plus": 504,
        "util_Drive_Alone_tour_mode_ASC_walk": 505,
        "util_Drive_Alone_tour_mode_ASC_ride_hail": 506,
        "util_Shared_Ride_2_tour_mode_ASC_shared_ride_2": 507,
        "util_Shared_Ride_2_tour_mode_ASC_shared_ride_3_plus": 508,
        "util_Shared_Ride_2_tour_mode_ASC_walk": 509,
        "util_Shared_Ride_2_tour_mode_ASC_ride_hail": 510,
        "util_Shared_Ride_3_tour_mode_ASC_shared_ride_2": 511,
        "util_Shared_Ride_3_tour_mode_ASC_shared_ride_3_plus": 512,
        "util_Shared_Ride_3_tour_mode_ASC_walk": 513,
        "util_Shared_Ride_3_tour_mode_ASC_ride_hail": 514,
        "util_Walk_tour_mode_ASC_ride_hail": 515,
        "util_Bike_tour_mode_ASC_walk": 516,
        "util_Bike_tour_mode_ASC_ride_hail": 517,
        "util_Walk_to_Transit_tour_mode_ASC_light_rail": 518,
        "util_Walk_to_Transit_tour_mode_ASC_ferry": 519,
        "util_Walk_to_Transit_tour_mode_ASC_express_bus": 520,
        "util_Walk_to_Transit_tour_mode_ASC_heavy_rail": 521,
        "util_Walk_to_Transit_tour_mode_ASC_commuter_rail": 522,
        "util_Walk_to_Transit_tour_mode_ASC_shared_ride_2": 523,
        "util_Walk_to_Transit_tour_mode_ASC_shared_ride_3_plus": 524,
        "util_Walk_to_Transit_tour_mode_ASC_walk": 525,
        "util_Walk_to_Transit_tour_mode_ASC_ride_hail": 526,
        "util_Drive_to_Transit_tour_mode_ASC_light_rail_skims_differ": {"Work": 527, "University": 530, "School": 530, "Escort": 530, "Shopping": 530, "EatOut": 530, "OthMaint": 530, "Social": 530, "OthDiscr": 530, "WorkBased": 529},
        "util_Drive_to_Transit_tour_mode_ASC_ferry": {"Work": 528, "WorkBased": 530, "*": 531},
        "util_Drive_to_Transit_tour_mode_ASC_express_bus": {"Work": 529, "WorkBased": 531, "*": 532},
        "util_Drive_to_Transit_tour_mode_ASC_heavy_rail": {"Work": 530, "WorkBased": 532, "*": 533},
        "util_Drive_to_Transit_tour_mode_ASC_commuter_rail": {"Work": 531, "WorkBased": 533, "*": 534},
        "util_Drive_to_Transit_tour_mode_ASC_ride_hail": {"Work": 532, "WorkBased": 534, "*": 535},
        "util_Ride_Hail_tour_mode_ASC_shared_ride_2": {"Work": 533, "WorkBased": 535, "*": 536},
        "util_Ride_Hail_tour_mode_ASC_shared_ride_3_plus": {"Work": 534, "WorkBased": 536, "*": 537},
        "util_Ride_Hail_tour_mode_ASC_walk": {"Work": 535, "WorkBased": 537, "*": 538},
        "util_Ride_Hail_tour_mode_ASC_walk_to_transit": 536,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_taxi": 537,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_single": 538,
        "util_Ride_Hail_tour_mode_ASC_ride_hail_shared": 539,
        "util_Walk_not_available_for_long_distances": {"Work": 540, "University": 543, "School": 543, "Escort": 543, "Shopping": 572, "EatOut": 572, "OthMaint": 572, "Social": 572, "OthDiscr": 572, "WorkBased": 542},
        "util_Bike_not_available_for_long_distances": {"Work": 541, "University": 544, "School": 544, "Escort": 544, "Shopping": 573, "EatOut": 573, "OthMaint": 573, "Social": 573, "OthDiscr": 573, "WorkBased": 543},
        "util_origin_density_index": {"Work": 542, "University": 545, "School": 545, "Escort": 545, "Shopping": 574, "EatOut": 574, "OthMaint": 574, "Social": 574, "OthDiscr": 574, "WorkBased": 544},
        "util_walk_express_penalty": {"Work": 543, "University": 546, "School": 546, "Escort": 546, "Shopping": 575, "EatOut": 575, "OthMaint": 575, "Social": 575, "OthDiscr": 575, "WorkBased": 545},
        "util_transit_hesitance_local_bus": {"Work": 544, "University": 547, "School": 547, "Escort": 547, "Shopping": 576, "EatOut": 576, "OthMaint": 576, "Social": 576, "OthDiscr": 576, "WorkBased": 546},
        "util_transit_hesitance_walk_to_light_rail": {"Work": 545, "University": 548, "School": 548, "Escort": 548, "Shopping": 577, "EatOut": 577, "OthMaint": 577, "Social": 577, "OthDiscr": 577, "WorkBased": 547},
        "util_transit_hesitance_drive_to_light_rail": {"Work": 546, "University": 549, "School": 549, "Escort": 549, "Shopping": 578, "EatOut": 578, "OthMaint": 578, "Social": 578, "OthDiscr": 578, "WorkBased": 548},
        "util_transit_hesitance_walk_to_ferry": {"Work": 547, "University": 550, "School": 550, "Escort": 550, "Shopping": 579, "EatOut": 579, "OthMaint": 579, "Social": 579, "OthDiscr": 579, "WorkBased": 549},
        "util_transit_hesitance_drive_to_ferry": {"Work": 548, "University": 551, "School": 551, "Escort": 551, "Shopping": 580, "EatOut": 580, "OthMaint": 580, "Social": 580, "OthDiscr": 580, "WorkBased": 550},
        "util_transit_hesitance_express_bus": {"Work": 549, "University": 552, "School": 552, "Escort": 552, "Shopping": 581, "EatOut": 581, "OthMaint": 581, "Social": 581, "OthDiscr": 581, "WorkBased": 551},
        "util_transit_hesitance_heavy_rail": {"Work": 550, "University": 553, "School": 553, "Escort": 553, "Shopping": 582, "EatOut": 582, "OthMaint": 582, "Social": 582, "OthDiscr": 582, "WorkBased": 552},
        "util_transit_hesitance_commuter_rail": {"Work": 551, "University": 554, "School": 554, "Escort": 554, "Shopping": 583, "EatOut": 583, "OthMaint": 583, "Social": 583, "OthDiscr": 583, "WorkBased": 553},
        "util_rail_hesitance_heavy_rail": {"Work": 552, "University": 555, "School": 555, "Escort": 555, "Shopping": 584, "EatOut": 584, "OthMaint": 584, "Social": 584, "OthDiscr": 584, "WorkBased": 554},
        "util_rail_hesitance_commuter_rail": {"Work": 553, "University": 556, "School": 556, "Escort": 556, "Shopping": 585, "EatOut": 585, "OthMaint": 585, "Social": 585, "OthDiscr": 585, "WorkBased": 555},
        "util_TNC_Single_adjustment": {"Work": 554, "University": 557, "School": 557, "Escort": 557, "Shopping": 586, "EatOut": 586, "OthMaint": 586, "Social": 586, "OthDiscr": 586, "WorkBased": 556},
        "util_adjust_tnc_shared": {"Work": 555, "University": 558, "School": 558, "Escort": 558, "Shopping": 587, "EatOut": 587, "OthMaint": 587, "Social": 587, "OthDiscr": 587, "WorkBased": 557},
        "util_PBA50_bike_infra_constant": {"Work": 556, "University": 559, "School": 559, "Escort": 559, "Shopping": 588, "EatOut": 588, "OthMaint": 588, "Social": 588, "OthDiscr": 588, "WorkBased": None},
        # Joint Tour ASCs — only on Shopping/EatOut/OthMaint/Social/OthDiscr (rows 543-571)
        "util_joint_auto_tour_mode_ASC_shared_ride_2": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 543, "EatOut": 543, "OthMaint": 543, "Social": 543, "OthDiscr": 543, "WorkBased": None},
        "util_joint_auto_tour_mode_ASC_shared_ride_3_": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 544, "EatOut": 544, "OthMaint": 544, "Social": 544, "OthDiscr": 544, "WorkBased": None},
        "util_joint_auto_tour_mode_ASC_walk": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 545, "EatOut": 545, "OthMaint": 545, "Social": 545, "OthDiscr": 545, "WorkBased": None},
        "util_joint_auto_tour_mode_ASC_ride_hail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 546, "EatOut": 546, "OthMaint": 546, "Social": 546, "OthDiscr": 546, "WorkBased": None},
        "util_joint_Walk_tour_mode_ASC_ride_hail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 547, "EatOut": 547, "OthMaint": 547, "Social": 547, "OthDiscr": 547, "WorkBased": None},
        "util_joint_Bike_tour_mode_ASC_walk": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 548, "EatOut": 548, "OthMaint": 548, "Social": 548, "OthDiscr": 548, "WorkBased": None},
        "util_joint_Bike_tour_mode_ASC_ride_hail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 549, "EatOut": 549, "OthMaint": 549, "Social": 549, "OthDiscr": 549, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_light_rail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 550, "EatOut": 550, "OthMaint": 550, "Social": 550, "OthDiscr": 550, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_ferry": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 551, "EatOut": 551, "OthMaint": 551, "Social": 551, "OthDiscr": 551, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_express_bus": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 552, "EatOut": 552, "OthMaint": 552, "Social": 552, "OthDiscr": 552, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_heavy_rail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 553, "EatOut": 553, "OthMaint": 553, "Social": 553, "OthDiscr": 553, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_commuter_rail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 554, "EatOut": 554, "OthMaint": 554, "Social": 554, "OthDiscr": 554, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_shared_ride_2": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 555, "EatOut": 555, "OthMaint": 555, "Social": 555, "OthDiscr": 555, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_shared_ride_3_plus": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 556, "EatOut": 556, "OthMaint": 556, "Social": 556, "OthDiscr": 556, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_walk": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 557, "EatOut": 557, "OthMaint": 557, "Social": 557, "OthDiscr": 557, "WorkBased": None},
        "util_joint_Walk_to_Transit_tour_mode_ASC_ride_hail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 558, "EatOut": 558, "OthMaint": 558, "Social": 558, "OthDiscr": 558, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_light_rail_skims_differ": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 559, "EatOut": 559, "OthMaint": 559, "Social": 559, "OthDiscr": 559, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_ferry": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 560, "EatOut": 560, "OthMaint": 560, "Social": 560, "OthDiscr": 560, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_express_bus": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 561, "EatOut": 561, "OthMaint": 561, "Social": 561, "OthDiscr": 561, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_heavy_rail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 562, "EatOut": 562, "OthMaint": 562, "Social": 562, "OthDiscr": 562, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_commuter_rail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 563, "EatOut": 563, "OthMaint": 563, "Social": 563, "OthDiscr": 563, "WorkBased": None},
        "util_joint_Drive_to_Transit_tour_mode_ASC_ride_hail": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 564, "EatOut": 564, "OthMaint": 564, "Social": 564, "OthDiscr": 564, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_shared_ride_2": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 565, "EatOut": 565, "OthMaint": 565, "Social": 565, "OthDiscr": 565, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_shared_ride_3_plus": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 566, "EatOut": 566, "OthMaint": 566, "Social": 566, "OthDiscr": 566, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_walk": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 567, "EatOut": 567, "OthMaint": 567, "Social": 567, "OthDiscr": 567, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_walk_to_transit": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 568, "EatOut": 568, "OthMaint": 568, "Social": 568, "OthDiscr": 568, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_ride_hail_taxi": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 569, "EatOut": 569, "OthMaint": 569, "Social": 569, "OthDiscr": 569, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_ride_hail_single": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 570, "EatOut": 570, "OthMaint": 570, "Social": 570, "OthDiscr": 570, "WorkBased": None},
        "util_joint_Ride_Hail_tour_mode_ASC_ride_hail_shared": {"Work": None, "University": None, "School": None, "Escort": None, "Shopping": 571, "EatOut": 571, "OthMaint": 571, "Social": 571, "OthDiscr": 571, "WorkBased": None},
    },

}

# CTRAMP token → ActivitySim coefficient crosswalk for constants tables.
# Each entry: ctramp_token → (asim_name, source).
#   source="yaml"     → asim_name is a YAML CONSTANTS key (IVT multiplier space)
#   source="template" → asim_name is a template coefficient name
# Shared entries apply to both Tour MC and Trip MC unless overridden
# per-submodel below.
_SHARED_TOKEN_MAP: dict[str, tuple[str, str]] = {
    "c_ivt":              ("coef_ivt",                        "template"),
    "c_ivt_lrt":          ("ivt_lrt_multiplier",              "yaml"),
    "c_ivt_ferry":        ("ivt_ferry_multiplier",            "yaml"),
    "c_ivt_exp":          ("ivt_exp_multiplier",              "yaml"),
    "c_ivt_hvy":          ("ivt_hvy_multiplier",              "yaml"),
    "c_ivt_com":          ("ivt_com_multiplier",              "yaml"),
    "c_cost":             ("ivt_cost_multiplier",             "yaml"),
    "c_shortiWait":       ("short_i_wait_multiplier",         "yaml"),
    "c_longiWait":        ("long_i_wait_multiplier",          "yaml"),
    "c_wacc":             ("wacc_multiplier",                 "yaml"),
    "c_wegr":             ("wegr_multiplier",                 "yaml"),
    "c_waux":             ("waux_multiplier",                 "yaml"),
    "c_dtim":             ("dtim_multiplier",                 "yaml"),
    "c_xwait":            ("xwait_multiplier",                "yaml"),
    "c_dacc_ratio":       ("dacc_ratio",                      "yaml"),
    "c_xfers_wlk":        ("xfers_wlk_multiplier",           "yaml"),
    "c_xfers_drv":        ("xfers_drv_multiplier",            "yaml"),
    "c_walkTimeShort":    ("walktimeshort_multiplier",        "yaml"),
    "c_walkTimeLong":     ("walktimelong_multiplier",         "yaml"),
    "c_bikeTimeShort":    ("biketimeshort_multiplier",        "yaml"),
    "c_bikeTimeLong":     ("biketimelong_multiplier",         "yaml"),
    "c_topology_walk":    ("topology_walk_multiplier",        "yaml"),
    "c_topology_bike":    ("topology_bike_multiplier",        "yaml"),
    "c_topology_trn":     ("topology_trn_multiplier",         "yaml"),
    "c_densityIndex":     ("density_index_multiplier",        "yaml"),
    "c_age1619_da":       ("coef_age1619_da_multiplier",      "template"),
    "c_age010_trn":       ("coef_age010_trn_multiplier",      "template"),
    "c_age16p_sr":        ("coef_age16p_sr_multiplier",       "template"),
    "c_hhsize1_sr":       ("coef_hhsize1_sr_multiplier",      "template"),
    "c_hhsize2_sr":       ("coef_hhsize2_sr_multiplier",      "template"),
}

# Per-submodel overrides / additions.  Merged on top of _SHARED_TOKEN_MAP.
_TOKEN_MAP_OVERRIDES: dict[str, dict[str, tuple[str, str]]] = {
    "Trip Mode Choice": {
        # Trip MC uses template coefficients for these (not YAML)
        "c_ivt_lrt":              ("coef_ivt_lrt_multiplier",           "template"),
        "c_ivt_ferry":            ("coef_ivt_ferry_multiplier",         "template"),
        "c_shortiWait":           ("coef_short_iwait_multiplier",       "template"),
        "c_longiWait":            ("coef_long_iwait_multiplier",        "template"),
        "c_wacc":                 ("coef_wacc_multiplier",              "template"),
        "c_wegr":                 ("coef_wegr_multiplier",              "template"),
        "c_waux":                 ("coef_waux_multiplier",              "template"),
        "c_dtim":                 ("coef_dtim_multiplier",              "template"),
        "c_xwait":                ("coef_xwait_multiplier",             "template"),
        "c_walkTimeShort":        ("coef_walktimeshort_multiplier",     "template"),
        "c_bikeTimeShort":        ("coef_biketimeshort_multiplier",     "template"),
        "c_age1619_da":           ("coef_age1619_da",                   "template"),
        "c_age010_trn":           ("coef_age010_trn",                   "template"),
        "c_age16p_sr":            ("coef_age16p_sr",                    "template"),
        "c_hhsize1_sr":           ("coef_hhsize1_sr",                   "template"),
        "c_hhsize2_sr":           ("coef_hhsize2_sr",                   "template"),
        "c_dacc_ratio":           ("dacc_ratio_multiplier",             "yaml"),
        # Trip MC only tokens
        "c_originDensityIndex":   ("origin_density_index_multiplier",   "yaml"),
        "c_originDensityIndexMax": ("origin_density_index_max",         "yaml"),
    },
    "Tour Mode Choice": {
        # Tour MC uses template coefficients for topology (not YAML)
        "c_topology_walk":        ("coef_topology_walk_multiplier",     "template"),
        "c_topology_bike":        ("coef_topology_bike_multiplier",     "template"),
        "c_topology_trn":         ("coef_topology_trn_multiplier",      "template"),
        # Tour MC only tokens (WorkBased sheet only)
        "c_densityIndexOrigin":   ("origin_density_index_multiplier",   "yaml"),
        "c_drvtrn_distpen_0":     ("drvtrn_distpen_0_multiplier",       "yaml"),
        "c_drvtrn_distpen_max":   ("drvtrn_distpen_max",                "yaml"),
    },
}


def get_token_map(submodel_name: str) -> dict[str, tuple[str, str]]:
    """Return the merged CTRAMP-token → (asim_name, source) map for a submodel."""
    merged = dict(_SHARED_TOKEN_MAP)
    merged.update(_TOKEN_MAP_OVERRIDES.get(submodel_name, {}))
    return merged


# Explicit row-number offsets for UEC sheets where rows don't align with the
# reference sheet (the first sheet listed in ctramp_sheets).  The crosswalk in
# MAPPINGS uses row numbers from the reference sheet.  For other sheets:
#   actual_row = crosswalk_row + offset  (unless overridden in _exceptions)
#
# Format: {submodel: {sheet_name: {"_offset": int, "_exceptions": {ref_row: actual_row_or_None}}}}
#
# _exceptions entries:
#   ref_row: actual_row  — use this specific row instead of ref_row + offset
#   ref_row: None        — row doesn't exist in this sheet (skip)


# Effective coefficient overrides for CTRAMP UEC rows where the displayed
# coefficient (from the alt column) is a multiplier on a property/token that
# resolves to a different numeric value.  The table will show the resolved
# effective value instead of the raw UEC coefficient.
# {submodel: {row_no: effective_value}}
COEFF_OVERRIDES: dict[str, dict[int, float]] = {
    # Property-resolved coefficients are now handled automatically by
    # resolve_ctramp_formula() in compare_coefficients.py.
    # Only add manual overrides here for cases that can't be auto-resolved.
    "CDAP": {
        # Rows 77-78: CTRAMP applies -1.758 on M alt (penalty to workers who WFH).
        # ASim uses +0.1813 on H alt (bonus). These are NOT equivalent:
        #   -1.758 on M = +1.758 on H AND +1.758 on N (relative)
        #   +0.1813 on H only affects H vs {M,N}
        # Leave raw values — shows as diff intentionally.
    },
}


# Alt-level mapping for submodels where CTRAMP has more alts than ASim.
# {submodel: {ctramp_alt: asim_alt}}
# When present, the comparison shows one column pair per CTRAMP alt,
# with each paired to its corresponding ASim alt.
ALT_MAPPINGS: dict[str, dict[str, str]] = {
    # Now that ASim has the full 11-alt spec, AO is a 1:1 match — no alt mapping needed.
}


# Explanatory notes for rows that appear on only one side or as many-to-one.
# {submodel: {label_or_"row_N": note_text}}
NOTES: dict[str, dict[str, str]] = {

    "Workplace Location": {
        # Many-to-one: CTRAMP has per-income-segment rows, ASim uses size_terms table
        "util_size_variable": (
            "CTRAMP rows 24-27 are per-income-segment size variables (low/med/high/veryhigh) "
            "with identical coeff=1. ActivitySim handles segmentation via "
            "destination_choice_size_terms.csv, so one spec row suffices."
        ),
        "util_no_attractions": (
            "CTRAMP rows 28-31 are per-income-segment no-attractions penalties "
            "(coeff=-999). ActivitySim applies the same penalty across segments "
            "via a single spec row; segmentation is in the size terms table."
        ),
        # ASim-only: no CTRAMP equivalent
        "local_dist": (
            "Intermediate variable that caches skims['DIST'] for reuse by "
            "downstream distance-band expressions. Not a utility term."
        ),
        "local_home_county": (
            "Intermediate variable that looks up the origin county_id for "
            "county-to-county constant expressions. Not a utility term."
        ),
        "util_utility_adjustment": (
            "ActivitySim shadow pricing mechanism — iteratively adjusts zone "
            "attractiveness to match aggregate targets. CTRAMP uses a different "
            "shadow pricing implementation outside the UEC."
        ),
    },

    "Auto Ownership": {},

    "School Location": {
        "local_dist": (
            "Intermediate variable that caches skims['DIST'] for reuse by "
            "downstream distance-band expressions. Not a utility term."
        ),
        "util_utility_adjustment": (
            "ActivitySim shadow pricing mechanism — iteratively adjusts zone "
            "attractiveness to match aggregate targets. CTRAMP uses a different "
            "shadow pricing implementation outside the UEC."
        ),
    },

    "CDAP": {
        "row_79": (
            "CTRAMP rows 79-82: No usual work/school location interactions. "
            "These tokens (noUsualWorkLocation, noUsualSchoolLocation) always "
            "return 0 in the MTC implementation — effectively dead code. "
            "No ActivitySim equivalent needed."
        ),
        "row_83": (
            "CTRAMP rows 83-84: Mandatory pattern unavailable for retired/non-working "
            "adults (-999). In ActivitySim, ptype-based unavailability "
            "is handled by coef_UNAVAILABLE in the ASC rows (rows 32-33)."
        ),
    },
    "Work From Home": {},
}

# Mapping notes for the constants crosswalk, keyed by submodel name.
# Each note is (asim_name_or_token, description).  Rendered as a collapsible
# "Mapping Notes" section below the constants table.
CONSTANTS_NOTES: dict[str, list[tuple[str, str]]] = {
    "CDAP": [
        ("WFH worker M-penalty & H-bonus (rows 77-78)",
         "CTRAMP rows 77-78 apply both −1.758 on M and +0.1813 on H in a single row. "
         "ASim mirrors this with coef_wfh_worker_m_penalty (−1.758) on M and "
         "coef_wfh_worker_h_bonus (+0.1813) on H in a single spec row with "
         "coefficients on both alt columns."),
    ],
    "Work From Home": [
        ("Calibration constant (row 24)",
         "CTRAMP: UEC coefficient column is 1.0 (multiplier) × property token "
         "%CDAP.WFH.CalibrationConstant% = −0.340. Effective value = 1.0 × −0.340 = −0.340. "
         "ActivitySim: −0.340 directly in coefficients file. Values are identical."),
        ("EN7 Superdistrict boosts (rows 25-58)",
         "Both CTRAMP and ASim have 34 superdistrict-level calibration rows. "
         "All are 0.0 in the base 2023 model; used for EN7 scenario runs."),
    ],
    "Tour Mode Choice": [
        ("xfers_wlk_multiplier",
         "Fixed 10 → 30 to match CTRAMP (30 × c_ivt)."),
        ("xfers_drv_multiplier",
         "Fixed 20 → 40 to match CTRAMP (40 × c_ivt)."),
        ("coef_age1619_da_multiplier_atwork",
         "Sign flip (base: +0.003 → fix: −0.172). "
         "Base value near zero was likely an insignificant regression coefficient; "
         "corrected to match CTRAMP pre-resolved value."),
        ("coef_age010_trn_multiplier_atwork",
         "Sign flip (base: +0.0007 → fix: −0.038). "
         "Base value near zero was likely an insignificant regression coefficient; "
         "corrected to match CTRAMP pre-resolved value."),
        ("c_densityIndexOrigin",
         "FIXED: was missing from ASim Tour MC. CTRAMP WorkBased has "
         "c_densityIndexOrigin = 0.00188 (= −0.1 × c_ivt_atwork) used as "
         "max(c_densityIndexOrigin × originDensityIndex, originDensityIndexMax=0.282) "
         "for walk/bike/transit. Added to ASim Tour MC spec with "
         "origin_density_index_multiplier = −0.1, origin_density_index_max = −15, "
         "gated by is_atwork_subtour preprocessor variable."),
    ],
    "Trip Mode Choice": [
        ("coef_ivt_othmaint_social",
         "FIXED: ASim had −0.0175 (separate segment), CTRAMP has −0.0279 "
         "(same as escort/shopping/etc). OthMaint and Social are not a distinct "
         "IVT segment in CTRAMP Trip MC."),
        ("density_index_multiplier",
         "BUG FIXED: was −5, corrected to −0.2 to match CTRAMP. "
         "The upstream ActivitySim prototype_mtc had the same wrong value (−5), "
         "copied from example_psrc — part of the same translation-error cluster "
         "as ivt_exp_multiplier, ivt_com_multiplier, and the 11 atwork bugs.\n"
         "\n"
         "Tour MC already has density_index_multiplier = −0.2, matching CTRAMP. "
         "CTRAMP stores c_densityIndex = c_ivt × (−0.2); the old −5 gave "
         "a 25× over-weighting of the density bonus for walk/bike/transit."),
        ("origin_density_index_multiplier",
         "BUG FIXED: was −15, corrected to −0.6 to match CTRAMP. "
         "Same provenance as density_index_multiplier.\n"
         "\n"
         "STRUCTURAL DIFFERENCES beyond the coefficient value:\n"
         "1. ASim adds origin_density_applied template coefficient that gates this "
         "term OFF for work/univ/school (=0) and ON for escort+ (=1). CTRAMP applies "
         "it to ALL purposes via UEC alt columns.\n"
         "2. ASim uses .clip(min) giving a gradual ramp to the cap; CTRAMP uses "
         "max() which effectively returns a flat constant (the floor dominates)."),
        ("origin_density_index_max",
         "BUG FIXED: Expression used .clip(origin_density_index_max) which sets a "
         "LOWER bound (floor in negative space → ceiling in utility space). "
         "CTRAMP uses max(positive_product, positive_floor) which is a FLOOR in "
         "utility space. These are opposite behaviors.\n"
         "\n"
         "Fix: changed to .clip(upper=origin_density_index_max). In the negative "
         "domain, clip(upper=-15) prevents values from exceeding -15 (i.e. they "
         "stay at -15 or more negative), which after multiplication by negative "
         "coef_ivt produces a utility floor — matching CTRAMP.\n"
         "\n"
         "YAML value -15 is correct: -15 × coef_ivt = 0.33 (Work), 0.4185 (Escort)."),
        ("walktimelong_multiplier",
         "FIXED: was 5, CTRAMP = 10. Corrected to match CTRAMP (10 × c_ivt)."),
        ("xfers_wlk_multiplier",
         "FIXED: was 5, CTRAMP = 15. Corrected to match CTRAMP (15 × c_ivt)."),
        ("xfers_drv_multiplier",
         "FIXED: was 15, CTRAMP = 20. Corrected to match CTRAMP (20 × c_ivt)."),
        ("ivt_com_multiplier",
         "FIXED: was 0.80, CTRAMP = 0.70. Corrected to match CTRAMP (0.70 × c_ivt)."),
        ("ivt_exp_multiplier",
         "BUG FIXED: ASim had −0.0175, corrected to 1.0. "
         "Accidental paste of coef_ivt_othmaint_social value; "
         "Tour MC correctly has 1.0. Expression uses (M − 1) × KEYIVT, "
         "so M=1.0 produces zero incremental IVT (correct: express = base IVT). "
         "With −0.0175 it produced a massive spurious positive IVT penalty."),
        ("ivt_cost_multiplier",
         "Structurally equivalent. CTRAMP formula is (0.6 × c_ivt) / vot; "
         "ASim uses ivt_cost_multiplier × df.ivot × coef_ivt. "
         "The 0.6 multiplier matches."),
        ("Atwork _multiplier coefficients (systematic)",
         "BUG FIXED: All 11 atwork LOS multiplier coefficients were wrong by a factor "
         "of 0.6738 (= 0.0188/0.0279). The ASim developer divided by the Tour MC "
         "at-work c_ivt (−0.0188) instead of the Trip MC c_ivt (−0.0279). "
         "In CTRAMP Trip MC, WorkBased tokens are IDENTICAL to Escort/Shopping/etc. "
         "Fixed: coef_wacc_atwork (1.348→2.0), coef_walktimeshort_atwork (1.348→2.0), "
         "coef_biketimeshort_atwork (2.695→4.0), coef_dtim_atwork (1.348→2.0), "
         "coef_ivt_ferry_atwork (0.539→0.8), coef_ivt_lrt_atwork (0.606→0.9), "
         "coef_long_iwait_atwork (0.674→1.0), coef_short_iwait_atwork (1.348→2.0), "
         "coef_waux_atwork (1.348→2.0), coef_wegr_atwork (1.348→2.0), "
         "coef_xwait_atwork (1.348→2.0)."),
    ],
}

# Crosswalk for size-terms: CTRAMP (purpose, segment) → ASim (model_selector, segment)
SIZE_TERMS_CROSSWALK: dict[tuple[str, str], tuple[str, str]] = {
    ("work", "low"):            ("workplace", "work_low"),
    ("work", "med"):            ("workplace", "work_med"),
    ("work", "high"):           ("workplace", "work_high"),
    ("work", "very high"):      ("workplace", "work_veryhigh"),
    ("university", "university"): ("school", "university"),
    ("school", "grade"):        ("school", "gradeschool"),
    ("school", "high"):         ("school", "highschool"),
    ("escort", "kids"):         ("non_mandatory", "escort_kids"),
    ("escort", "no kids"):      ("non_mandatory", "escort_nokids"),
    ("shopping", "shopping"):   ("non_mandatory", "shopping"),
    ("eatout", "eatout"):       ("non_mandatory", "eatout"),
    ("othmaint", "othmaint"):   ("non_mandatory", "othmaint"),
    ("social", "social"):       ("non_mandatory", "social"),
    ("othdiscr", "othdiscr"):   ("non_mandatory", "othdiscr"),
    ("atwork", "atwork"):       ("atwork", "atwork"),
}

# fmt: on
