---
title: "Summarize Express Lane Prices"
author: "David Ory"
runtime: shiny
output: 
   html_document:
      theme: cosmo
      toc: yes
---

## Administration

#### Purpose
This script consumes travel model roadway network data generated by `extract-express-lane-data.job` and builds tables showing the characteristics of each express lane corridor.  

#### Outputs
1.  Shiny interactive

## Procedure

#### Overhead
```{r overhead, results = 'hide', include=FALSE}
library(knitr)
library(reshape2)
suppressMessages(library(dplyr))
library(stringr)
library(xtable)
```

```{r config, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

#### Parameters
```{r parameters}
LOW_VC_THRESH = 0.60
HIGH_VC_THRESH = 0.80
```

```{r remote-io, include=FALSE}
# F_NETWORK = "~DavidWork/Documents/express-lane-prices-tests/express-lane-data.csv"
F_NETWORK = "M:/Application/Model One/RTP2017/Project Performance Assessment/Baseline Network/_working/_toll_calcs/express-lane-data.csv"
```

```{r data-reads, include=FALSE}
# Read the data
network_df <- read.table(file = F_NETWORK, header = TRUE, sep = ",", stringsAsFactors = FALSE)
```

```{r procedure, include=FALSE}
# Re-align as database
time_dimension   <- c("ea", "am", "md", "pm", "ev")
volume_dimension <- c("dat", "s2t", "tot")
price_dimension  <- c("da", "s2")

# Initialize output with first entry
time   = time_dimension[1]
volume = volume_dimension[1]
price  = price_dimension[1]

price_variable  = paste("toll",time,"_",price, sep = "")
volume_variable = paste("vol",time,"_",volume, sep = "")
vc_variable     = paste("vc", toupper(time), sep = "")

price_df <- network_df %>%
  select_(.dots = setNames(price_variable, "price"))

volume_df <- network_df %>%
  select_(.dots = setNames(volume_variable, "volume"))

vc_df <- network_df %>%
  select_(.dots = setNames(vc_variable, "vc"))

working_df <- network_df %>%
  select(a, b, distance, tollclass) %>%
  mutate(class = volume) %>%
  mutate(time = time)

working_df <- cbind(working_df, price_df, volume_df, vc_df)

for (time in 1:length(time_dimension)){
  
  for (volume in 1:length(volume_dimension)){
    
    if(!(time == 1 & volume ==1)) {
      
      volume_variable = paste("vol",time_dimension[time],"_",volume_dimension[volume], sep = "")
      vc_variable     = paste("vc", toupper(time_dimension[time]), sep = "")
      
      volume_df <- network_df %>%
        select_(.dots = setNames(volume_variable, "volume"))
      
      vc_df <- network_df %>%
        select_(.dots = setNames(vc_variable, "vc"))
      
      entry_df <- network_df %>%
        select(a, b, distance, tollclass) %>%
        mutate(class = volume_dimension[volume]) %>%
        mutate(time = time_dimension[time])
      
      entry_df <- cbind(entry_df, volume_df, vc_df)
      
      if(volume == 3) {
        
        # no price dimension
        entry_df <- entry_df %>%
          mutate(price = NA)
        
        } else{
          
          price = volume
          price_variable  = paste("toll",time_dimension[time],"_",price_dimension[price], sep = "")
          
          price_df <- network_df %>%
            select_(.dots = setNames(price_variable, "price"))
          
          entry_df <- cbind(entry_df, price_df)     
          
          } # else
      
      working_df <- rbind(working_df, entry_df)
    
    } # if not first  
  } # mode
} # time

remove(price_df, volume_df, vc_df, volume, time, price_variable, vc_variable, volume_variable)
```

```{r summarize, include=FALSE}
# Do link (across mode) specific summaries (same across da, s2)
link_summary <- working_df %>%
  mutate(no_volume_dist = ifelse(volume < 1.0, distance, 0)) %>%
  mutate(low_vc_dist = ifelse(vc < LOW_VC_THRESH, distance, 0)) %>%
  mutate(high_vc_dist = ifelse(vc > HIGH_VC_THRESH, distance, 0)) %>%
  filter(class == "tot") %>%
  group_by(tollclass, time) %>%
  summarize(distance = sum(distance),
            links = n(),
            all_mean_vehs = mean(volume),
            no_volume_dist = sum(no_volume_dist),
            low_vc_dist = sum(low_vc_dist),
            high_vc_dist = sum(high_vc_dist)) %>%
  mutate(no_volume_dist_share = no_volume_dist / distance * 100) %>%
  mutate(low_vc_dist_share = low_vc_dist / distance * 100) %>%
  mutate(high_vc_dist_share = high_vc_dist / distance * 100) %>%
  mutate(target_vc_dist_share = 100.0 - low_vc_dist_share - high_vc_dist_share)
  
# Drive alone pay-specific summaries
da_summary <- working_df %>%
  filter(class == "dat") %>%
  group_by(tollclass, time) %>%
  summarize(da_mean_price = mean(price/distance), da_mean_vehs = mean(volume))

# Share-ride 2 pay-specific summaries
s2_summary <- working_df %>%
  filter(class == "s2t") %>%
  group_by(tollclass, time) %>%
  summarize(s2_mean_price = mean(price/distance), s2_mean_vehs = mean(volume))

summary_df <- left_join(link_summary, da_summary, by = c("tollclass", "time"))
summary_df <- left_join(summary_df,   s2_summary, by = c("tollclass", "time"))

summary_df <- summary_df %>%
  mutate(da_share = ifelse(all_mean_vehs > 0, da_mean_vehs / all_mean_vehs, 0)) %>%
  mutate(s2_share = ifelse(all_mean_vehs > 0, s2_mean_vehs / all_mean_vehs, 0))
  
remove(link_summary, da_summary, s2_summary)
   
```

## Interactives
```{r shiny_table, echo=FALSE, cache=FALSE}
inputPanel(
  selectInput("time_name", label = "Time of Day:", choices = unique(summary_df$time), selected = "am")
  )

renderDataTable({
  table_df <- summary_df %>%
    filter(time == input$time_name) %>%
    filter(da_mean_price > 0.0) %>%
    mutate(all_vehs = round(all_mean_vehs, 0)) %>%
    mutate(dat_vehs = round(da_mean_vehs, 0)) %>%
    mutate(s2t_vehs = round(s2_mean_vehs, 0)) %>%
    mutate(dat_shr  = round(da_share * 100, 1)) %>%
    mutate(s2t_shr  = round(s2_share * 100, 1)) %>%
    mutate(dat_prc  = round(da_mean_price, 2)) %>%
    mutate(s2t_prc  = round(s2_mean_price, 2)) %>%
    mutate(lo_vc    = round(low_vc_dist_share, 1)) %>%
    mutate(trg_vc   = round(target_vc_dist_share, 1)) %>%
    mutate(hi_vc    = round(high_vc_dist_share, 1)) %>%
    select(tollclass, links, 
           all_vehs, dat_vehs, s2t_vehs,
           dat_shr, s2t_shr, 
           dat_prc, s2t_prc,
           lo_vc, trg_vc, hi_vc)
    
  })


```

