[//4]: # (### Non-Mandatory Destination Choice)

The non-mandatory tour destination models operate similar to the Usual Work and School Location choice model. The main procedural difference between the models is the usual work and school location choice model selects the usual locationn of the mandatory activity regardless if the activity is undertaken during the travel day, while the non-mandatory tour destination choice model selects the location for an actiivity that has already been generated. 

Calibration for the Non-Mandatoryy Destination Choice model focused on matching the observed tour length frequency distributions from the household survey. The match required adjusting the piecewise linear distance term in the untiltiy function. Tour length frequency distributions were grouped by tour primary purpose. 

A tour's "primary purpose" and in turn primary destination is the purpose and location of the activity that is assumed to provide the greatest impetus for engaging in the travel tour. In the household survey, the primary destination was not asked and instead inferred from the pattern of stops in a closed loop in the respondents' travel diaries. The inference is made by weighting multiple criteria including a defined hierarchy of purposes and the duration of activites. 

(TODO: Add more detailed about this tour purpose)

#### Frequency Distribution
- Escort
```{python}
from calib_report import config
from calib_report.data import nonwork_dest
chts_file = config.CHTS_DIR / "nonMandTourDistProfile.csv"
bats_file = config.BATS_DIR / "BATS2023_TLFD.csv" 

```

```{python}
#| label: fig-escort-tlfd
#| fig-cap: Escort Tour Length Frequency Distributions
#| fig-subcap: 
#|  - "CHTS 2012"
#|  - "BATS2023"

nonwork_dest.plot_tlfd(
    chts_file,
    "escort",
    "Percent of Tours",
    chts_source = True
)

nonwork_dest.plot_tlfd(
    bats_file,
    "escort",
    "Percent of Tours"
)
```
```{python}
#| label: fig-shop-tlfd
#| fig-cap: Shop Tour Length Frequency Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "shop",
    "Percent of Tours"
)
```
```{python}
#| label: fig-maint-tlfd
#| fig-cap: Maintenance Tour Length Frequency Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "maintenance",
    "Percent of Tours"
)
```
```{python}
#| label: fig-eatout-tlfd
#| fig-cap: Eating Out Tour Length Frequency Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "eatout",
    "Percent of Tours"
)
```
```{python}
#| label: fig-visit-tlfd
#| fig-cap: Visit Tour Length Frequency Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "visit",
    "Percent of Tours"
)
```

```{python}
#| label: fig-discr-tlfd
#| fig-cap: Discretionary Tour Length Frequeny Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "discretionary",
    "Percent of Tours"
)
```
```{python}
#| label: fig-atwork-tlfd
#| fig-cap: At-Work Tour Length Frequency Distributions
nonwork_dest.plot_tlfd(
    bats_file,
    "atwork",
    "Percent of Tours"
)

```