library(dplyr)
library(tidyr)

# For RStudio, these can be set in the .Rprofile
TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, "OUTPUT", "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

cat("TARGET_DIR  = ",TARGET_DIR, "\n")
cat("ITER        = ",ITER,       "\n")
cat("SAMPLESHARE = ",SAMPLESHARE,"\n")

######### counties
LOOKUP_COUNTY        <- data.frame(COUNTY=c(1,2,3,4,5,6,7,8,9),
                                   county_name=c("01 San Francisco","02 San Mateo","03 Santa Clara","04 Alameda",
                                                 "05 Contra Costa","06 Solano","07 Napa","08 Sonoma","09 Marin"))
LOOKUP_COUNTY$COUNTY      <- as.integer(LOOKUP_COUNTY$COUNTY)
LOOKUP_COUNTY$county_name <- as.character(LOOKUP_COUNTY$county_name)


tazData              <- read.table(file=file.path(TARGET_DIR,"INPUT","landuse","tazData.csv"), header=TRUE, sep=",")

wsloc_results        <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",
                                                  paste0("wsLocResults_",ITER,".csv")), header=TRUE, sep=",")

# generated by extract_skim_table.job
dist_skim            <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", "HWYSKIMMD_DISTDA.csv"),
                                   header=FALSE, col.names=c("TAZ","ones",1:1475), sep=",") %>% select(-ones)
# convert to OTAZ, DTAZ, DISTDA
dist_skim <- gather(dist_skim, "DTAZ", "DISTDA", X1:X1475)
dist_skim$DTAZ = strtoi(substring(dist_skim$DTAZ, 2))
dist_skim <- rename(dist_skim, OTAZ=TAZ)

# add Home COUNTY
wsloc_results <- left_join(wsloc_results, 
                           rename(select(tazData, ZONE, COUNTY), HomeTAZ=ZONE)) %>% left_join(LOOKUP_COUNTY)
wsloc_results <- rename(wsloc_results,HomeCOUNTY=COUNTY, Home_county_name=county_name)

# add Work COUNTY
wsloc_results <- left_join(wsloc_results, 
                           rename(select(tazData, ZONE, COUNTY), WorkLocation=ZONE)) %>% left_join(LOOKUP_COUNTY)
wsloc_results <- rename(wsloc_results,WorkCOUNTY=COUNTY, Work_county_name=county_name)


# summarize to (Home County, Work County)
wsloc_county  <- group_by(wsloc_results, Home_county_name, Work_county_name) %>% summarise(num_pers=n())
# divide by SAMPLESHARE
wsloc_county  <- mutate(wsloc_county, num_pers=num_pers/SAMPLESHARE)

wsloc_county_spread <- spread(wsloc_county, key=Work_county_name, value=num_pers)

# save it
write.table(wsloc_county_spread, file.path(OUTPUT_DIR,"01_usual_work_school_location_TM_county.csv"), sep=",", row.names=FALSE)
cat("Wrote ",file.path(OUTPUT_DIR,"01_usual_work_school_location_TM_county.csv\n"))


# trip length frequency distribution
for (trip_type in c("work","univ","school")) {
  if (trip_type == "work") {
    trip_dists <- subset(wsloc_results, subset=WorkLocation>0,
                         select=c(Home_county_name, EmploymentCategory, HomeTAZ, WorkLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, WorkLocation=DTAZ))
  } else if (trip_type == "univ") {
    trip_dists <- subset(wsloc_results, subset=(SchoolLocation>0)&(StudentCategory=="College or higher"),
                         select=c(Home_county_name, StudentCategory, HomeTAZ, SchoolLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, SchoolLocation=DTAZ))
  } else if (trip_type == "school") {
    trip_dists <- subset(wsloc_results, subset=(SchoolLocation>0)&(StudentCategory=="Grade or high school"),
                         select=c(Home_county_name, StudentCategory, HomeTAZ, SchoolLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, SchoolLocation=DTAZ))
  }
  trip_tlfd  <- data.frame(distbin=seq(1,150,by=1))

  # by county
  for (county in LOOKUP_COUNTY$county_name) {
    county_trip_dists <- subset(trip_dists, subset=Home_county_name==county)
    head(county_trip_dists)
    county_trip_hist  <- hist(county_trip_dists$DISTDA, breaks=seq(0,150,by=1), plot=FALSE)
    county_trip_tlfd  <- data.frame(distbin=county_trip_hist$breaks[2:length(county_trip_hist$breaks)], 
                                    county_total=county_trip_hist$counts)
    county_trip_tlfd  <- mutate(county_trip_tlfd, county_total=county_total/SAMPLESHARE) # divide by SAMPLESHARE
    colnames(county_trip_tlfd)[colnames(county_trip_tlfd)=="county_total"] <- substring(county,4)
    trip_tlfd <- left_join(trip_tlfd, county_trip_tlfd)
  }

  # total
  total_trip_hist  <- hist(trip_dists$DISTDA, breaks=seq(0,150,by=1), plot=FALSE)
  total_trip_tlfd  <- data.frame(distbin=total_trip_hist$breaks[2:length(total_trip_hist$breaks)],
                               Total=total_trip_hist$counts)
  total_trip_tlfd  <- mutate(total_trip_tlfd, Total=Total/SAMPLESHARE) # divide by SAMPLESHARE
  trip_tlfd        <- left_join(trip_tlfd, total_trip_tlfd)

  # want columns: distbin, counties in alpha order, then Total
  col_order <- c("distbin", sort(substring(LOOKUP_COUNTY$county_name,4)), "Total")
  trip_tlfd <- trip_tlfd[col_order]

  # save it
  outfile <- file.path(OUTPUT_DIR, paste0("01_usual_work_school_location_TM_",trip_type,"_TLFD.csv"))
  write.table(trip_tlfd, outfile, sep=",", row.names=FALSE)
  cat("Wrote ",outfile,"\n")
}
