library(dplyr)
library(tidyr)
options(java.parameters = "-Xmx8000m")  # xlsx uses java and can run out of memory
library(xlsx)

# For RStudio, these can be set in the .Rprofile
TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling

WORKBOOK       <- "M:\\Development\\Travel Model One\\Calibration\\Version 1.5.0\\01 Usual Work and School Location\\01_UsualWorkAndSchoolLocation.xlsx"
WORKBOOK_BLANK <- gsub(".xlsx","_blank.xlsx",WORKBOOK)
WORKBOOK_TEMP  <- gsub(".xlsx","_temp.xlsx", WORKBOOK)
calib_workbook <- loadWorkbook(file=WORKBOOK_BLANK)
calib_sheets   <- getSheets(calib_workbook)

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
WORKBOOK     <- gsub("\\\\","/",WORKBOOK  ) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, "OUTPUT", "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

print(paste0("TARGET_DIR  = ",TARGET_DIR ))
print(paste0("ITER        = ",ITER       ))
print(paste0("SAMPLESHARE = ",SAMPLESHARE))

######### counties
LOOKUP_COUNTY        <- data.frame(COUNTY=c(1,2,3,4,5,6,7,8,9),
                                   county_name=c("01 San Francisco","02 San Mateo","03 Santa Clara","04 Alameda",
                                                 "05 Contra Costa","06 Solano","07 Napa","08 Sonoma","09 Marin"))
LOOKUP_COUNTY$COUNTY      <- as.integer(LOOKUP_COUNTY$COUNTY)
LOOKUP_COUNTY$county_name <- as.character(LOOKUP_COUNTY$county_name)


tazData              <- read.table(file=file.path(TARGET_DIR,"INPUT","landuse","tazData.csv"), header=TRUE, sep=",")

wsloc_results        <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",
                                                  paste0("wsLocResults_",ITER,".csv")), header=TRUE, sep=",")

# generated by extract_skim_table.job
dist_skim            <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", "HWYSKMMD_DISTDA.csv"),
                                   header=FALSE, col.names=c("OTAZ","DTAZ","ones","DISTDA"), sep=",") %>% select(-ones)

# add Home COUNTY
wsloc_results <- left_join(wsloc_results, 
                           rename(select(tazData, ZONE, COUNTY), HomeTAZ=ZONE)) %>% left_join(LOOKUP_COUNTY)
wsloc_results <- rename(wsloc_results,HomeCOUNTY=COUNTY, Home_county_name=county_name)

# add Work COUNTY
wsloc_results <- left_join(wsloc_results, 
                           rename(select(tazData, ZONE, COUNTY), WorkLocation=ZONE)) %>% left_join(LOOKUP_COUNTY)
wsloc_results <- rename(wsloc_results,WorkCOUNTY=COUNTY, Work_county_name=county_name)


# summarize to (Home County, Work County)
wsloc_county  <- group_by(wsloc_results, Home_county_name, Work_county_name) %>% summarise(num_pers=n())
# divide by SAMPLESHARE
wsloc_county  <- mutate(wsloc_county, num_pers=num_pers/SAMPLESHARE)

wsloc_county_spread <- spread(wsloc_county, key=Work_county_name, value=num_pers)

# fillNA
wsloc_county_spread[is.na(wsloc_county_spread)] <- 0

# save it
outfile <- file.path(OUTPUT_DIR,"01_usual_work_school_location_TM_county.csv")
write.table(wsloc_county_spread, outfile, sep=",", row.names=FALSE)
print(paste("Wrote",outfile))

# save it (along with source label) to calibration workbook
addDataFrame(as.data.frame(wsloc_county_spread), calib_sheets$modeldata, startRow=4, startColumn=1, row.names=FALSE)
source_cell <- getCells( getRows(calib_sheets$modeldata, rowIndex=1:1), colIndex=1:1 )
setCellValue(source_cell[[1]], paste("Source: ",outfile))

avg_trip_lengths <- data.frame(county=character(), trip_type=character(), mean_trip_length=double(), stringsAsFactors = FALSE)

# trip length frequency distribution
for (trip_type in c("work","univ","school")) {
  col = 1
  if (trip_type == "work") {
    trip_dists <- subset(wsloc_results, subset=WorkLocation>0,
                         select=c(Home_county_name, EmploymentCategory, HomeTAZ, WorkLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, WorkLocation=DTAZ))
  } else if (trip_type == "univ") {
    trip_dists <- subset(wsloc_results, subset=(SchoolLocation>0)&(StudentCategory=="College or higher"),
                         select=c(Home_county_name, StudentCategory, HomeTAZ, SchoolLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, SchoolLocation=DTAZ))
    col = 14
  } else if (trip_type == "school") {
    trip_dists <- subset(wsloc_results, subset=(SchoolLocation>0)&(StudentCategory=="Grade or high school"),
                         select=c(Home_county_name, StudentCategory, HomeTAZ, SchoolLocation))
    trip_dists <- left_join(trip_dists, rename(dist_skim, HomeTAZ=OTAZ, SchoolLocation=DTAZ))
    col = 27
  }
  
  trip_tlfd  <- data.frame(distbin=seq(1,150,by=1))

  # by county
  for (county in LOOKUP_COUNTY$county_name) {
    county_trip_dists <- subset(trip_dists, subset=Home_county_name==county)
    head(county_trip_dists)
    county_trip_hist  <- hist(county_trip_dists$DISTDA, breaks=seq(0,150,by=1), plot=FALSE)
    county_trip_tlfd  <- data.frame(distbin=county_trip_hist$breaks[2:length(county_trip_hist$breaks)], 
                                    county_total=county_trip_hist$counts)
    county_trip_tlfd  <- mutate(county_trip_tlfd, county_total=county_total/SAMPLESHARE) # divide by SAMPLESHARE
    colnames(county_trip_tlfd)[colnames(county_trip_tlfd)=="county_total"] <- substring(county,4)
    trip_tlfd <- left_join(trip_tlfd, county_trip_tlfd)
    
    avg_trip_lengths[nrow(avg_trip_lengths)+1,]=list(substring(county,4),trip_type,mean(county_trip_dists$DISTDA))
  }

  # total
  total_trip_hist  <- hist(trip_dists$DISTDA, breaks=seq(0,150,by=1), plot=FALSE)
  total_trip_tlfd  <- data.frame(distbin=total_trip_hist$breaks[2:length(total_trip_hist$breaks)],
                               Total=total_trip_hist$counts)
  total_trip_tlfd  <- mutate(total_trip_tlfd, Total=Total/SAMPLESHARE) # divide by SAMPLESHARE
  trip_tlfd        <- left_join(trip_tlfd, total_trip_tlfd)

  avg_trip_lengths[nrow(avg_trip_lengths)+1,]=list("Total",trip_type,mean(county_trip_dists$DISTDA))
  
  # want columns: distbin, counties in alpha order, then Total
  col_order <- c("distbin", sort(substring(LOOKUP_COUNTY$county_name,4)), "Total")
  trip_tlfd <- trip_tlfd[col_order]

  # save it
  outfile <- file.path(OUTPUT_DIR, paste0("01_usual_work_school_location_TM_",trip_type,"_TLFD.csv"))
  write.table(trip_tlfd, outfile, sep=",", row.names=FALSE)
  print(paste("Wrote",outfile))

  # save it (along with source label) to calibration workbook
  addDataFrame(as.data.frame(trip_tlfd), calib_sheets$modeldata, startRow=19, startColumn=col, row.names=FALSE)
  source_cell <- getCells( getRows(calib_sheets$modeldata, rowIndex=17:17), colIndex=col:col )
  setCellValue(source_cell[[1]], paste("Source: ",outfile))
}

remove(dist_skim)

# move trip types to columns and reorder
avg_triplen_spread <- spread(avg_trip_lengths, key=trip_type, value=mean_trip_length)
avg_triplen_spread <- avg_triplen_spread[c("county","work","univ","school")]

# save average trip lengths
outfile <- file.path(OUTPUT_DIR, paste0("01_usual_work_school_location_TM_avgtriplen.csv"))
write.table(avg_triplen_spread, outfile, sep=",", row.names=FALSE)
print(paste("Wrote",outfile))

# save it (along with source label) to calibration workbook
addDataFrame(as.data.frame(avg_triplen_spread), calib_sheets$modeldata, startRow=4, startColumn=14, row.names=FALSE)
source_cell <- getCells( getRows(calib_sheets$modeldata, rowIndex=3:3), colIndex=14:14 )
setCellValue(source_cell[[1]], paste("Source: ",outfile))

saveWorkbook(calib_workbook, WORKBOOK_TEMP)
forceFormulaRefresh(WORKBOOK_TEMP, WORKBOOK, verbose=TRUE)
print(paste("Wrote",WORKBOOK))