library(dplyr)
library(tidyr)
options(java.parameters = "-Xmx8000m")  # xlsx uses java and can run out of memory
library(xlsx)

TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling
CODE_DIR     <- Sys.getenv("CODE_DIR")    # location of utilitiles\calibration code
CALIB_ITER   <- Sys.getenv("CALIB_ITER")  # calibration iteration

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
CODE_DIR     <- gsub("\\\\","/",CODE_DIR  ) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, paste0("OUTPUT_",CALIB_ITER), "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)
stopifnot(nchar(CODE_DIR    )>0)
stopifnot(nchar(CALIB_ITER  )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

print(paste0("TARGET_DIR  = ",TARGET_DIR ))
print(paste0("ITER        = ",ITER       ))
print(paste0("SAMPLESHARE = ",SAMPLESHARE))
print(paste0("CODE_DIR    = ",CODE_DIR   ))
print(paste0("CALIB_ITER  = ",CALIB_ITER ))

WORKBOOK       <- "M:\\Development\\Travel Model One\\Calibration\\Version 1.5.2\\09 Non-Work Destination Choice\\09_NonWorkDestinationChoice.xlsx"
WORKBOOK       <- gsub("\\\\","/",WORKBOOK  ) # switch slashes around
WORKBOOK_TEMP  <- gsub(".xlsx","_temp.xlsx", WORKBOOK)
WORKBOOK_BLANK <- file.path(CODE_DIR, "workbook_templates", "09_NonWorkDestinationChoice_blank.xlsx")
calib_workbook <- loadWorkbook(file=WORKBOOK_BLANK)
calib_sheets   <- getSheets(calib_workbook)

######### counties
LOOKUP_COUNTY        <- data.frame(COUNTY=c(1,2,3,4,5,6,7,8,9),
                                   county_name=c("01 San Francisco","02 San Mateo","03 Santa Clara","04 Alameda",
                                                 "05 Contra Costa","06 Solano","07 Napa","08 Sonoma","09 Marin"))
LOOKUP_COUNTY$COUNTY      <- as.integer(LOOKUP_COUNTY$COUNTY)
LOOKUP_COUNTY$county_name <- as.character(LOOKUP_COUNTY$county_name)


tazData              <- read.table(file=file.path(TARGET_DIR,"INPUT","landuse","tazData.csv"), header=TRUE, sep=",")

indiv_tour_results   <- read.table(file=file.path(TARGET_DIR,paste0("OUTPUT_",CALIB_ITER),"main",paste0("indivTourData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(hh_id, person_id, tour_id, tour_category, tour_purpose, tour_mode, start_hour, end_hour, orig_taz, dest_taz)

joint_tour_results   <- read.table(file=file.path(TARGET_DIR,paste0("OUTPUT_",CALIB_ITER),"main",paste0("jointTourData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(hh_id, tour_participants, tour_id, tour_category, tour_purpose, tour_mode, start_hour, end_hour, orig_taz, dest_taz)

# create num_participants, indiv_joint column
joint_tour_results$tour_participants <- as.character(joint_tour_results$tour_participants)
count_participants <- function(x) { length(strsplit(x," ")[[1]]) }
joint_tour_results <- mutate(joint_tour_results, 
                             num_participants=count_participants(tour_participants),
                             indiv_joint="joint")
indiv_tour_results <- mutate(indiv_tour_results,
                             num_participants=1,
                             indiv_joint="indiv")

# put them together
tour_results <- rbind(select(indiv_tour_results, -person_id),
                      select(joint_tour_results, -tour_participants))

# generated by extract_skim_table.job
dist_skim            <- read.table(file=file.path(TARGET_DIR, "OUTPUT_00", "skims", "HWYSKMMD_DISTDA.csv"),
                                   header=FALSE, col.names=c("OTAZ","DTAZ","ones","DISTDA"), sep=",") %>% select(-ones)

avg_trip_lengths <- data.frame(trip_type=character(), mean_trip_length=double(), stringsAsFactors = FALSE)

# trip length frequency distribution
trip_types  = c("escort","shop","maintenance","eatout","visit","discretionary","atwork")
distbin_seq = seq(0,150,by=1)

trip_tlfd_all =  data.frame(distbin=seq(1,150,by=1))
for (trip_type in trip_types) {
  if (trip_type == "escort") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("escort_kids", "escort_no kids"))
  } else if (trip_type == "shop") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("shopping"))
  } else if (trip_type == "maintenance") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("othmaint"))
  } else if (trip_type == "eatout") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("eatout"))
  } else if (trip_type == "visit") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("social"))
  } else if (trip_type == "discretionary") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("othdiscr"))
  } else if (trip_type == "atwork") {
    trip_dists <- subset(tour_results, subset=tour_purpose %in% c("atwork_business", "atwork_eat", "atwork_maint"))
  }

  trip_dists <- left_join(trip_dists, rename(dist_skim, orig_taz=OTAZ, dest_taz=DTAZ))
  trip_tlfd  <- data.frame(distbin=distbin_seq)

  # total
  total_trip_hist  <- hist(trip_dists$DISTDA, breaks=distbin_seq, plot=FALSE)
  total_trip_tlfd  <- data.frame(distbin=total_trip_hist$breaks[2:length(total_trip_hist$breaks)],
                               Total=total_trip_hist$counts)
  total_trip_tlfd  <- mutate(total_trip_tlfd, Total=Total/SAMPLESHARE) # divide by SAMPLESHARE
  # rename to trip_type
  names(total_trip_tlfd)[names(total_trip_tlfd) == "Total"] <- trip_type
  
  avg_trip_lengths[nrow(avg_trip_lengths)+1,]=list(trip_type,mean(trip_dists$DISTDA))
  
  trip_tlfd_all    <- left_join(trip_tlfd_all, total_trip_tlfd)
}

remove(dist_skim)

# save it
outfile <- file.path(OUTPUT_DIR, paste0("09_nonwork_destination_TM_TLFD.csv"))
write.table(trip_tlfd_all, outfile, sep=",", row.names=FALSE)
print(paste("Wrote",outfile))

# save it (along with source label) to calibration workbook
addDataFrame(as.data.frame(trip_tlfd_all), calib_sheets$modeldata, startRow=3, startColumn=1, row.names=FALSE)
source_cell <- getCells( getRows(calib_sheets$modeldata, rowIndex=2:2), colIndex=1:1 )
setCellValue(source_cell[[1]], paste("Source: ",outfile))

# save average trip lengths
outfile <- file.path(OUTPUT_DIR, paste0("09_nonwork_destination_TM_avgtriplen.csv"))
write.table(avg_trip_lengths, outfile, sep=",", row.names=FALSE)
print(paste("Wrote",outfile))

# save it (along with source label) to calibration workbook
addDataFrame(as.data.frame(avg_trip_lengths), calib_sheets$modeldata, startRow=3, startColumn=10, row.names=FALSE)
source_cell <- getCells( getRows(calib_sheets$modeldata, rowIndex=2:2), colIndex=10:10 )
setCellValue(source_cell[[1]], paste("Source: ",outfile))

saveWorkbook(calib_workbook, WORKBOOK_TEMP)
forceFormulaRefresh(WORKBOOK_TEMP, WORKBOOK, verbose=TRUE)
print(paste("Wrote",WORKBOOK))