library(dplyr)
library(tidyr)

# For RStudio, these can be set in the .Rprofile
TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, "OUTPUT", "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

cat("TARGET_DIR  = ",TARGET_DIR, "\n")
cat("ITER        = ",ITER,       "\n")
cat("SAMPLESHARE = ",SAMPLESHARE,"\n")

input.pop.households <- read.table(file = file.path(TARGET_DIR,"INPUT","popsyn","hhFile.calib.2015.csv"),
                                   header=TRUE, sep=",") %>%
  select(HHID, TAZ, PERSONS, hworkers)

# read ferry skims because the only way to separate ferry tours from light rail tours is with ferry availability :p
# generated by extract_skim_table.job
table      <- "ivtFerry"
ferry_skim <- data.frame()
for (timeperiod in c("EA","AM","MD", "PM", "EV")) {
  for (submode in c("wlk_lrf_wlk","drv_lrf_wlk","wlk_lrf_drv")) {
    skim_table <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", paste0("trnskm",timeperiod,"_",submode,"_",table,".csv")),
                             header=FALSE, col.names=c("OTAZ","DTAZ","ones",table), sep=",") %>% 
      select(-ones) %>%
      mutate(timeperiod=timeperiod, submode=submode)
    ferry_skim <- rbind(ferry_skim, skim_table)
  }
}
remove(skim_table)

ao_results           <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main","aoResults.csv"), header=TRUE, sep=",")

indiv_tour_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("indivTourData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(hh_id, person_id, tour_id, tour_category, tour_purpose, tour_mode, start_hour, end_hour, orig_taz, dest_taz)

joint_tour_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("jointTourData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(hh_id, tour_participants, tour_id, tour_category, tour_purpose, tour_mode, start_hour, end_hour, orig_taz, dest_taz)

# create num_participants, indiv_joint column
joint_tour_results$tour_participants <- as.character(joint_tour_results$tour_participants)
count_participants <- function(x) { length(strsplit(x," ")[[1]]) }
joint_tour_results <- mutate(joint_tour_results, 
                             num_participants=count_participants(tour_participants),
                             indiv_joint="joint")
indiv_tour_results <- mutate(indiv_tour_results,
                             num_participants=1,
                             indiv_joint="indiv")

# put them together
tour_results <- rbind(select(indiv_tour_results, -person_id),
                      select(joint_tour_results, -tour_participants))

# add number of workers and number of vehicles to indiv_tour_results
tour_results <- left_join(tour_results, ao_results, by=c("hh_id"="HHID"))
tour_results <- left_join(tour_results, input.pop.households, by=c("hh_id"="HHID"))

tour_results <- mutate(tour_results, 
                       auto_suff=if_else(AO==0, "Autos=0", if_else(AO<hworkers, "Autos<Workers", "Autos>=Workers")))

# summarize to "auto_sufficiency", indiv_joint, tour purpose and tour mode
tour_summary <- group_by(tour_results, auto_suff, indiv_joint, tour_purpose, tour_mode) %>% 
  summarise(num_tours=sum(num_participants)) %>%
  mutate(num_tours=num_tours/SAMPLESHARE)

# move auto_sufficiency to columns
tour_summary_spread <- spread(tour_summary, key=auto_suff, value=num_tours)

# reorder
tour_summary_spread <- tour_summary_spread[c("indiv_joint","tour_purpose","tour_mode",
                                             "Autos=0","Autos<Workers","Autos>=Workers")]
# fillNA
tour_summary_spread[is.na(tour_summary_spread)] <- 0


# save it
outfile <- file.path(OUTPUT_DIR, paste0("11_tour_mode_choice_TM.csv"))
write.table(tour_summary_spread, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")

# transit submode summary
# Want submode: Local, LRT-Walk, LRT-Drive, Ferry-Walk, Ferry-Drive, Express, HeavyRail, CommRail
transit_tour_results <- subset(tour_results, subset=(tour_mode>=9)&(tour_mode<=18))
# split into LRF and non-LRF with trn_submodes
nonLRF_tour_results  <- subset(transit_tour_results, subset=(tour_mode!=10)&(tour_mode!=15)) %>%
  mutate(trn_submode=case_when(tour_mode== 9 ~ "Local",
                               tour_mode==11 ~ "Express",
                               tour_mode==12 ~ "HeavyRail",
                               tour_mode==13 ~ "CommRail",
                               tour_mode==14 ~ "Local",
                               tour_mode==16 ~ "Express",
                               tour_mode==17 ~ "HeavyRail",
                               tour_mode==18 ~ "CommRail"))

LRF_tour_results     <- subset(transit_tour_results, subset=(tour_mode==10)|(tour_mode==15)) %>%
  mutate(lrf_submode=case_when(tour_mode==10 ~ "LRF-Walk",
                               tour_mode==15 ~ "LRF-Drive"))
# to distinguish between LRT and Ferry, we need to look at availability
LRF_tour_results     <- mutate(LRF_tour_results,
                               outPeriod = case_when(end_hour <=  5 ~ "EA",
                                                     end_hour <= 10 ~ "AM",
                                                     end_hour <= 15 ~ "MD",
                                                     end_hour <= 19 ~ "PM",
                                                     end_hour  > 19 ~ "EV"),
                               inPeriod = case_when(start_hour <=  5 ~ "EA",
                                                    start_hour <= 10 ~ "AM",
                                                    start_hour <= 15 ~ "MD",
                                                    start_hour <= 19 ~ "PM",
                                                    start_hour  > 19 ~ "EV"))
LRF_walk  <- subset(LRF_tour_results, subset=tour_mode==10)
LRF_drive <- subset(LRF_tour_results, subset=tour_mode==15)

# WALK ----
# check ferry availability - outbound
LRF_walk <- left_join(LRF_walk, subset(ferry_skim, subset=submode=="wlk_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "outPeriod"="timeperiod") ) %>% 
  mutate(outFerryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)
# check ferry availability - inbound
LRF_walk <- left_join(LRF_walk, subset(ferry_skim, subset=submode=="wlk_lrf_wlk"),
                      by=c("orig_taz"="DTAZ", "dest_taz"="OTAZ", "inPeriod"="timeperiod") ) %>% 
  mutate(inFerryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)

LRF_walk <- mutate(LRF_walk, ferryAvailable=ifelse((inFerryAvailable==1)&(outFerryAvailable==1),1,0)) %>% 
  mutate(trn_submode=ifelse(ferryAvailable==1,"Ferry-Walk","LRT-Walk")) %>%
  select(-outFerryAvailable, -inFerryAvailable, -ferryAvailable, -lrf_submode, -inPeriod, -outPeriod)

# DRIVE ----
# check ferry availability - outbound
LRF_drive <- left_join(LRF_drive, subset(ferry_skim, subset=submode=="drv_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "outPeriod"="timeperiod") ) %>% 
  mutate(outFerryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)
# check ferry availability - inbound
LRF_drive <- left_join(LRF_drive, subset(ferry_skim, subset=submode=="wlk_lrf_drv"),
                      by=c("orig_taz"="DTAZ", "dest_taz"="OTAZ", "inPeriod"="timeperiod") ) %>% 
  mutate(inFerryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)

LRF_drive <- mutate(LRF_drive, ferryAvailable=ifelse((inFerryAvailable==1)&(outFerryAvailable==1),1,0)) %>% 
  mutate(trn_submode=ifelse(ferryAvailable==1,"Ferry-Drive","LRT-Drive")) %>%
  select(-outFerryAvailable, -inFerryAvailable, -ferryAvailable, -lrf_submode, -inPeriod, -outPeriod)

# put them back together
transit_tour_results <- rbind(nonLRF_tour_results, LRF_walk, LRF_drive)

# summarize to "auto_sufficiency", indiv_joint, tour purpose and TRANSIT tour mode
trn_tour_summary <- group_by(transit_tour_results, auto_suff, indiv_joint, tour_purpose, trn_submode) %>% 
  summarise(num_tours=sum(num_participants)) %>%
  mutate(num_tours=num_tours/SAMPLESHARE)

# move auto_sufficiency to columns
trn_tour_summary_spread <- spread(trn_tour_summary, key=auto_suff, value=num_tours)

# reorder
trn_tour_summary_spread <- trn_tour_summary_spread[c("indiv_joint","tour_purpose","trn_submode",
                                                     "Autos=0","Autos<Workers","Autos>=Workers")]
# fillNA
trn_tour_summary_spread[is.na(trn_tour_summary_spread)] <- 0


# save it
outfile <- file.path(OUTPUT_DIR, paste0("11_tour_mode_choice_trnsubmode_TM.csv"))
write.table(trn_tour_summary_spread, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")