library(dplyr)
library(tidyr)
options(java.parameters = "-Xmx8000m")  # xlsx uses java and can run out of memory
library(xlsx)

# For RStudio, these can be set in the .Rprofile
TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling

WORKBOOK       <- "M:\\Development\\Travel Model One\\Calibration\\Version 1.5.0\\15 Trip Mode Choice\\15_TripModeChoice.xlsx"
WORKBOOK_BLANK <- gsub(".xlsx","_blank.xlsx",WORKBOOK)
WORKBOOK_TEMP  <- gsub(".xlsx","_temp.xlsx", WORKBOOK)
calib_workbook <- loadWorkbook(file=WORKBOOK_BLANK)
calib_sheets   <- getSheets(calib_workbook)

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, "OUTPUT", "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

cat("TARGET_DIR  = ",TARGET_DIR, "\n")
cat("ITER        = ",ITER,       "\n")
cat("SAMPLESHARE = ",SAMPLESHARE,"\n")


# read ferry skims because the only way to separate ferry tours from light rail tours is with ferry availability :p
# generated by extract_skim_table.job
table      <- "ivtFerry"
ferry_skim <- data.frame()
for (timeperiod in c("EA","AM","MD", "PM", "EV")) {
  for (submode in c("wlk_lrf_wlk","drv_lrf_wlk","wlk_lrf_drv")) {
    skim_table <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", paste0("trnskm",timeperiod,"_",submode,"_",table,".csv")),
                             header=FALSE, col.names=c("OTAZ","DTAZ","ones",table), sep=",") %>% 
      select(-ones) %>%
      mutate(timeperiod=timeperiod, submode=submode)
    ferry_skim <- rbind(ferry_skim, skim_table)
  }
}
remove(skim_table)

indiv_trip_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("indivTripData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(inbound, tour_purpose, tour_mode, trip_mode, depart_hour, orig_taz, dest_taz) %>% 
  mutate(num_participants=1, indiv_joint="indiv")

joint_trip_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("jointTripData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(inbound, num_participants, tour_purpose, tour_mode, trip_mode, depart_hour, orig_taz, dest_taz) %>%
  mutate(indiv_joint="joint")

# put individual and joint trips together
trip_results <- rbind(indiv_trip_results, joint_trip_results)
n_trip_results <- nrow(trip_results)


# split into Light-Rail/Ferry and non Light Rail Ferry to check if ferry avaiable for light rail/ferry
LRF_trip_results    <- subset(trip_results, (trip_mode==10)|(trip_mode==15))
nonLRF_trip_results <- subset(trip_results, (trip_mode!=10)&(trip_mode!=15)) %>% mutate(ferryAvailable=0)

# to distinguish between LRT and Ferry, we need to look at availability
LRF_trip_results     <- mutate(LRF_trip_results,
                               timeperiod = case_when(depart_hour <=  5 ~ "EA",
                                                      depart_hour <= 10 ~ "AM",
                                                      depart_hour <= 15 ~ "MD",
                                                      depart_hour <= 19 ~ "PM",
                                                      depart_hour  > 19 ~ "EV"))
LRF_walk      <- subset(LRF_trip_results, subset=trip_mode==10)
LRF_drive_out <- subset(LRF_trip_results, subset=(trip_mode==15)&(inbound==0))
LRF_drive_in  <- subset(LRF_trip_results, subset=(trip_mode==15)&(inbound==1))


# check ferry availability
LRF_walk <- left_join(LRF_walk, subset(ferry_skim, subset=submode=="wlk_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode, -timeperiod)

LRF_drive_out <- left_join(LRF_drive_out, subset(ferry_skim, subset=submode=="drv_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode, -timeperiod)

LRF_drive_in <- left_join(LRF_drive_in, subset(ferry_skim, subset=submode=="wlk_lrf_drv"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode, -timeperiod)

LRF_trip_results <- rbind(LRF_walk, LRF_drive_out, LRF_drive_in)

trip_results <- rbind(nonLRF_trip_results, LRF_trip_results)
cat("n_trip_results = ",n_trip_results,"\n")
cat("nrow(trip_results) = ",nrow(trip_results),"\n")
# stopifnot(n_trip_results == nrow(trip_results))

# create special trip mode for ferry
trip_results <- mutate(trip_results, trip_mode=ifelse(ferryAvailable==1,-trip_mode,trip_mode))

# summarize to tour purose, tour mode, trip mode
trip_summary <- group_by(trip_results, indiv_joint, tour_purpose, tour_mode, trip_mode) %>% 
  summarise(num_trips=sum(num_participants)) %>%
  mutate(num_trips=num_trips/SAMPLESHARE)


# save it
outfile <- file.path(OUTPUT_DIR, paste0("15_trip_mode_choice_TM.csv"))
write.table(trip_summary, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")

addDataFrame(as.data.frame(trip_summary), calib_sheets$modeldata, startRow=2, startColumn=1, row.names=FALSE)

saveWorkbook(calib_workbook, WORKBOOK_TEMP)
forceFormulaRefresh(WORKBOOK_TEMP, WORKBOOK, verbose=TRUE)
cat("Wrote ",WORKBOOK,"\n")