library(dplyr)
library(tidyr)
options(java.parameters = "-Xmx8000m")  # xlsx uses java and can run out of memory
library(xlsx)

# For RStudio, these can be set in the .Rprofile
TARGET_DIR   <- Sys.getenv("TARGET_DIR")  # The location of the input files
ITER         <- Sys.getenv("ITER")        # The iteration of model outputs to read
SAMPLESHARE  <- Sys.getenv("SAMPLESHARE") # Sampling

TAZ_SD_FILE    <- "X:\\travel-model-one-calibration\\utilities\\geographies\\taz-superdistrict-county.csv"
WORKBOOK       <- "M:\\Development\\Travel Model One\\Calibration\\Version 1.5.0\\15 Trip Mode Choice\\15_TripModeChoice.xlsx"
WORKBOOK_BLANK <- gsub(".xlsx","_blank.xlsx",WORKBOOK)
WORKBOOK_TEMP  <- gsub(".xlsx","_temp.xlsx", WORKBOOK)
calib_workbook <- loadWorkbook(file=WORKBOOK_BLANK)
calib_sheets   <- getSheets(calib_workbook)

TARGET_DIR   <- gsub("\\\\","/",TARGET_DIR) # switch slashes around
TAZ_SD_FILE  <- gsub("\\\\","/",TAZ_SD_FILE) # switch slashes around
OUTPUT_DIR   <- file.path(TARGET_DIR, "OUTPUT", "calibration")
if (!file.exists(OUTPUT_DIR)) { dir.create(OUTPUT_DIR) }

stopifnot(nchar(TARGET_DIR  )>0)
stopifnot(nchar(ITER        )>0)
stopifnot(nchar(SAMPLESHARE )>0)

SAMPLESHARE <- as.numeric(SAMPLESHARE)

cat("TARGET_DIR  = ",TARGET_DIR, "\n")
cat("ITER        = ",ITER,       "\n")
cat("SAMPLESHARE = ",SAMPLESHARE,"\n")


# read ferry skims because the only way to separate ferry tours from light rail tours is with ferry availability :p
# generated by extract_skim_table.job
table      <- "ivtFerry"
ferry_skim <- data.frame()
for (timeperiod in c("EA","AM","MD", "PM", "EV")) {
  for (submode in c("wlk_lrf_wlk","drv_lrf_wlk","wlk_lrf_drv")) {
    skim_table <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", paste0("trnskm",timeperiod,"_",submode,"_",table,".csv")),
                             header=FALSE, col.names=c("OTAZ","DTAZ","ones",table), sep=",") %>% 
      select(-ones) %>%
      mutate(timeperiod=timeperiod, submode=submode)
    ferry_skim <- rbind(ferry_skim, skim_table)
  }
}
remove(skim_table)

indiv_trip_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("indivTripData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(inbound, tour_purpose, tour_mode, trip_mode, depart_hour, orig_taz, dest_taz) %>% 
  mutate(num_participants=1, indiv_joint="indiv")

joint_trip_results   <- read.table(file=file.path(TARGET_DIR,"OUTPUT","main",paste0("jointTripData_",ITER,".csv")),
                                   header=TRUE, sep=",") %>% 
  select(inbound, num_participants, tour_purpose, tour_mode, trip_mode, depart_hour, orig_taz, dest_taz) %>%
  mutate(indiv_joint="joint")

# put individual and joint trips together
trip_results <- rbind(indiv_trip_results, joint_trip_results)
n_trip_results <- nrow(trip_results)

# add time period to trip results
trip_results <- mutate(trip_results,
                       timeperiod = case_when(depart_hour <=  5 ~ "EA",
                                              depart_hour <= 10 ~ "AM",
                                              depart_hour <= 15 ~ "MD",
                                              depart_hour <= 19 ~ "PM",
                                              depart_hour  > 19 ~ "EV"))

# split into Light-Rail/Ferry and non Light Rail Ferry to check if ferry avaiable for light rail/ferry
LRF_trip_results    <- subset(trip_results, (trip_mode==10)|(trip_mode==15))
nonLRF_trip_results <- subset(trip_results, (trip_mode!=10)&(trip_mode!=15)) %>% mutate(ferryAvailable=0)

# to distinguish between LRT and Ferry, we need to look at availability
LRF_walk      <- subset(LRF_trip_results, subset=trip_mode==10)
LRF_drive_out <- subset(LRF_trip_results, subset=(trip_mode==15)&(inbound==0))
LRF_drive_in  <- subset(LRF_trip_results, subset=(trip_mode==15)&(inbound==1))


# check ferry availability
LRF_walk <- left_join(LRF_walk, subset(ferry_skim, subset=submode=="wlk_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)

LRF_drive_out <- left_join(LRF_drive_out, subset(ferry_skim, subset=submode=="drv_lrf_wlk"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)

LRF_drive_in <- left_join(LRF_drive_in, subset(ferry_skim, subset=submode=="wlk_lrf_drv"),
                      by=c("orig_taz"="OTAZ", "dest_taz"="DTAZ", "timeperiod"="timeperiod") ) %>% 
  mutate(ferryAvailable=ifelse(is.na(ivtFerry),0,1)) %>%
  select(-ivtFerry, -submode)

LRF_trip_results <- rbind(LRF_walk, LRF_drive_out, LRF_drive_in)

trip_results <- rbind(nonLRF_trip_results, LRF_trip_results)
cat("n_trip_results = ",n_trip_results,"\n")
cat("nrow(trip_results) = ",nrow(trip_results),"\n")
# stopifnot(n_trip_results == nrow(trip_results))

# create special trip mode for ferry
trip_results <- mutate(trip_results, trip_mode=ifelse(ferryAvailable==1,-trip_mode,trip_mode))

# summarize to tour purose, tour mode, trip mode
trip_summary <- group_by(trip_results, indiv_joint, tour_purpose, tour_mode, trip_mode) %>% 
  summarise(num_trips=sum(num_participants)) %>%
  mutate(num_trips=num_trips/SAMPLESHARE)

# save it
outfile <- file.path(OUTPUT_DIR, paste0("15_trip_mode_choice_TM.csv"))
write.table(trip_summary, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")

addDataFrame(as.data.frame(trip_summary), calib_sheets$modeldata, startRow=2, startColumn=1, row.names=FALSE)

# transit district-to-district
transit_trip_results  <- subset(trip_results, subset=((trip_mode<0)|((trip_mode>=9)&(trip_mode<=18)))) %>%
  mutate(trn_submode=case_when(trip_mode==-15 ~"Ferry",
                               trip_mode==-10 ~"Ferry",
                               trip_mode== 9 ~ "Local",
                               trip_mode==10 ~ "LRT",
                               trip_mode==11 ~ "Express",
                               trip_mode==12 ~ "HeavyRail",
                               trip_mode==13 ~ "CommRail",
                               trip_mode==14 ~ "Local",
                               trip_mode==15 ~ "LRT",
                               trip_mode==16 ~ "Express",
                               trip_mode==17 ~ "HeavyRail",
                               trip_mode==18 ~ "CommRail"))
transit_trip_results$acc = "Not Set"
transit_trip_results$egr = "Not Set"

# wlk wlk
transit_trip_results$acc[which((transit_trip_results$trip_mode>=9)&(transit_trip_results$trip_mode<=13))] <- "wlk"
transit_trip_results$egr[which((transit_trip_results$trip_mode>=9)&(transit_trip_results$trip_mode<=13))] <- "wlk"
transit_trip_results$acc[which(transit_trip_results$trip_mode==-10)] <- "wlk"
transit_trip_results$egr[which(transit_trip_results$trip_mode==-10)] <- "wlk"

# outbound: drv wlk
transit_trip_results$acc[which((transit_trip_results$inbound==0)&
                                 (transit_trip_results$trip_mode>=14)&
                                 (transit_trip_results$trip_mode<=18))]  <- "drv"
transit_trip_results$egr[which((transit_trip_results$inbound==0)&
                                 (transit_trip_results$trip_mode>=14)&
                                 (transit_trip_results$trip_mode<=18))]  <- "wlk"
transit_trip_results$acc[which((transit_trip_results$inbound==0)&
                                 (transit_trip_results$trip_mode==-15))] <- "drv"
transit_trip_results$egr[which((transit_trip_results$inbound==0)&
                                 (transit_trip_results$trip_mode==-15))] <- "wlk"

# inbound: wlk drv
transit_trip_results$acc[which((transit_trip_results$inbound==1)&
                                 (transit_trip_results$trip_mode>=14)&
                                 (transit_trip_results$trip_mode<=18))]  <- "wlk"
transit_trip_results$egr[which((transit_trip_results$inbound==1)&
                                 (transit_trip_results$trip_mode>=14)&
                                 (transit_trip_results$trip_mode<=18))]  <- "drv"
transit_trip_results$acc[which((transit_trip_results$inbound==1)&
                                 (transit_trip_results$trip_mode==-15))] <- "wlk"
transit_trip_results$egr[which((transit_trip_results$inbound==1)&
                                 (transit_trip_results$trip_mode==-15))] <- "drv"

# combine purposes
transit_trip_results <- mutate(transit_trip_results,
                               simple_purpose=case_when(
                                 tour_purpose=="atwork_business" ~ "atwork",
                                 tour_purpose=="atwork_eat"      ~ "atwork",
                                 tour_purpose=="atwork_maint"    ~ "atwork",
                                 tour_purpose=="eatout"          ~ "ind_disc",
                                 tour_purpose=="escort_kids"     ~ "ind_maint",
                                 tour_purpose=="escort_no kids"  ~ "ind_maint",
                                 tour_purpose=="othdiscr"        ~ "ind_disc",
                                 tour_purpose=="othmaint"        ~ "ind_maint",
                                 tour_purpose=="school_grade"    ~ "school",
                                 tour_purpose=="school_high"     ~ "school",
                                 tour_purpose=="shopping"        ~ "ind_maint",
                                 tour_purpose=="social"          ~ "ind_disc",
                                 tour_purpose=="university"      ~ "university",
                                 tour_purpose=="work_high"       ~ "work",
                                 tour_purpose=="work_low"        ~ "work",
                                 tour_purpose=="work_med"        ~ "work",
                                 tour_purpose=="work_very high"  ~ "work"))

# add boards
transit_trip_results$num_boards <- NA
table <- "boards"
print(paste("Have ", nrow(subset(transit_trip_results, !is.na(transit_trip_results$num_boards))),
            "boards counts of",nrow(transit_trip_results)))

for (timeperiod in c("EA","AM","MD", "PM", "EV")) {
  for (trn_submode in c("Local","Express","LRT","Ferry","HeavyRail","CommRail")) {
    submode <- case_when(trn_submode=="Local"    ~ "loc",
                         trn_submode=="Express"  ~ "exp",
                         trn_submode=="LRT"      ~ "lrf",
                         trn_submode=="Ferry"    ~ "lrf",
                         trn_submode=="HeavyRail"~ "hvy",
                         trn_submode=="CommRail" ~ "com")
    for (acc_egr in c("wlk_wlk","drv_wlk","wlk_drv")) {
      acc <- substr(acc_egr,0,3)
      egr <- substr(acc_egr,5,7)
      
      file_name <- paste0("trnskm",timeperiod,"_",acc,"_",submode,"_",egr,"_",table,".csv")
      skim_table <- read.table(file=file.path(TARGET_DIR, "OUTPUT", "skims", file_name),
                               header=FALSE, col.names=c("orig_taz","dest_taz","ones",table), sep=",") %>% 
      select(-ones) %>%
      mutate(timeperiod=timeperiod, trn_submode=trn_submode,acc=acc,egr=egr)
      # print(paste("Read ",file_name))
      # print(head(skim_table))
      transit_trip_results <- left_join(transit_trip_results, skim_table,
                                        by = c("orig_taz", "dest_taz", "timeperiod", "trn_submode", "acc", "egr"))
      # set num_boards
      transit_trip_results <- mutate(transit_trip_results, 
                                     num_boards=ifelse(!is.na(boards),boards,num_boards))
      
      transit_trip_results <- select(transit_trip_results, -boards)
      board_num_count      <- nrow(subset(transit_trip_results, !is.na(transit_trip_results$num_boards)))
      print(paste("=> Have board counts for", sprintf("%.1f%%", 100*board_num_count/nrow(transit_trip_results))))
    }
  }
}
missing_boards <- subset(transit_trip_results, is.na(transit_trip_results$num_boards))
print(paste("Have ",nrow(missing_boards),"rows without board counts"))

# want walk access&egress, drive access or egress
transit_trip_results <- mutate(transit_trip_results, acc_egr=ifelse((acc=="drv")|(egr=="drv"),"2_Drive","1_Walk"))

# plus a Total category
transit_trip_results <- rbind(transit_trip_results,
                              mutate(transit_trip_results, acc_egr="0_Total"))

# group by trn_submode, acc_egr, num_boards and spread
transit_boards_summary <- group_by(subset(transit_trip_results, !is.na(transit_trip_results$num_boards)),
                                   trn_submode, acc_egr, num_boards) %>%
  summarise(num_trips=sum(num_participants)) %>%
  mutate(num_trips=num_trips/SAMPLESHARE)

# assuming no 5- and 6-boards
transit_boards_summary <- as.data.frame(transit_boards_summary)
if (nrow(subset(transit_boards_summary, num_boards==5)) == 0) {
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="0_Total", num_boards=5, num_trips=0)
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="1_Walk",  num_boards=5, num_trips=0)
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="2_Drive", num_boards=5, num_trips=0)
}
if (nrow(subset(transit_boards_summary, num_boards==6)) == 0) {
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="0_Total", num_boards=6, num_trips=0)
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="1_Walk",  num_boards=6, num_trips=0)
  transit_boards_summary <- add_row(transit_boards_summary, trn_submode="CommRail", acc_egr="2_Drive", num_boards=6, num_trips=0)
}

transit_boards_summary <- spread(transit_boards_summary, trn_submode, num_trips)
transit_boards_summary <- as.data.frame(transit_boards_summary) %>% 
  replace_na(list("Local"=0, "Express"=0,"Ferry"=0,"LRT"=0,"CommRail"=0,"HeavyRail"=0))
transit_boards_summary <- transit_boards_summary[c("num_boards","Local","Express","Ferry","LRT","HeavyRail","CommRail","acc_egr")]

# save it
outfile <- file.path(OUTPUT_DIR, paste0("15_trip_mode_choice_trn_boards_TM.csv"))
write.table(transit_boards_summary, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")

addDataFrame(transit_boards_summary, calib_sheets$modeldata, startRow=2, startColumn=17, row.names=FALSE)


# add superdistrict for orig, dest
taz_sd <- read.table(file = TAZ_SD_FILE, header=TRUE, sep=",")
transit_trip_results <- left_join(transit_trip_results, 
                          select(taz_sd, ZONE, SD_NAME) %>% rename(orig_taz=ZONE, orig_SD=SD_NAME))
transit_trip_results <- left_join(transit_trip_results, 
                          select(taz_sd, ZONE, SD_NAME) %>% rename(dest_taz=ZONE, dest_SD=SD_NAME))

transit_trip_results <- rbind(transit_trip_results,
                      data.frame(transit_trip_results) %>% mutate(simple_purpose="Total"), # all purposes
                      data.frame(transit_trip_results) %>% mutate(trn_submode="Total"),    # all submodes
                      data.frame(transit_trip_results) %>% mutate(simple_purpose="Total",  # both
                                                                  trn_submode="Total")
)

trn_trip_summary <- group_by(transit_trip_results, simple_purpose, trn_submode, orig_SD, dest_SD) %>% 
  summarise(num_trips=sum(num_participants)) %>%
  mutate(num_trips=num_trips/SAMPLESHARE)

trn_trip_summary <- as.data.frame(trn_trip_summary) %>% 
  mutate(key=paste(trn_submode, orig_SD, dest_SD, simple_purpose, sep="-"))

trn_trip_summary <- trn_trip_summary[c("key","trn_submode","orig_SD","dest_SD","simple_purpose","num_trips")]

# save it
outfile <- file.path(OUTPUT_DIR, paste0("15_trip_mode_choice_trn_ODdist_TM.csv"))
write.table(trn_trip_summary, outfile, sep=",", row.names=FALSE)
cat("Wrote ",outfile,"\n")

addDataFrame(trn_trip_summary, calib_sheets$modeldata, startRow=2, startColumn=10, row.names=FALSE)

saveWorkbook(calib_workbook, WORKBOOK_TEMP)
forceFormulaRefresh(WORKBOOK_TEMP, WORKBOOK, verbose=TRUE)
cat("Wrote ",WORKBOOK,"\n")