---
title: "Rebuild TAZ Data with New ABAG Employment Estimates"
author: "David Ory"
output: 
  html_document:
    theme: cosmo
    toc: yes
---


## Administration

#### Purpose
ABAG is moving forward with a new definition of employment.  This script incorporates the new employment estimates into the previous TAZ data versions. 

#### Outputs
1.  A CSV database of TAZ data per: http://analytics.mtc.ca.gov/foswiki/Main/TazData

## Procedure

#### Overhead
```{r overhead, results = 'hide'}
library(knitr)
suppressMessages(library(dplyr))
library(stringr)
```

```{r config, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

#### Remote I/O
```{r remote-io}
F_NEW_EMPLOYMENT = "M:/Data/ABAGProjections/2015/2015 09 10 Revisions to historical/tazproportionrev_091015.csv"

F_2000_TAZ = "M:/Development/Travel Model One/Version 04/2000_04_XXX/OUTPUT/tazData.csv"

F_2005_TAZ = "M:/Development/Travel Model One/Version 04/2005_04_YYY/OUTPUT/tazData.csv"

F_2010_TAZ = "M:/Development/Travel Model One/Version 04/2010_04_ZZZ/OUTPUT/tazData.csv"

OUTPUT_DIR <- "M:/Application/Model One/Zonal Data/Revised Historical/2015 09 11/"

F_2000_OUTPUT = paste(OUTPUT_DIR, "tazData_2000.csv", sep = "")

F_2005_OUTPUT = paste(OUTPUT_DIR, "tazData_2005.csv", sep = "")

F_2010_OUTPUT = paste(OUTPUT_DIR, "tazData_2010.csv", sep = "")
```

#### Data reads
```{r data-reads}
abag_emp_df <- read.table(file = F_NEW_EMPLOYMENT, header = TRUE, sep = ",", stringsAsFactors = FALSE)

taz_2000_df <- read.table(file = F_2000_TAZ, header = TRUE, sep = ",", stringsAsFactors = FALSE)

taz_2005_df <- read.table(file = F_2005_TAZ, header = TRUE, sep = ",", stringsAsFactors = FALSE)

taz_2010_df <- read.table(file = F_2010_TAZ, header = TRUE, sep = ",", stringsAsFactors = FALSE)

```

#### Data manipulation
```{r data-manipulation}
# Prepare the ABAG data
abag_df <- abag_emp_df %>%
  select(year, ZONE = zone, 
         TOTEMP  = totemBLSe3, 
         RETEMPN = retemBLSe3, 
         FPSEMPN = fpsemBLSe3, 
         HEREMPN = heremBLSe3,
         OTHEMPN = othemBLSe3,
         AGREMPN = agremBLSe3,
         MWTEMPN = mwtemBLSe3)

abag_df <- abag_df %>%
  mutate(TOTEMP  = round(TOTEMP)) %>%
  mutate(RETEMPN = round(RETEMPN)) %>%
  mutate(FPSEMPN = round(FPSEMPN)) %>%
  mutate(HEREMPN = round(HEREMPN)) %>%
  mutate(OTHEMPN = round(OTHEMPN)) %>%
  mutate(AGREMPN = round(AGREMPN)) %>%
  mutate(MWTEMPN = round(MWTEMPN))

abag_2005_df <- abag_df %>%
  filter(year == 2005) %>%
  select(-year)

abag_2010_df <- abag_df %>%
  filter(year == 2010) %>%
  select(-year)

# Prepare the TAZ data

# 2000
# TODO: pending ABAG update 

# 2005
taz_2005_out <- taz_2005_df %>%
  select(-AVGINCQ1, -AVGINCQ2, -AVGINCQ3, -AVGINCQ4, -AVGHHINC,
         -TOTEMP, -RETEMPN, -FPSEMPN, -HEREMPN, -OTHEMPN, -AGREMPN, -MWTEMPN)
taz_2005_out <- left_join(taz_2005_out, abag_2005_df, by = c("ZONE"))

# 2010
taz_2010_out <- taz_2010_df %>%
  select(-TOTEMP, -RETEMPN, -FPSEMPN, -HEREMPN, -OTHEMPN, -AGREMPN, -MWTEMPN)
taz_2010_out <- left_join(taz_2010_out, abag_2010_df, by = c("ZONE"))
  
```

#### Data writes
```{r data-writes}
# write.csv(taz_2000_out, file = F_2000_OUTPUT, row.names = FALSE, quote = F)
write.csv(taz_2005_out, file = F_2005_OUTPUT, row.names = FALSE, quote = F)
write.csv(taz_2010_out, file = F_2010_OUTPUT, row.names = FALSE, quote = F)
```

#### De-bug
```{r debug}
#sum(taz_2000_out$TOTEMP)
#sum(taz_2000_df$TOTEMP)

sum(taz_2005_out$TOTEMP)
sum(taz_2005_df$TOTEMP)

sum(taz_2010_out$TOTEMP)
sum(taz_2010_df$TOTEMP)

```

