---
title: "Trip Distance by Mode, Tour Purpose, Origin Superdistrict, Destination Superdistrict"
author: "David Ory"
output: 
  html_document:
    theme: cosmo
    toc: yes
---


## Administration

#### Purpose
Prepares a bespoke summary of travel model output.  Specifically, calculates the average trip length by travel mode, tour purpose, origin superdistrict, and destination superdistrict. 

#### Outputs
1.  A CSV database with logical names.  

## Procedure

#### Overhead
```{r overhead, results = 'hide'}
library(knitr)
suppressMessages(library(dplyr))
```

```{r config, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

#### Mode look-up table
```{r mode-lookup}
LOOKUP_MODE <- data.frame(trip_mode = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18),
                          mode_name = c("Drive alone - free", "Drive alone - pay", 
                                        "Shared ride two - free", "Shared ride two - pay",
                                        "Shared ride three - free", "Shared ride three - pay",
                                        "Walk", "Bike",
                                        "Walk  to local bus", "Walk to light rail or ferry", "Walk to express bus", 
                                        "Walk to heavy rail", "Walk to commuter rail",
                                        "Drive  to local bus", "Drive to light rail or ferry", "Drive to express bus", 
                                        "Drive to heavy rail", "Drive to commuter rail"))

# SAMPLING_RATE = 1.00
SAMPLING_RATE = 0.500

```


#### Remote file locations
```{r remote-dir}
TARGET_DIR  <- "M:/Application/Model One/RTP2017/Scenarios/2040_06_694/OUTPUT/"
OUTPUT_DIR  <- "M:/Application/Model One/RTP2017/Scenarios/2040_06_694/OUTPUT/bespoke/"

```


#### Load, join, compute
```{r data-manips}
# Load
load(paste(TARGET_DIR, "updated_output/", "trips.rdata", sep = ""))
zonal_df <- read.table(file = paste(TARGET_DIR, "tazData.csv", sep = ""), header=TRUE, sep=",")

# Select and join
working <- trips %>%
  select(hh_id, tour_purpose, distance, trip_mode, orig_taz, dest_taz)

origin <- zonal_df %>%
  select(orig_taz = ZONE, orig_sd = SD)

destination <- zonal_df %>%
  select(dest_taz = ZONE, dest_sd = SD)

output <- left_join(working, origin, by = c("orig_taz"))
output <- left_join(output, destination, by = c("dest_taz"))

# Reduce
summarized <- output %>%
  group_by(trip_mode, tour_purpose, orig_sd, dest_sd) %>%
  summarize(simulated_trips = n(), mean_distance = mean(distance))

summarized <- left_join(summarized, LOOKUP_MODE, by = c("trip_mode"))

summarized <- summarized %>%
  mutate(estimated_trips = simulated_trips / SAMPLING_RATE) %>%
  select(trip_mode, mode_name, tour_purpose, orig_sd, dest_sd, simulated_trips, estimated_trips, mean_distance)

```

#### Write to disk
```{r write-disk}
F_OUTPUT = paste(OUTPUT_DIR, "trip-distance-by-mode-superdistrict.csv", sep = "")
write.csv(summarized, file = F_OUTPUT, row.names = FALSE, quote = F)
```


