# -------------------------------------------------------------------------
# Analysis to inform the implementation of a "pseudo monthly toll cap" strategy
# Specifically, this script looks at the toll trip frequency of toll road users.
#
# input:   
# %TARGET_DIR%\updated_output\trips_with_detailed_cost.rdata
# (generated by travel-model-one/utilities/NextGenFwys/metrics/travel-cost-by-income-driving-households.r)
#
# -------------------------------------------------------------------------

library(dplyr)
library(knitr) # for the kable function that creates well-formatted tables 

# ------------------------------------------
# read inputs
# ------------------------------------------
# look at the scenario in Round 1: All Lane Tolling + Transit 
# it has Means_Based_Tolling_Q1Factor  = 1, so it's probably closest to what we'll have for Round 2
TARGET_DIR="//model3-a/Model3A-Share/Projects/2035_TM152_NGF_NP10_Path1a_02"

# another Round 1 scenario is: All Lane Tolling + Affordability Focus
# it has Means_Based_Tolling_Q1Factor  = 0.5 
# (note that in Round 2, in pathways where we have monthly toll cap, we won't have toll discount, so Path1a in Round 1 is a better choice for this analysis)
# TARGET_DIR="//MODEL3-B/Model3B-Share/Projects/2035_TM152_NGF_NP10_Path1b_02"

detailedCost_file <- file.path(TARGET_DIR, "updated_output", "trips_with_detailed_cost.rdata")
load(detailedCost_file)

# ------------------------------------------
# Preprocessing 
# ------------------------------------------

# The dataframe already has a name - it's trips
# Rename dataframe with a df_ prefix to make it easier to remember it is a data frame
df_tripCosts <- trips
rm(trips)

# Note that the input file trips_with_detailed_cost.rdata is a 50% sample
SAMPLESHARE  <- 0.5

#from topsheet
total_population <- 9002950


# ------------------------------------------
# Translate the monthly toll caps to a daily toll cap
# ------------------------------------------

# Anticipated monthly toll cap
# Monthly cap of $30 for Q1
# Monthly cap of $60 for 50 to 80% AMI (first 60% of Q2)

# Focus on the first element (toll cap for Q1) for now, in this concept development phase
# Converting $30 per month to a cap per day
# assume 260 work days in a year 
# minus 10 days of sick/vacation, so 250 days

# in today's prices
DailyTollCap_today=30*12/250
# i.e. $1.44 in today's prices - that seems pretty low?

# Using a conversion rate of 1.87 from https://github.com/BayAreaMetro/modeling-website/wiki/InflationAssumptions
DailyTollCap=DailyTollCap_today/1.87
print(paste("The daily toll cap in 2000$ =", DailyTollCap))
# the result using the initial assumptions is $0.77 in 2000$
# these are just initial assumptions - to be discussed


#-----------------------------------------------
# Convert data frame to person level
#-----------------------------------------------

df_personCosts <- df_tripCosts %>%
  group_by(person_id) %>%
  summarise(
    hhld_incQ               = first(incQ),
    hhld_incQ_label         = first(incQ_label),
    hhld_income             = first(income),
    hhld_autos              = first(autos),
    home_taz                = first(home_taz),
    hhld_travel             = first(hhld_travel),
    hhld_trips              = first(hhld_trips),
    hhld_auto_seg_trips     = first(hhld_auto_seg_trips),
    hhld_transit_seg_trips  = first(hhld_transit_seg_trips),
    person_numtrips         = n(),
    person_parking_cost     = sum(totalParkingCost, na.rm = TRUE),
    person_auto_op_cost     = sum(auto_op_cost, na.rm = TRUE),
    person_bridge_toll      = sum(bridge_toll, na.rm = TRUE),
    person_cordon_toll      = sum(cordon_toll, na.rm = TRUE),
    person_value_toll       = sum(value_toll, na.rm = TRUE),
    person_fare             = sum(fare, na.rm = TRUE),
    person_drv_trn_op_cost  = sum(drv_trn_op_cost, na.rm = TRUE),
    person_taxitnc_cost     = sum(taxitnc_cost, na.rm = TRUE)
  )

# it takes a while to generate the person level file

# Get the number of cases
num_person <- nrow(df_personCosts)
print(paste("Number of persons who made at least one trip in the simulated day =", num_person))
# results: about 4m in the "all persons" universe
# this 2035 scenario should have about 9m people
# more than half of the people didn't travel in the simulated day? hmm. it seems low. but I double check this with the trips.rdata file


#-----------------------------------------------
# Create a universe of just toll trips
#-----------------------------------------------
df_filteredtripCosts <- df_tripCosts %>%
   filter(value_toll > 0)


#-----------------------------------------------
# Convert the toll trip data frame to a person level data frame 
# Essentially a data frame of toll road users
#-----------------------------------------------

df_tollRoadUsers <- df_filteredtripCosts %>%
  group_by(person_id) %>%
  summarise(
    hhld_incQ               = first(incQ),
    hhld_incQ_label         = first(incQ_label),
    hhld_income             = first(income),
    hhld_autos              = first(autos),
    home_taz                = first(home_taz),
    hhld_travel             = first(hhld_travel),
    hhld_trips              = first(hhld_trips),
    hhld_auto_seg_trips     = first(hhld_auto_seg_trips),
    hhld_transit_seg_trips  = first(hhld_transit_seg_trips),
    person_numtrips         = n(),
    person_parking_cost     = sum(totalParkingCost, na.rm = TRUE),
    person_auto_op_cost     = sum(auto_op_cost, na.rm = TRUE),
    person_bridge_toll      = sum(bridge_toll, na.rm = TRUE),
    person_cordon_toll      = sum(cordon_toll, na.rm = TRUE),
    person_value_toll       = sum(value_toll, na.rm = TRUE),
    person_fare             = sum(fare, na.rm = TRUE),
    person_drv_trn_op_cost  = sum(drv_trn_op_cost, na.rm = TRUE),
    person_taxitnc_cost     = sum(taxitnc_cost, na.rm = TRUE)
  )

# it takes a while to generate the person level file

# Get the number of cases
num_tollRoadUsers <- nrow(df_tollRoadUsers)
print(paste("Number of persons who made at least one toll trip in the simulated day =", num_tollRoadUsers))


#-----------------------------------------------
# Focus on persons in Q1 households
#-----------------------------------------------
df_Q1tollRoadUsers <- df_tollRoadUsers %>%
  filter(hhld_incQ==1)

# report number of cases
num_Q1tollRoadUsers <- nrow(df_Q1tollRoadUsers)
print(paste("Number of persons in Q1 households who made at least one toll trip in the simulated day =", num_Q1tollRoadUsers))
# results: much less than the definition of "quartile" - may be lower income people travel less?


# ------------------------------------------
# How many Q1 persons pay more than the toll cap
# ------------------------------------------

# create a data frame of persons that pay more than the toll cap
df_Q1tollRoadUsersPayMoreThanCap <- df_Q1tollRoadUsers %>%
  filter(person_value_toll > DailyTollCap)

# Get the number of cases
num_Q1tollRoadUsersPayMoreThanCap <- nrow(df_Q1tollRoadUsersPayMoreThanCap)
print(paste("Number of Q1 toll road users paying more than the daily toll cap =", num_Q1tollRoadUsersPayMoreThanCap))

# calculate % of toll road users paying more than the daily toll cap
percent_Q1tollRoadUsersPayMoreThanCap = num_Q1tollRoadUsersPayMoreThanCap / num_Q1tollRoadUsers
print(paste("Percent of Q1 toll road users paying more than the daily toll cap (out of all q1 toll road users) =", percent_Q1tollRoadUsersPayMoreThanCap))
# results: 99% of Q1 toll road users pay more than the cap (out of all Q1 toll road users)

# calculate % of toll road users paying more than the daily toll cap (out of all persons)
percent_Q1tollRoadUsersPayMoreThanCap_OutOfAllPersons = num_Q1tollRoadUsersPayMoreThanCap / total_population
print(paste("Percent of Q1 toll road users paying more than the daily toll cap (out of all persons) =", percent_Q1personPayMoreThanCap_OutOfAllPersons))
# results: Putting the number of Q1 toll road users who pay more than the cap in context. This is about 6% of the population.

#-----------------------------------------------
# do they make many trips or just very long trips
# look at a toll trip frequency table
#------------------------------------------

df_tollRoadUsersNumTripsTable <- df_tollRoadUsers %>%
  group_by(person_numtrips) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

# Print the table using kable
kable(df_tollRoadUsersNumTripsTable, caption = "Toll Trip Frequency Table of Toll Road Users", format = "markdown")
# results: 93% of the toll road users user make 1 or 2 toll trips in the simulated day
# it's surprising that the biggest group isn't 2 toll trips. TO-DO: investigate this. 


df_Q1tollRoadUsersPayMoreThanCapNumTripsTable <- df_Q1tollRoadUsersPayMoreThanCap %>%
  group_by(person_numtrips) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

# Print the table using kable
kable(df_Q1tollRoadUsersPayMoreThanCapNumTripsTable, caption = "Toll Trip Frequency Table of Q1 Toll Road Users Paying More Than the Toll Cap", format = "markdown")
# results: 95% of the toll road users user make 1 or 2 toll trips in the simulated day
# again, it's surprising that the biggest group isn't 2 toll trips. TO-DO: investigate this.  

# what does this mean for the "trip level toll cap"?
#--------------------------------------------------
# if we set the trip level toll cap to be half of the daily toll cap
# then 95% of the toll users will receive the cap (although those who made 1 trip only have to pay half of the daily toll cap)
