base_zip: "data/external/mtc/2023_TM161_IPA_35_20260217.zip"
output_root: "temp"

scenarios:
  - name: baseline
    skip_if_exists: false
    replacements: []

  - name: truck_updates
    skip_if_exists: false
    replacements:
      - source: "https://github.com/BayAreaMetro/travel-model-one/blob/tm1.7_truck_updates/model-files/RunIteration.bat"
        destination: "CTRAMP/RunIteration.bat"
      - source: "https://github.com/BayAreaMetro/travel-model-one/blob/tm1.7_truck_updates/model-files/scripts/nonres/TruckTimeOfDay.job"
        destination: "CTRAMP/scripts/nonres/TruckTimeOfDay.job"
      - source: "https://github.com/BayAreaMetro/travel-model-one/blob/tm1.7_truck_updates/model-files/scripts/nonres/TruckTripDistribution.job"
        destination: "CTRAMP/scripts/nonres/TruckTripDistribution.job"
      - source: "https://github.com/BayAreaMetro/travel-model-one/blob/tm1.7_truck_updates/model-files/scripts/nonres/TruckTripGeneration.job"
        destination: "CTRAMP/scripts/nonres/TruckTripGeneration.job"
